In [29]:
import glob,codecs,os,yaml
import pandas as pd
from unidecode import unidecode
from os.path import expanduser
def ding():
    os.system('afplay /System/Library/Sounds/Submarine.aiff')
from IPython.core.display import HTML,display

## ⚠️
Pour les cas où le genre des noms est marqué explicitement, on utilise *nomGenre=True*

In [30]:
%store -r numerosKalaba typeKalaba
%store -r anneeKalaba
# numerosKalaba=[1]
print anneeKalaba, numerosKalaba, typeKalaba
nomGenre=False

25 [5] Kalaba

In [31]:
debug=0
home = expanduser("~")
repertoire=home+"/sDrive/Cours/Bordeaux/L1-LinguistiqueGenerale/00-ProjetKalaba/"
annee=anneeKalaba
if typeKalaba!="Kanonik":
    serie=repertoire+"%d-K%d/"%(annee,numerosKalaba[0])
else:
    serie=repertoire+"%d-Kanoniks/"%(annee,numerosKalaba[0])
    nomsKalabas=[serie+"Kanonik-%02d/"%num for num in numerosKalaba]
print serie

/Users/gilles/sDrive/Cours/Bordeaux/L1-LinguistiqueGenerale/00-ProjetKalaba/25-K5/

In [32]:
nomDeclarationRad="Declarations-Radicaux.tex"
nomDeclarationDec="Declarations-Decoupages.tex"
nomTableauxRad="Tableaux-Gloses.yaml"
nomDeclaration="Declarations.tex"
nomTableaux="Tableaux.yaml"

In [33]:
flexion=pd.read_csv(serie+"Clozes.txt",sep=";",header=None, names=list(range(20)),encoding="utf8").dropna(axis='columns', how='all')
flexion.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15
0,#\tNOM,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,#,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,#,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,chefASgErg,chef,NOM,fojub,NaN,fojuboθ,fojub-o-θ,"NOM, CF=N1, Genre=A, Nombre=Sg, Cas=Erg",chef.A.N1-Sg-N1.Erg,4.0,chef,.A.N1,-Sg,-N1.Erg,NaN,NaN
4,chefASgAbs,chef,NOM,fojub,NaN,fojubo,fojub-o,"NOM, CF=N1, Genre=A, Nombre=Sg, Cas=Abs",chef.A.N1-Sg,3.0,chef,.A.N1,-Sg,NaN,NaN,NaN

In [34]:
categories=flexion[2].dropna().unique().tolist()
categories

[u'NOM', u'VER', u'PRO', u'DET', u'ADJ', u'PREP']

bFlex sélectionne les lignes non-vides correspondant à une catégorie

In [35]:
bFlex={c:(flexion[7].notnull()) & (flexion[2]==c.upper()) for c in categories}
flexion[bFlex["NOM"]]

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15
3,chefASgErg,chef,NOM,fojub,NaN,fojuboθ,fojub-o-θ,"NOM, CF=N1, Genre=A, Nombre=Sg, Cas=Erg",chef.A.N1-Sg-N1.Erg,4.0,chef,.A.N1,-Sg,-N1.Erg,NaN,NaN
4,chefASgAbs,chef,NOM,fojub,NaN,fojubo,fojub-o,"NOM, CF=N1, Genre=A, Nombre=Sg, Cas=Abs",chef.A.N1-Sg,3.0,chef,.A.N1,-Sg,NaN,NaN,NaN
5,chefASgDat,chef,NOM,fojub,NaN,fojubom,fojub-o-m,"NOM, CF=N1, Genre=A, Nombre=Sg, Cas=Dat",chef.A.N1-Sg-N1.Dat.Sg,4.0,chef,.A.N1,-Sg,-N1.Dat.Sg,NaN,NaN
6,chefASgObl,chef,NOM,fojub,NaN,fojubol,fojub-o-l,"NOM, CF=N1, Genre=A, Nombre=Sg, Cas=Obl",chef.A.N1-Sg-Obl,4.0,chef,.A.N1,-Sg,-Obl,NaN,NaN
7,chefAPauErg,chef,NOM,fojub,NaN,fojubiθ,fojub-i-θ,"NOM, CF=N1, Genre=A, Nombre=Pau, Cas=Erg",chef.A.N1-N1.Pau-N1.Erg,4.0,chef,.A.N1,-N1.Pau,-N1.Erg,NaN,NaN
8,chefAPauAbs,chef,NOM,fojub,NaN,fojubi,fojub-i,"NOM, CF=N1, Genre=A, Nombre=Pau, Cas=Abs",chef.A.N1-N1.Pau,3.0,chef,.A.N1,-N1.Pau,NaN,NaN,NaN
9,chefAPauDat,chef,NOM,fojub,NaN,ʒefojubi,ʒe-fojub-i,"NOM, CF=N1, Genre=A, Nombre=Pau, Cas=Dat",N1.Dat.Pau-chef.A.N1-N1.Pau,4.0,N1.Dat.Pau-,chef,.A.N1,-N1.Pau,NaN,NaN
10,chefAPauObl,chef,NOM,fojub,NaN,fojubil,fojub-i-l,"NOM, CF=N1, Genre=A, Nombre=Pau, Cas=Obl",chef.A.N1-N1.Pau-Obl,4.0,chef,.A.N1,-N1.Pau,-Obl,NaN,NaN
11,chefAPlErg,chef,NOM,fojub,fjbo,fobjibboð,racine(fojub)x1Vb2i33o-ð,"NOM, CF=N1, Genre=A, Nombre=Pl, Cas=Erg",chef.A.N1xN1.Pl-N1.Erg.Pl,4.0,chef,.A.N1,xN1.Pl,-N1.Erg.Pl,NaN,NaN
12,chefAPlAbs,chef,NOM,fojub,fjbo,fobjibbo,racine(fojub)x1Vb2i33o,"NOM, CF=N1, Genre=A, Nombre=Pl, Cas=Abs",chef.A.N1xN1.Pl,3.0,chef,.A.N1,xN1.Pl,NaN,NaN,NaN
13,chefAPlDat,chef,NOM,fojub,fjbo,ʒefobjibbom,ʒe+racine(fojub)x1Vb2i33o+m,"NOM, CF=N1, Genre=A, Nombre=Pl, Cas=Dat",N1.Dat.Pl+chef.A.N1xN1.Pl+N1.Dat.Pl,5.0,N1.Dat.Pl+,chef,.A.N1,xN1.Pl,+N1.Dat.Pl,NaN
14,chefAPlObl,chef,NOM,fojub,fjbo,fobjibbol,racine(fojub)x1Vb2i33o-l,"NOM, CF=N1, Genre=A, Nombre=Pl, Cas=Obl",chef.A.N1xN1.Pl-Obl,4.0,chef,.A.N1,xN1.Pl,-Obl,NaN,NaN
15,maraisASgErg,marais,NOM,vigam,NaN,vigamoθ,vigam-o-θ,"NOM, CF=N1, Genre=A, Nombre=Sg, Cas=Erg",marais.A.N1-Sg-N1.Erg,4.0,marais,.A.N1,-Sg,-N1.Erg,NaN,NaN
16,maraisASgAbs,marais,NOM,vigam,NaN,vigamo,vigam-o,"NOM, CF=N1, Genre=A, Nombre=Sg, Cas=Abs",marais.A.N1-Sg,3.0,marais,.A.N1,-Sg,NaN,NaN,NaN
17,maraisASgDat,marais,NOM,vigam,NaN,vigamom,vigam-o-m,"NOM, CF=N1, Genre=A, Nombre=Sg, Cas=Dat",marais.A.N1-Sg-N1.Dat.Sg,4.0,marais,.A.N1,-Sg,-N1.Dat.Sg,NaN,NaN
18,maraisASgObl,marais,NOM,vigam,NaN,vigamol,vigam-o-l,"NOM, CF=N1, Genre=A, Nombre=Sg, Cas=Obl",marais.A.N1-Sg-Obl,4.0,marais,.A.N1,-Sg,-Obl,NaN,NaN
19,maraisAPauErg,marais,NOM,vigam,NaN,vigamiθ,vigam-i-θ,"NOM, CF=N1, Genre=A, Nombre=Pau, Cas=Erg",marais.A.N1-N1.Pau-N1.Erg,4.0,marais,.A.N1,-N1.Pau,-N1.Erg,NaN,NaN
20,maraisAPauAbs,marais,NOM,vigam,NaN,vigami,vigam-i,"NOM, CF=N1, Genre=A, Nombre=Pau, Cas=Abs",marais.A.N1-N1.Pau,3.0,marais,.A.N1,-N1.Pau,NaN,NaN,NaN
21,maraisAPauDat,marais,NOM,vigam,NaN,ʒevigami,ʒe-vigam-i,"NOM, CF=N1, Genre=A, Nombre=Pau, Cas=Dat",N1.Dat.Pau-marais.A.N1-N1.Pau,4.0,N1.Dat.Pau-,marais,.A.N1,-N1.Pau,NaN,NaN
22,maraisAPauObl,marais,NOM,vigam,NaN,vigamil,vigam-i-l,"NOM, CF=N1, Genre=A, Nombre=Pau, Cas=Obl",marais.A.N1-N1.Pau-Obl,4.0,marais,.A.N1,-N1.Pau,-Obl,NaN,NaN
23,maraisAPlErg,marais,NOM,vigam,vgmi,vibgimmoð,racine(vigam)x1Vb2i33o-ð,"NOM, CF=N1, Genre=A, Nombre=Pl, Cas=Erg",marais.A.N1xN1.Pl-N1.Erg.Pl,4.0,marais,.A.N1,xN1.Pl,-N1.Erg.Pl,NaN,NaN
24,maraisAPlAbs,marais,NOM,vigam,vgmi,vibgimmo,racine(vigam)x1Vb2i33o,"NOM, CF=N1, Genre=A, Nombre=Pl, Cas=Abs",marais.A.N1xN1.Pl,3.0,marais,.A.N1,xN1.Pl,NaN,NaN,NaN
25,maraisAPlDat,marais,NOM,vigam,vgmi,ʒevibgimmom,ʒe+racine(vigam)x1Vb2i33o+m,"NOM, CF=N1, Genre=A, Nombre=Pl, Cas=Dat",N1.Dat.Pl+marais.A.N1xN1.Pl+N1.Dat.Pl,5.0,N1.Dat.Pl+,marais,.A.N1,xN1.Pl,+N1.Dat.Pl,NaN
26,maraisAPlObl,marais,NOM,vigam,vgmi,vibgimmol,racine(vigam)x1Vb2i33o-l,"NOM, CF=N1, Genre=A, Nombre=Pl, Cas=Obl",marais.A.N1xN1.Pl-Obl,4.0,marais,.A.N1,xN1.Pl,-Obl,NaN,NaN
27,placeASgErg,place,NOM,duwaŋ,NaN,duwaŋoθ,duwaŋ-o-θ,"NOM, CF=N1, Genre=A, Nombre=Sg, Cas=Erg",place.A.N1-Sg-N1.Erg,4.0,place,.A.N1,-Sg,-N1.Erg,NaN,NaN
28,placeASgAbs,place,NOM,duwaŋ,NaN,duwaŋo,duwaŋ-o,"NOM, CF=N1, Genre=A, Nombre=Sg, Cas=Abs",place.A.N1-Sg,3.0,place,.A.N1,-Sg,NaN,NaN,NaN
29,placeASgDat,place,NOM,duwaŋ,NaN,duwaŋom,duwaŋ-o-m,"NOM, CF=N1, Genre=A, Nombre=Sg, Cas=Dat",place.A.N1-Sg-N1.Dat.Sg,4.0,place,.A.N1,-Sg,-N1.Dat.Sg,NaN,NaN
30,placeASgObl,place,NOM,duwaŋ,NaN,duwaŋol,duwaŋ-o-l,"NOM, CF=N1, Genre=A, Nombre=Sg, Cas=Obl",place.A.N1-Sg-Obl,4.0,place,.A.N1,-Sg,-Obl,NaN,NaN
31,placeAPauErg,place,NOM,duwaŋ,NaN,duwaŋiθ,duwaŋ-i-θ,"NOM, CF=N1, Genre=A, Nombre=Pau, Cas=Erg",place.A.N1-N1.Pau-N1.Erg,4.0,place,.A.N1,-N1.Pau,-N1.Erg,NaN,NaN
32,placeAPauAbs,place,NOM,duwaŋ,NaN,duwaŋi,duwaŋ-i,"NOM, CF=N1, Genre=A, Nombre=Pau, Cas=Abs",place.A.N1-N1.Pau,3.0,place,.A.N1,-N1.Pau,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1425,villageoisDPauDat,villageois,NOM,baðuz,bðza,baðzoziŋ,racine(baðuz)x1V23o3i-ŋ,"NOM, CF=N4, Genre=D, Nombre=Pau, Cas=Dat",villageois.D.N4xN4.Pau-Dat,4.0,villageois,.D.N4,xN4.Pau,-Dat,NaN,NaN
1426,villageoisDPauObl,villageois,NOM,baðuz,bðza,baðzozil,racine(baðuz)x1V23o3i-l,"NOM, CF=N4, Genre=D, Nombre=Pau, Cas=Obl",villageois.D.N4xN4.Pau-Obl,4.0,villageois,.D.N4,xN4.Pau,-Obl,NaN,NaN
1427,villageoisDPlErg,villageois,NOM,baðuz,NaN,baðuzoθij,baðuz-oθi-j,"NOM, CF=N4, Genre=D, Nombre=Pl, Cas=Erg",villageois.D.N4-Pl-N4.Erg,4.0,villageois,.D.N4,-Pl,-N4.Erg,NaN,NaN
1428,villageoisDPlAbs,villageois,NOM,baðuz,NaN,baðuzoθif,baðuz-oθi-f,"NOM, CF=N4, Genre=D, Nombre=Pl, Cas=Abs",villageois.D.N4-Pl-N4.Abs.Pl,4.0,villageois,.D.N4,-Pl,-N4.Abs.Pl,NaN,NaN
1429,villageoisDPlDat,villageois,NOM,baðuz,NaN,baðuzoθiŋ,baðuz-oθi-ŋ,"NOM, CF=N4, Genre=D, Nombre=Pl, Cas=Dat",villageois.D.N4-Pl-Dat,4.0,villageois,.D.N4,-Pl,-Dat,NaN,NaN
1430,villageoisDPlObl,villageois,NOM,baðuz,NaN,mubaðuzoθi,mu-baðuz-oθi,"NOM, CF=N4, Genre=D, Nombre=Pl, Cas=Obl",N4.Obl.Pl-villageois.D.N4-Pl,4.0,N4.Obl.Pl-,villageois,.D.N4,-Pl,NaN,NaN
1431,levernDSgErg,lever-n,NOM,ŋiwað,NaN,θeŋiwaðaj,θe+ŋiwað+a-j,"NOM, CF=N4, Genre=D, Nombre=Sg, Cas=Erg",N4.Sg+leverN.D.N4+N4.Sg-N4.Erg,6.0,N4.Sg+,lever,N,.D.N4,+N4.Sg,-N4.Erg
1432,levernDSgAbs,lever-n,NOM,ŋiwað,NaN,θeŋiwaðab,θe+ŋiwað+a-b,"NOM, CF=N4, Genre=D, Nombre=Sg, Cas=Abs",N4.Sg+leverN.D.N4+N4.Sg-N4.Abs,6.0,N4.Sg+,lever,N,.D.N4,+N4.Sg,-N4.Abs
1433,levernDSgDat,lever-n,NOM,ŋiwað,NaN,θeŋiwaðaŋ,θe+ŋiwað+a-ŋ,"NOM, CF=N4, Genre=D, Nombre=Sg, Cas=Dat",N4.Sg+leverN.D.N4+N4.Sg-Dat,6.0,N4.Sg+,lever,N,.D.N4,+N4.Sg,-Dat
1434,levernDSgObl,lever-n,NOM,ŋiwað,NaN,θeŋiwaðal,θe+ŋiwað+a-l,"NOM, CF=N4, Genre=D, Nombre=Sg, Cas=Obl",N4.Sg+leverN.D.N4+N4.Sg-Obl,6.0,N4.Sg+,lever,N,.D.N4,+N4.Sg,-Obl
1435,levernDPauErg,lever-n,NOM,ŋiwað,ŋwði,ŋiwðoðij,racine(ŋiwað)x1V23o3i-j,"NOM, CF=N4, Genre=D, Nombre=Pau, Cas=Erg",leverN.D.N4xN4.Pau-N4.Erg,5.0,lever,N,.D.N4,xN4.Pau,-N4.Erg,NaN
1436,levernDPauAbs,lever-n,NOM,ŋiwað,ŋwði,ŋiwðoðib,racine(ŋiwað)x1V23o3i-b,"NOM, CF=N4, Genre=D, Nombre=Pau, Cas=Abs",leverN.D.N4xN4.Pau-N4.Abs,5.0,lever,N,.D.N4,xN4.Pau,-N4.Abs,NaN
1437,levernDPauDat,lever-n,NOM,ŋiwað,ŋwði,ŋiwðoðiŋ,racine(ŋiwað)x1V23o3i-ŋ,"NOM, CF=N4, Genre=D, Nombre=Pau, Cas=Dat",leverN.D.N4xN4.Pau-Dat,5.0,lever,N,.D.N4,xN4.Pau,-Dat,NaN
1438,levernDPauObl,lever-n,NOM,ŋiwað,ŋwði,ŋiwðoðil,racine(ŋiwað)x1V23o3i-l,"NOM, CF=N4, Genre=D, Nombre=Pau, Cas=Obl",leverN.D.N4xN4.Pau-Obl,5.0,lever,N,.D.N4,xN4.Pau,-Obl,NaN
1439,levernDPlErg,lever-n,NOM,ŋiwað,NaN,ŋiwaðoθij,ŋiwað-oθi-j,"NOM, CF=N4, Genre=D, Nombre=Pl, Cas=Erg",leverN.D.N4-Pl-N4.Erg,5.0,lever,N,.D.N4,-Pl,-N4.Erg,NaN
1440,levernDPlAbs,lever-n,NOM,ŋiwað,NaN,ŋiwaðoθif,ŋiwað-oθi-f,"NOM, CF=N4, Genre=D, Nombre=Pl, Cas=Abs",leverN.D.N4-Pl-N4.Abs.Pl,5.0,lever,N,.D.N4,-Pl,-N4.Abs.Pl,NaN
1441,levernDPlDat,lever-n,NOM,ŋiwað,NaN,ŋiwaðoθiŋ,ŋiwað-oθi-ŋ,"NOM, CF=N4, Genre=D, Nombre=Pl, Cas=Dat",leverN.D.N4-Pl-Dat,5.0,lever,N,.D.N4,-Pl,-Dat,NaN
1442,levernDPlObl,lever-n,NOM,ŋiwað,NaN,muŋiwaðoθi,mu-ŋiwað-oθi,"NOM, CF=N4, Genre=D, Nombre=Pl, Cas=Obl",N4.Obl.Pl-leverN.D.N4-Pl,5.0,N4.Obl.Pl-,lever,N,.D.N4,-Pl,NaN
1443,bucherDSgErg,bûcher,NOM,dakow,NaN,θedakowaj,θe+dakow+a-j,"NOM, CF=N4, Genre=D, Nombre=Sg, Cas=Erg",N4.Sg+bûcher.D.N4+N4.Sg-N4.Erg,5.0,N4.Sg+,bûcher,.D.N4,+N4.Sg,-N4.Erg,NaN
1444,bucherDSgAbs,bûcher,NOM,dakow,NaN,θedakowab,θe+dakow+a-b,"NOM, CF=N4, Genre=D, Nombre=Sg, Cas=Abs",N4.Sg+bûcher.D.N4+N4.Sg-N4.Abs,5.0,N4.Sg+,bûcher,.D.N4,+N4.Sg,-N4.Abs,NaN
1445,bucherDSgDat,bûcher,NOM,dakow,NaN,θedakowaŋ,θe+dakow+a-ŋ,"NOM, CF=N4, Genre=D, Nombre=Sg, Cas=Dat",N4.Sg+bûcher.D.N4+N4.Sg-Dat,5.0,N4.Sg+,bûcher,.D.N4,+N4.Sg,-Dat,NaN
1446,bucherDSgObl,bûcher,NOM,dakow,NaN,θedakowal,θe+dakow+a-l,"NOM, CF=N4, Genre=D, Nombre=Sg, Cas=Obl",N4.Sg+bûcher.D.N4+N4.Sg-Obl,5.0,N4.Sg+,bûcher,.D.N4,+N4.Sg,-Obl,NaN
1447,bucherDPauErg,bûcher,NOM,dakow,dkwa,dakwowij,racine(dakow)x1V23o3i-j,"NOM, CF=N4, Genre=D, Nombre=Pau, Cas=Erg",bûcher.D.N4xN4.Pau-N4.Erg,4.0,bûcher,.D.N4,xN4.Pau,-N4.Erg,NaN,NaN
1448,bucherDPauAbs,bûcher,NOM,dakow,dkwa,dakwowib,racine(dakow)x1V23o3i-b,"NOM, CF=N4, Genre=D, Nombre=Pau, Cas=Abs",bûcher.D.N4xN4.Pau-N4.Abs,4.0,bûcher,.D.N4,xN4.Pau,-N4.Abs,NaN,NaN
1449,bucherDPauDat,bûcher,NOM,dakow,dkwa,dakwowiŋ,racine(dakow)x1V23o3i-ŋ,"NOM, CF=N4, Genre=D, Nombre=Pau, Cas=Dat",bûcher.D.N4xN4.Pau-Dat,4.0,bûcher,.D.N4,xN4.Pau,-Dat,NaN,NaN
1450,bucherDPauObl,bûcher,NOM,dakow,dkwa,dakwowil,racine(dakow)x1V23o3i-l,"NOM, CF=N4, Genre=D, Nombre=Pau, Cas=Obl",bûcher.D.N4xN4.Pau-Obl,4.0,bûcher,.D.N4,xN4.Pau,-Obl,NaN,NaN
1451,bucherDPlErg,bûcher,NOM,dakow,NaN,dakowoθij,dakow-oθi-j,"NOM, CF=N4, Genre=D, Nombre=Pl, Cas=Erg",bûcher.D.N4-Pl-N4.Erg,4.0,bûcher,.D.N4,-Pl,-N4.Erg,NaN,NaN
1452,bucherDPlAbs,bûcher,NOM,dakow,NaN,dakowoθif,dakow-oθi-f,"NOM, CF=N4, Genre=D, Nombre=Pl, Cas=Abs",bûcher.D.N4-Pl-N4.Abs.Pl,4.0,bûcher,.D.N4,-Pl,-N4.Abs.Pl,NaN,NaN
1453,bucherDPlDat,bûcher,NOM,dakow,NaN,dakowoθiŋ,dakow-oθi-ŋ,"NOM, CF=N4, Genre=D, Nombre=Pl, Cas=Dat",bûcher.D.N4-Pl-Dat,4.0,bûcher,.D.N4,-Pl,-Dat,NaN,NaN
1454,bucherDPlObl,bûcher,NOM,dakow,NaN,mudakowoθi,mu-dakow-oθi,"NOM, CF=N4, Genre=D, Nombre=Pl, Cas=Obl",N4.Obl.Pl-bûcher.D.N4-Pl,4.0,N4.Obl.Pl-,bûcher,.D.N4,-Pl,NaN,NaN

### Analyse de la case
on fait un dict à partir de la case pour éclater en colonne puis faire un pivot_table

In [36]:
def makeParadigme(row):
    result={}
    parts=row["Case"].split(", ")
    for part in parts[1:]:
        attr,val=part.split("=")
        result[attr.strip()]=val
    return result

# Tableaux pour une catégorie

In [37]:
def reindexNombre(tableau):
    result=tableau
    if "Du" in tableau.columns:
        result=tableau.reindex("Sg Du Pl".split(" "),axis=1)
    elif "Pau" in tableau.columns:
        result=tableau.reindex("Sg Pau Pl".split(" "),axis=1)
    elif "Sg" in tableau.columns:
        result=tableau.reindex("Sg Pl".split(" "),axis=1)
    return result

def reindexPers(tableau):
    result=tableau
    if "3Du" in tableau.columns:
        result=tableau.reindex("3Sg 3Du 3Pl".split(" "),axis=1)
    elif "3Pau" in tableau.columns:
        result=tableau.reindex("3Sg 3Pau 3Pl".split(" "),axis=1)
    elif "3Sg" in tableau.columns:
        result=tableau.reindex("3Sg 3Pl".split(" "),axis=1)
    return result

def reindexTableau(tableau):
    return reindexNombre(reindexPers(tableau))

In [38]:
def makeTableaux(cat):
    # sel sélectionne la catégorie cat dans flexion
    # les colonnes 1, 6 et 7 correspondent à la catégorie, la forme et la case
    sel=bFlex[cat]
    catTableaux={}
    catCF={}
    radCF={}
    cfLexemes={}

    # la colonnne 3 contient le radical
    lDF=flexion[sel][[1,6,7]]
    lDF=flexion[sel][[1,3,6,7]]
    lDF.columns=(u"%s Radical Forme Case"%cat).split(" ")
    # on ajoute une colonne avec un dict correspondant à attribut:valeur
    lDF["dCell"]=lDF.apply(makeParadigme,axis=1)
    if lDF.iloc[0]["dCell"]!={}:
        # on éclate le dict attribut:valeur en colonnes
        # on calcule les dimensions du tableau croisé pour pivot_table
        dfCat=pd.concat([lDF.drop(['Case',"dCell"], axis=1), lDF['dCell'].apply(pd.Series)], axis=1)
        setColonnes=set(dfCat.columns.tolist())
        if cat=="NOM" and not nomGenre:
            setColonnes-=set(["Genre"])
        if "Nombre" in setColonnes:
            colonnes="Nombre"
            lignes=setColonnes-set([cat,"Radical","Forme","CF","Nombre"])
        elif "Pers" in setColonnes:
            colonnes="Pers"
            lignes=list(setColonnes-set([cat,"Radical","Forme","CF","Pers"]))
        if debug: print colonnes, lignes
        # on fait la liste des lexèmes de la catégorie cat
        listCat=dfCat[cat].unique().tolist()
        if debug: display(dfCat.head())
        for l in listCat:
            print l
            catL=dfCat[dfCat[cat].str.encode("utf8")==l.encode("utf8")]
            radical=catL["Radical"].values[0]
            if "CF" in dfCat.columns:
                lCF=catL["CF"].values[0]
                if lCF not in cfLexemes:
                    cfLexemes[lCF]=[]
                cfLexemes[lCF].append(l)
                #
                # reindexNombre présente les colonnes concernant le nombre dans l'ordre traditionnel
                # SG < DU/PAU < PL
                #
                if lCF not in catCF:
                    catTableaux[lCF]=pd.pivot_table(catL,index=lignes,columns=colonnes,values="Forme", aggfunc='first')
                    catCF[lCF]=l
                    radCF[lCF]=radical
            elif cat=="NOM" and nomGenre:
                lCF=catL["Genre"].values[0]
                if lCF not in cfLexemes:
                    cfLexemes[lCF]=[]
                cfLexemes[lCF].append(l)
                if lCF not in catCF:
                    catTableaux[lCF]=pd.pivot_table(catL,index=lignes,columns=colonnes,values="Forme", aggfunc='first')
                    catCF[lCF]=l
                    radCF[lCF]=radical
            else:
                catCF[cat]=l
                radCF[cat]=radical
                catTableaux[cat]=pd.pivot_table(catL,index=lignes,columns=colonnes,values="Forme", aggfunc='first')
        for t in catTableaux:   
            if debug: display(HTML("<h1>%s, %s</h1>"%(t,catCF[t])),reindexTableau(catTableaux[t]))
#             print t,catCF[t],radCF[t]
#             print reindexTableau(catTableaux[t]).to_latex(multirow=True)
    return catTableaux,cfLexemes,catCF,radCF

In [39]:
tableaux={}
tableauxLatex=[]
lexemesCF={}
cfLexs={}
cfRads={}
tableauxLatex.append(ur"\subsection*{Tableaux de flexion}")
for cat in "DET PRO NOM ADJ VER".split(" "):
#    print ur"\section{%s}"%cat
    tableauxLatex.append(ur"\subsubsection*{%s}"%cat)
    tableaux[cat],lexemesCF[cat],cfLexs[cat],cfRads[cat]=makeTableaux(cat)
#     print tableaux[cat]
#     print lexemesCF[cat]
    for t in tableaux[cat]:
#        print t
        tableauxLatex.append(u"\\needspace{6\\baselineskip}")
        tableauxLatex.append(u"\\noindent\n%s %s => %s\\\\"%(t,cfLexs[cat][t],cfRads[cat][t]))
        tableauxLatex.append(reindexTableau(tableaux[cat][t]).to_latex(multirow=True)+u" \\\\ \\medskip")
        tableauxLatex.append("")
print "\n".join(tableauxLatex)

DEM
DEF
IND
PRO
chef
marais
place
raison
Clemencia
sortilège
lune
thé
homme
excuse
chasseur
mère
serpent
donjon
chambre
corps
Katisha
plaine
chemin
disparition
feu
gorge
esprit
café
Kaleb
souris
Mahira
robe
obscurité
oeil
autruche
couteau
douleur
démon
créature
ombre
harmonie
sorcier
jour
cuisine
enfant
arbre
père
dégât
Agathos
héros
livre
sort
chatte
côté
demande
colère
nouvelle-n
jardin
lance
cri
construction
mort
milieu
combattant
louve
Hoderi
bras
Freja
légende
lueur
hurlement
table
souffrance
infirmière
combat
manoir
loup
femme
matin
voleuse
dragon
Nicole
dernier-n
Elphaba
chat
visage
grimoire
maître
villageoise
viande
lumière
croc
soeur
maison
coussin
village
crapaud
légume
proximité
lit
peau
œuf
gargouille
caillou
fruit
histoire
vengeance
Nabil
blessure
fille
parent
balai
forêt
garçon
nuit
main
vote
tornade
coup
Violette
coyote
poisson
villageois
lever-n
bûcher
quatre
courageux
six
deux
vilain
effrayé
cinq
vert
méchant
blanc
gros
héroïque
autre
petit
sept
maigre
nouveau
rouge
dernier
nombreux
bas
profond
noir
trois
treize
terrible
troisième
grand
suivant
différent
disparu
blessé
jaune
furieux
approcher
sortir-mov
disparaître
retourner
manquer-med
arriver
pleurer-act
vivre
mourir
entrer
rêvasser
tourner-mov
tomber
hurler
revenir
courir
brûler-med
aller
nuire
dormir
sauter
passer
jardiner
partir
parler
voler-act
descendre
redevenir
envahir
fuir
jeter
attraper
illustrer
prendre
pousser
inquiéter
cacher
chasser-act
accueillir
planter
protéger
surplomber
acheter
pendre
interroger
donner
boire
montrer
détester
pleurer
avoir
transformer
voter
chasser-mov
remercier
raconter
brûler
chercher
reconstruire
demander
voler
enlever
connaître
placer
allumer
lancer
lever
survoler
supporter
recouvrir
compter
être
ressusciter
arrêter
changer
posséder
reconnaître
dévorer
transpercer
échanger
noyer
préparer
embrasser
porter
faire
apporter
découvrir
excuser
nourrir
rejoindre
présenter
manger
enfermer
offrir
voir
\subsection*{Tableaux de flexion}
\subsubsection*{DET}
\needspace{6\baselineskip}
\noindent
DET IND => l\\
\begin{tabular}{lllll}
\toprule
    & Nombre &       Sg &      Pau &       Pl \\
Cas & Genre &          &          &          \\
\midrule
\multirow{4}{*}{Abs} & A &    l-a-b &    l-a-v &    l-a-n \\
    & B &    l-a-b &    l-a-v &    l-a-n \\
    & C &    l-e-p &    l-e-f &    l-e-ŋ \\
    & D &    l-e-p &    l-e-f &    l-e-n \\
\cline{1-5}
\multirow{4}{*}{Dat} & A &  l-a-b-a &  l-a-v-a &  l-a-n-a \\
    & B &  l-a-b-a &  l-a-v-a &  l-a-n-a \\
    & C &  l-e-p-a &  l-e-f-a &  l-e-ŋ-a \\
    & D &  l-e-p-a &  l-e-f-a &  l-e-n-a \\
\cline{1-5}
\multirow{4}{*}{Erg} & A &  l-a-b-e &  l-a-v-e &  l-a-n-e \\
    & B &  l-a-b-e &  l-a-v-e &  l-a-n-e \\
    & C &  l-e-p-e &  l-e-f-e &  l-e-ŋ-e \\
    & D &  l-e-p-e &  l-e-f-e &  l-e-n-e \\
\cline{1-5}
\multirow{4}{*}{Obl} & A &  l-a-b-o &  l-a-v-o &  l-a-n-o \\
    & B &  l-a-b-o &  l-a-v-o &  l-a-n-o \\
    & C &  l-e-p-o &  l-e-f-o &  l-e-ŋ-o \\
    & D &  l-e-p-o &  l-e-f-o &  l-e-n-o \\
\bottomrule
\end{tabular}
 \\ \medskip

\subsubsection*{PRO}
\needspace{6\baselineskip}
\noindent
PRO PRO => r\\
\begin{tabular}{lllll}
\toprule
    & Nombre &        Sg &       Pau &        Pl \\
Cas & Genre &           &           &           \\
\midrule
\multirow{4}{*}{Abs} & A &    r-a-st &    r-a-ks &    r-a-sp \\
    & B &    r-o-st &    r-o-ks &    r-o-sp \\
    & C &    r-e-st &    r-e-ks &    r-e-sp \\
    & D &    r-i-st &    r-i-ks &    r-i-sp \\
\cline{1-5}
\multirow{4}{*}{Dat} & A &  r-a-st-e &  r-a-ks-e &  r-a-sp-e \\
    & B &  r-o-st-e &  r-o-ks-e &  r-o-sp-e \\
    & C &  r-e-st-e &  r-e-ks-e &  r-e-sp-e \\
    & D &  r-i-st-e &  r-i-ks-e &  r-i-sp-e \\
\cline{1-5}
\multirow{4}{*}{Erg} & A &  r-a-st-i &  r-a-ks-i &  r-a-sp-i \\
    & B &  r-o-st-i &  r-o-ks-i &  r-o-sp-i \\
    & C &  r-e-st-i &  r-e-ks-i &  r-e-sp-i \\
    & D &  r-i-st-i &  r-i-ks-i &  r-i-sp-i \\
\cline{1-5}
\multirow{4}{*}{Obl} & A &  r-a-st-u &  r-a-ks-u &  r-a-sp-u \\
    & B &  r-o-st-u &  r-o-ks-u &  r-o-sp-u \\
    & C &  r-e-st-u &  r-e-ks-u &  r-e-sp-u \\
    & D &  r-i-st-u &  r-i-ks-u &  r-i-sp-u \\
\bottomrule
\end{tabular}
 \\ \medskip

\subsubsection*{NOM}
\needspace{6\baselineskip}
\noindent
N1 chef => fojub\\
\begin{tabular}{llll}
\toprule
Nombre &         Sg &         Pau &                           Pl \\
Cas &            &             &                              \\
\midrule
Abs &    fojub-o &     fojub-i &       racine(fojub)x1Vb2i33o \\
Dat &  fojub-o-m &  ʒe-fojub-i &  ʒe+racine(fojub)x1Vb2i33o+m \\
Erg &  fojub-o-θ &   fojub-i-θ &     racine(fojub)x1Vb2i33o-ð \\
Obl &  fojub-o-l &   fojub-i-l &     racine(fojub)x1Vb2i33o-l \\
\bottomrule
\end{tabular}
 \\ \medskip

\needspace{6\baselineskip}
\noindent
N2 thé => letig\\
\begin{tabular}{llll}
\toprule
Nombre &          Sg &                       Pau &                        Pl \\
Cas &             &                           &                           \\
\midrule
Abs &   letig-o-p &   racine(letig)x1V23oθi-p &   racine(letig)x1V22i3o-p \\
Dat &   letig-o-ŋ &   racine(letig)x1V23oθi-ŋ &   racine(letig)x1V22i3o-ŋ \\
Erg &  ʒo-letig-o &  ʒo-racine(letig)x1V23oθi &  ʒo-racine(letig)x1V22i3o \\
Obl &   letig-o-s &   racine(letig)x1V23oθi-l &   racine(letig)x1V22i3o-l \\
\bottomrule
\end{tabular}
 \\ \medskip

\needspace{6\baselineskip}
\noindent
N3 chambre => figam\\
\begin{tabular}{llll}
\toprule
Nombre &                       Sg &                      Pau &           Pl \\
Cas &                          &                          &              \\
\midrule
Abs &  racine(figam)x1V22u3i-p &  racine(figam)x1V23oθi-g &  figam-oθi-g \\
Dat &  racine(figam)x1V22u3i-ŋ &  racine(figam)x1V23oθi-ŋ &  figam-oθi-ŋ \\
Erg &  racine(figam)x1V22u3i-v &  racine(figam)x1V23oθi-ʒ &  figam-oθi-ʒ \\
Obl &  racine(figam)x1V22u3i-l &  racine(figam)x1V23oθi-ʒ &  figam-oθi-l \\
\bottomrule
\end{tabular}
 \\ \medskip

\needspace{6\baselineskip}
\noindent
N4 gorge => buʃog\\
\begin{tabular}{llll}
\toprule
Nombre &            Sg &                      Pau &            Pl \\
Cas &               &                          &               \\
\midrule
Abs &  θe+buʃog+a-b &  racine(buʃog)x1V23o3i-b &   buʃog-oθi-f \\
Dat &  θe+buʃog+a-ŋ &  racine(buʃog)x1V23o3i-ŋ &   buʃog-oθi-ŋ \\
Erg &  θe+buʃog+a-j &  racine(buʃog)x1V23o3i-j &   buʃog-oθi-j \\
Obl &  θe+buʃog+a-l &  racine(buʃog)x1V23o3i-l &  mu-buʃog-oθi \\
\bottomrule
\end{tabular}
 \\ \medskip

\subsubsection*{ADJ}
\needspace{6\baselineskip}
\noindent
A1 quatre => bufoʃ\\
\begin{tabular}{lllll}
\toprule
    & Nombre &               Sg &                          Pau &               Pl \\
Cas & Genre &                  &                              &                  \\
\midrule
\multirow{4}{*}{Abs} & A &       bufoʃ-oʃ-a &       racine(bufoʃ)x1V23a3-a &       bufoʃ-eʒ-a \\
    & B &    le+bufoʃ-oʃ+a &    le+racine(bufoʃ)x1V23a3+a &    le+bufoʃ-eʒ+a \\
    & C &      bufoʃ-oʃ-le &      racine(bufoʃ)x1V23a3-le &      bufoʃ-eʒ-le \\
    & D &       bufoʃ-oʃ-e &       racine(bufoʃ)x1V23a3-e &       bufoʃ-eʒ-e \\
\cline{1-5}
\multirow{4}{*}{Dat} & A &     bufoʃ-oʃ-a-θ &     racine(bufoʃ)x1V23a3-a-θ &     bufoʃ-eʒ-a-θ \\
    & B &  le+bufoʃ-oʃ+a-θ &  le+racine(bufoʃ)x1V23a3+a-θ &  le+bufoʃ-eʒ+a-θ \\
    & C &    bufoʃ-oʃ-le-θ &    racine(bufoʃ)x1V23a3-le-θ &    bufoʃ-eʒ-le-θ \\
    & D &     bufoʃ-oʃ-e-θ &     racine(bufoʃ)x1V23a3-e-θ &     bufoʃ-eʒ-e-θ \\
\cline{1-5}
\multirow{4}{*}{Erg} & A &     bufoʃ-oʃ-a-ŋ &     racine(bufoʃ)x1V23a3-a-ŋ &     bufoʃ-eʒ-a-ŋ \\
    & B &  le+bufoʃ-oʃ+a-ŋ &  le+racine(bufoʃ)x1V23a3+a-ŋ &  le+bufoʃ-eʒ+a-ŋ \\
    & C &    bufoʃ-oʃ-le-ŋ &    racine(bufoʃ)x1V23a3-le-ŋ &    bufoʃ-eʒ-le-ŋ \\
    & D &     bufoʃ-oʃ-e-ŋ &     racine(bufoʃ)x1V23a3-e-ŋ &     bufoʃ-eʒ-e-ŋ \\
\cline{1-5}
\multirow{4}{*}{Obl} & A &     bufoʃ-oʃ-a-l &     racine(bufoʃ)x1V23a3-a-l &     bufoʃ-eʒ-a-l \\
    & B &  le+bufoʃ-oʃ+a-l &  le+racine(bufoʃ)x1V23a3+a-l &  le+bufoʃ-eʒ+a-l \\
    & C &    bufoʃ-oʃ-le-l &    racine(bufoʃ)x1V23a3-le-l &    bufoʃ-eʒ-le-l \\
    & D &     bufoʃ-oʃ-e-l &     racine(bufoʃ)x1V23a3-e-l &     bufoʃ-eʒ-e-l \\
\bottomrule
\end{tabular}
 \\ \medskip

\needspace{6\baselineskip}
\noindent
A2 rouge => labið\\
\begin{tabular}{lllll}
\toprule
    & Nombre &               Sg &                          Pau &                             Pl \\
Cas & Genre &                  &                              &                                \\
\midrule
\multirow{4}{*}{Abs} & A &       labið-oʃ-e &       racine(labið)x1V23a3-e &       racine(labið)xsi1a12o3-e \\
    & B &    le+labið-oʃ+a &    le+racine(labið)x1V23a3+a &    le+racine(labið)xsi1a12o3+a \\
    & C &         labið-oʃ &         racine(labið)x1V23a3 &         racine(labið)xsi1a12o3 \\
    & D &    le+labið-oʃ+e &    le+racine(labið)x1V23a3+e &    le+racine(labið)xsi1a12o3+e \\
\cline{1-5}
\multirow{4}{*}{Dat} & A &     labið-oʃ-e-θ &     racine(labið)x1V23a3-e-θ &     racine(labið)xsi1a12o3-e-θ \\
    & B &  le+labið-oʃ+a-θ &  le+racine(labið)x1V23a3+a-θ &  le+racine(labið)xsi1a12o3+a-θ \\
    & C &       labið-oʃ-θ &       racine(labið)x1V23a3-θ &       racine(labið)xsi1a12o3-θ \\
    & D &  le+labið-oʃ+e-θ &  le+racine(labið)x1V23a3+e-θ &  le+racine(labið)xsi1a12o3+e-θ \\
\cline{1-5}
\multirow{4}{*}{Erg} & A &     labið-oʃ-e-ŋ &     racine(labið)x1V23a3-e-ŋ &     racine(labið)xsi1a12o3-e-ŋ \\
    & B &  le+labið-oʃ+a-ŋ &  le+racine(labið)x1V23a3+a-ŋ &  le+racine(labið)xsi1a12o3+a-ŋ \\
    & C &       labið-oʃ-ŋ &       racine(labið)x1V23a3-ŋ &       racine(labið)xsi1a12o3-ŋ \\
    & D &  le+labið-oʃ+e-ŋ &  le+racine(labið)x1V23a3+e-ŋ &  le+racine(labið)xsi1a12o3+e-ŋ \\
\cline{1-5}
\multirow{4}{*}{Obl} & A &     labið-oʃ-e-l &     racine(labið)x1V23a3-e-l &     racine(labið)xsi1a12o3-e-l \\
    & B &  le+labið-oʃ+a-l &  le+racine(labið)x1V23a3+a-l &  le+racine(labið)xsi1a12o3+a-l \\
    & C &       labið-oʃ-l &       racine(labið)x1V23a3-l &       racine(labið)xsi1a12o3-l \\
    & D &  le+labið-oʃ+e-l &  le+racine(labið)x1V23a3+e-l &  le+racine(labið)xsi1a12o3+e-l \\
\bottomrule
\end{tabular}
 \\ \medskip

\subsubsection*{VER}
\needspace{6\baselineskip}
\noindent
V1 approcher => luθaʒ\\
\begin{tabular}{lllll}
\toprule
    & Pers &                     3Sg &                      3Pau &                       3Pl \\
Temps & Genre &                         &                           &                           \\
\midrule
\multirow{4}{*}{PRS} & A &  racine(luθaʒ)x1V1a23-u &  racine(luθaʒ)x1V1a23-u-w &  racine(luθaʒ)x1V1a23-u-ŋ \\
    & B &  racine(luθaʒ)x1V1a23-o &  racine(luθaʒ)x1V1a23-o-w &  racine(luθaʒ)x1V1a23-o-ŋ \\
    & C &  racine(luθaʒ)x1V1a23-i &  racine(luθaʒ)x1V1a23-i-w &  racine(luθaʒ)x1V1a23-i-ŋ \\
    & D &  racine(luθaʒ)x1V1a23-e &  racine(luθaʒ)x1V1a23-e-w &  racine(luθaʒ)x1V1a23-e-ŋ \\
\cline{1-5}
\multirow{4}{*}{PST} & A &              luθaʒ-ow-u &              luθaʒ-ow-u-w &              luθaʒ-ow-u-ŋ \\
    & B &              luθaʒ-ow-o &              luθaʒ-ow-o-w &              luθaʒ-ow-o-ŋ \\
    & C &              luθaʒ-ow-i &              luθaʒ-ow-i-w &              luθaʒ-ow-i-ŋ \\
    & D &              luθaʒ-ow-e &              luθaʒ-ow-e-w &              luθaʒ-ow-e-ŋ \\
\bottomrule
\end{tabular}
 \\ \medskip

\needspace{6\baselineskip}
\noindent
V2 hurler => siren\\
\begin{tabular}{lllll}
\toprule
    & Pers &                       3Sg &                      3Pau &                       3Pl \\
Temps & Genre &                           &                           &                           \\
\midrule
\multirow{4}{*}{PRS} & A &  racine(siren)x1V1a23-u-j &  racine(siren)x1V1a23-u-k &  racine(siren)x1V1a23-u-k \\
    & B &  racine(siren)x1V1a23-u-j &  racine(siren)x1V1a23-u-k &  racine(siren)x1V1a23-u-k \\
    & C &  racine(siren)x1V1a23-e-j &  racine(siren)x1V1a23-e-k &  racine(siren)x1V1a23-e-k \\
    & D &  racine(siren)x1V1a23-e-j &  racine(siren)x1V1a23-e-k &  racine(siren)x1V1a23-e-k \\
\cline{1-5}
\multirow{4}{*}{PST} & A &  racine(siren)x1V2a23-u-j &  racine(siren)x1V2a23-u-k &  racine(siren)x1V2a23-u-k \\
    & B &  racine(siren)x1V2a23-u-j &  racine(siren)x1V2a23-u-k &  racine(siren)x1V2a23-u-k \\
    & C &  racine(siren)x1V2a23-e-j &  racine(siren)x1V2a23-e-k &  racine(siren)x1V2a23-e-k \\
    & D &  racine(siren)x1V2a23-e-j &  racine(siren)x1V2a23-e-k &  racine(siren)x1V2a23-e-k \\
\bottomrule
\end{tabular}
 \\ \medskip

# Liste des lexèmes par CF

=> à intégrer aux tableaux...

In [40]:
cfLatex=[]
cfLatex.append(ur"\subsection*{Classes flexionnelles}")
for cat in "NOM ADJ VER DET".split(" "):
    classeCat=lexemesCF[cat]
    if classeCat:
        if debug: print cat+" : "
        cfLatex.append(cat+" : ")
        if debug: print ur"\begin{description}"
        cfLatex.append(ur"\begin{description}")
        for c in classeCat:
            if debug: print ur"\item[- %s] %s"%(c,", ".join(sorted(classeCat[c])))
            cfLatex.append(ur"\item[- %s] %s"%(c,", ".join(sorted(classeCat[c]))))
        if debug: print ur"\end{description}"
        cfLatex.append(ur"\end{description}")
if len(cfLatex)<2:
    cfLatex=[]
print "\n".join(cfLatex)

\subsection*{Classes flexionnelles}
NOM :
\begin{description}
\item[- N1] Clemencia, Freja, Hoderi, autruche, bras, chef, combattant, coussin, couteau, crapaud, créature, douleur, démon, lit, louve, lune, légende, légume, maison, marais, milieu, mort, obscurité, oeil, peau, place, proximité, raison, sortilège, village
\item[- N2] Nabil, arbre, blessure, caillou, chasseur, combat, cuisine, donjon, enfant, excuse, fruit, gargouille, harmonie, histoire, homme, hurlement, infirmière, jour, loup, lueur, manoir, mère, ombre, serpent, sorcier, souffrance, table, thé, vengeance, œuf
\item[- N3] Agathos, Elphaba, Katisha, Nicole, balai, chambre, chat, chatte, chemin, corps, dernier-n, disparition, dragon, dégât, femme, feu, fille, forêt, garçon, héros, livre, main, matin, nuit, parent, plaine, père, sort, voleuse, vote
\item[- N4] Kaleb, Mahira, Violette, bûcher, café, colère, construction, coup, coyote, cri, croc, côté, demande, esprit, gorge, grimoire, jardin, lance, lever-n, lumière, maître, nouvelle-n, poisson, robe, soeur, souris, tornade, viande, villageois, villageoise, visage
\end{description}
ADJ :
\begin{description}
\item[- A1] autre, blanc, cinq, courageux, deux, effrayé, gros, héroïque, maigre, méchant, nouveau, petit, quatre, sept, six, vert, vilain
\item[- A2] bas, blessé, dernier, différent, disparu, furieux, grand, jaune, noir, nombreux, profond, rouge, suivant, terrible, treize, trois, troisième
\end{description}
VER :
\begin{description}
\item[- V1] accueillir, acheter, approcher, arriver, attraper, avoir, boire, brûler, cacher, chasser-act, chasser-mov, chercher, demander, descendre, disparaître, donner, détester, entrer, envahir, fuir, illustrer, inquiéter, interroger, jeter, manquer-med, montrer, mourir, pendre, planter, pleurer, pleurer-act, pousser, prendre, protéger, raconter, reconstruire, redevenir, remercier, retourner, rêvasser, sortir-mov, surplomber, tomber, tourner-mov, transformer, vivre, voler, voter
\item[- V2] aller, allumer, apporter, arrêter, brûler-med, changer, compter, connaître, courir, dormir, découvrir, dévorer, embrasser, enfermer, enlever, excuser, faire, hurler, jardiner, lancer, lever, manger, nourrir, noyer, nuire, offrir, parler, partir, passer, placer, porter, posséder, préparer, présenter, reconnaître, recouvrir, rejoindre, ressusciter, revenir, sauter, supporter, survoler, transpercer, voir, voler-act, échanger, être
\end{description}

# Liste des noms par genre

- on ajoute une colonne genre en coupant dans la matrice de traits
- on fait la liste des genres
- on fait la liste des noms par genre
- on fabrique la structure LaTeX

In [41]:
genresLatex=[]

genresLatex.append(ur"\subsection*{Genre des noms}")

# Ajout de la colonne genre
flexion["genre"]=flexion[bFlex["NOM"]][7].str.extract("Genre=(.+?),")

# Liste des genres
genres=sorted([g for g in flexion["genre"].unique().tolist() if isinstance(g,unicode)])
genreNoms={}

# Liste des noms par genre
for g in genres:
    genreNoms[g]=flexion[flexion.genre==g][1].unique().tolist()

# LaTeX
if debug: print ur"\begin{description}"
genresLatex.append(ur"\begin{description}")
for g in genres:
    if debug: print ur"\item[- %s]"%g, ", ".join(sorted(genreNoms[g]))
    genresLatex.append(ur"\item[- %s] %s"%(g, ", ".join(sorted(genreNoms[g]))))
if debug: print ur"\end{description}"
genresLatex.append(ur"\end{description}")

print "\n".join(genresLatex)

\subsection*{Genre des noms}
\begin{description}
\item[- A] Clemencia, Kaleb, Katisha, Mahira, café, chambre, chasseur, chef, chemin, corps, disparition, donjon, esprit, excuse, feu, gorge, homme, lune, marais, mère, place, plaine, raison, robe, serpent, sortilège, souris, thé
\item[- B] Elphaba, Freja, Hoderi, Nicole, bras, chat, combat, combattant, croc, dernier-n, dragon, femme, grimoire, hurlement, infirmière, loup, louve, lueur, lumière, légende, manoir, matin, maître, milieu, mort, soeur, souffrance, table, viande, villageoise, visage, voleuse
\item[- C] Agathos, arbre, autruche, chatte, colère, construction, couteau, cri, créature, cuisine, côté, demande, douleur, dégât, démon, enfant, harmonie, héros, jardin, jour, lance, livre, nouvelle-n, obscurité, oeil, ombre, père, sorcier, sort
\item[- D] Nabil, Violette, balai, blessure, bûcher, caillou, coup, coussin, coyote, crapaud, fille, forêt, fruit, gargouille, garçon, histoire, lever-n, lit, légume, main, maison, nuit, parent, peau, poisson, proximité, tornade, vengeance, village, villageois, vote, œuf
\end{description}

# Calcul des remplissages de paradigmes
- filledCells contient les informations exportées par Phrases2
- sortLevel permet de mettre les noms des traits dans l'ordre logique
- filledTable fait le tableau du remplissage pour une catégorie avec un pivot_table
    - on lui passe 
        - le filledCells de la catégorie
        - la colonne du lexème
        - les colonnes qu'on veut mettre en ligne dans le tableau du paradigme
        - les colonnes qu'on veut mettre en colonnes dans le tableau du paradigme

In [42]:
with open(serie+"FilledCells.yaml", 'r') as stream:
    filledCells=yaml.safe_load(stream)
filledCells["VER"]=[v.replace(".Trois",".3") for v in filledCells["VER"]]
filledCells

{'ADJ': ['maigre.A1.C.PAU.Erg',
  u'bless\xe9.A2.C.PL.Abs',
  'deux.A1.A.PAU.obl',
  'gros.A1.D.PL.Abs',
  'terrible.A2.A.PL.obl',
  'cinq.A1.D.PAU.obl',
  'suivant.A2.B.PL.Erg',
  'deux.A1.C.PAU.Dat',
  'gros.A1.B.PAU.erg',
  'deux.A1.A.PAU.erg',
  u'bless\xe9.A2.B.PAU.Erg',
  'trois.A2.D.PAU.Abs',
  'rouge.A2.C.SG.Dat',
  u'm\xe9chant.A1.C.PL.Abs',
  'rouge.A2.D.PAU.Abs',
  'terrible.A2.C.SG.Erg',
  'terrible.A2.B.PAU.Erg',
  'deux.A1.B.PAU.obl',
  'cinq.A1.A.PAU.Abs',
  'maigre.A1.C.PAU.obl',
  'deux.A1.A.PAU.Erg',
  'petit.A1.A.PAU.Erg',
  u'diff\xe9rent.A2.A.SG.Abs',
  'quatre.A1.C.PAU.Abs',
  'grand.A2.A.SG.Abs',
  'deux.A1.D.PAU.Dat',
  'disparu.A2.C.PAU.Abs',
  'petit.A1.A.PL.Erg',
  'deux.A1.B.PAU.erg',
  'rouge.A2.C.PAU.Dat',
  'petit.A1.C.PL.Abs',
  'grand.A2.D.PL.obl',
  'blanc.A1.A.SG.Abs',
  'petit.A1.C.PAU.Dat',
  'jaune.A2.D.SG.obl',
  'profond.A2.D.PL.Erg',
  'deux.A1.D.PAU.erg',
  'grand.A2.D.PAU.Erg',
  'petit.A1.A.PAU.Abs',
  'suivant.A2.B.SG.Abs',
  'petit.A1.D.PAU.erg',
  'rouge.A2.B.SG.Abs',
  'grand.A2.D.PL.Erg',
  'nouveau.A1.C.PL.Abs',
  'noir.A2.B.PL.Abs',
  'courageux.A1.B.PAU.obl',
  'gros.A1.B.SG.Abs',
  'sept.A1.B.PL.Erg',
  'courageux.A1.A.SG.Erg',
  u'bless\xe9.A2.B.SG.Abs',
  'jaune.A2.B.SG.Abs',
  'rouge.A2.C.PL.Abs',
  'blanc.A1.A.PAU.obl',
  'terrible.A2.C.PL.Abs',
  'furieux.A2.D.SG.Erg',
  'blanc.A1.B.PAU.Abs',
  'blanc.A1.B.PAU.Erg',
  'profond.A2.B.PL.obl',
  'grand.A2.A.PL.obl',
  'jaune.A2.D.SG.Abs',
  'noir.A2.D.PL.Abs',
  'noir.A2.A.PL.Abs',
  'trois.A2.B.PAU.Abs',
  'vert.A1.B.PAU.erg',
  'furieux.A2.C.SG.Erg',
  'petit.A1.A.SG.Erg',
  'vert.A1.A.SG.obl',
  u'effray\xe9.A1.D.PAU.Erg',
  'profond.A2.C.SG.Erg',
  'trois.A2.B.PAU.Erg',
  'courageux.A1.A.SG.Abs',
  'noir.A2.D.PAU.Abs',
  'petit.A1.B.SG.Erg',
  'quatre.A1.D.PAU.Erg',
  'suivant.A2.C.SG.Erg',
  'courageux.A1.D.PL.obl',
  'vert.A1.B.SG.obl',
  'noir.A2.B.SG.Erg',
  'petit.A1.D.PAU.Erg',
  'blanc.A1.B.SG.Erg',
  'blanc.A1.B.SG.Dat',
  'maigre.A1.B.SG.Abs',
  'blanc.A1.D.SG.Dat',
  u'diff\xe9rent.A2.B.SG.Dat',
  'grand.A2.C.SG.obl',
  'trois.A2.B.PAU.erg',
  'sept.A1.A.PL.Abs',
  'blanc.A1.B.PL.Erg',
  'blanc.A1.A.SG.Erg',
  u'effray\xe9.A1.D.SG.Abs',
  'jaune.A2.D.PAU.Abs',
  u'effray\xe9.A1.C.PAU.obl',
  'dernier.A2.D.PL.erg',
  u'bless\xe9.A2.D.SG.Abs',
  'deux.A1.C.PAU.Abs',
  'vilain.A1.B.SG.Erg',
  'noir.A2.B.SG.obl',
  'deux.A1.D.PAU.obl',
  'noir.A2.A.PAU.Abs',
  'grand.A2.A.SG.Erg',
  'noir.A2.A.SG.erg',
  'noir.A2.B.SG.Abs',
  'blanc.A1.D.PAU.Abs',
  u'm\xe9chant.A1.C.PAU.Abs',
  'grand.A2.B.SG.erg',
  u'm\xe9chant.A1.C.PAU.obl',
  u'bless\xe9.A2.B.SG.obl',
  'blanc.A1.D.SG.obl',
  'petit.A1.D.SG.Dat',
  'autre.A1.D.SG.obl',
  'noir.A2.A.SG.obl',
  'treize.A2.D.PL.erg',
  'blanc.A1.A.PL.Erg',
  'suivant.A2.D.PAU.Abs',
  'vilain.A1.C.PAU.dat',
  u'm\xe9chant.A1.C.PAU.Dat',
  'furieux.A2.C.PL.Abs',
  'vert.A1.D.SG.Abs',
  u'effray\xe9.A1.C.SG.erg',
  'quatre.A1.D.PAU.erg',
  'jaune.A2.B.PAU.Erg',
  'rouge.A2.C.PAU.Erg',
  'petit.A1.D.PL.Erg',
  'maigre.A1.D.PL.Dat',
  'grand.A2.D.SG.obl',
  'trois.A2.C.PAU.obl',
  'petit.A1.C.SG.obl',
  'petit.A1.B.SG.Abs',
  'jaune.A2.D.PL.Abs',
  'terrible.A2.B.SG.Abs',
  'trois.A2.A.PAU.Abs',
  'noir.A2.C.PAU.Erg',
  'blanc.A1.B.SG.Abs',
  'quatre.A1.C.PAU.Erg',
  'dernier.A2.D.SG.obl',
  'petit.A1.A.PAU.obl',
  'noir.A2.B.PL.Erg',
  'blanc.A1.C.PL.erg',
  'noir.A2.C.SG.obl',
  'gros.A1.A.PAU.Erg',
  'deux.A1.A.PAU.Abs',
  'grand.A2.B.PL.Erg',
  u'troisi\xe8me.A2.C.SG.Abs',
  'quatre.A1.A.PAU.Abs',
  'blanc.A1.D.PL.Abs',
  'grand.A2.A.PAU.Abs',
  'jaune.A2.D.PL.erg',
  'treize.A2.C.PL.Dat',
  'petit.A1.B.SG.obl',
  'dernier.A2.C.SG.Erg',
  'vilain.A1.D.PAU.Dat',
  'deux.A1.B.PAU.Dat',
  'suivant.A2.D.SG.obl',
  u'effray\xe9.A1.C.PL.Abs',
  u'effray\xe9.A1.D.PL.Abs',
  'vert.A1.D.PL.Erg',
  'noir.A2.C.SG.Abs',
  'deux.A1.A.PAU.Dat',
  'petit.A1.D.SG.erg',
  'deux.A1.D.PAU.Erg',
  'noir.A2.D.SG.Abs',
  'grand.A2.A.PL.Abs',
  'furieux.A2.A.SG.Abs',
  'blanc.A1.D.SG.Erg',
  'noir.A2.A.SG.Abs',
  'deux.A1.C.PAU.erg',
  u'effray\xe9.A1.B.SG.Erg',
  'grand.A2.D.PAU.Abs',
  'noir.A2.D.SG.Erg',
  'petit.A1.D.SG.Erg',
  'furieux.A2.C.PL.obl',
  'blanc.A1.D.PL.Erg',
  'blanc.A1.A.PAU.Abs',
  'gros.A1.A.PL.Abs',
  'gros.A1.D.SG.Dat',
  'nouveau.A1.B.SG.obl',
  'noir.A2.C.SG.Erg',
  'gros.A1.C.SG.Erg',
  'maigre.A1.D.PL.obl',
  'autre.A1.D.PL.obl',
  u'h\xe9ro\xefque.A1.D.PL.obl',
  'bas.A2.B.SG.obl',
  'deux.A1.C.PAU.Erg',
  'grand.A2.B.SG.Dat',
  'noir.A2.C.PAU.obl',
  'petit.A1.D.SG.Abs',
  'blanc.A1.B.PL.Abs',
  'petit.A1.C.PL.Dat',
  u'effray\xe9.A1.D.SG.Erg',
  'gros.A1.B.PAU.Abs',
  'courageux.A1.B.PL.Abs',
  'gros.A1.D.PL.obl',
  'maigre.A1.A.PAU.Erg',
  'profond.A2.D.SG.obl',
  'grand.A2.C.PL.Dat',
  'deux.A1.B.PAU.Abs',
  'gros.A1.A.PL.Erg',
  'rouge.A2.B.SG.Erg',
  'grand.A2.C.PAU.obl',
  'trois.A2.C.PAU.Erg',
  'sept.A1.B.PL.Dat',
  u'diff\xe9rent.A2.A.PAU.Abs',
  'courageux.A1.B.PL.erg',
  'profond.A2.D.SG.Erg',
  'gros.A1.B.SG.obl',
  u'h\xe9ro\xefque.A1.A.PL.Abs',
  'profond.A2.D.SG.Abs',
  u'm\xe9chant.A1.C.SG.obl',
  'noir.A2.B.SG.erg',
  'petit.A1.C.SG.Abs',
  'grand.A2.B.SG.obl',
  'blanc.A1.A.SG.erg',
  'terrible.A2.B.PL.Abs',
  'blanc.A1.A.PL.obl',
  'petit.A1.D.PAU.Abs',
  'cinq.A1.B.PAU.Abs',
  'blanc.A1.B.SG.obl',
  'trois.A2.A.PAU.Erg',
  'blanc.A1.C.SG.Erg',
  'noir.A2.B.PAU.Erg',
  'petit.A1.D.PAU.Dat',
  'deux.A1.B.PAU.Erg',
  'gros.A1.B.PAU.obl',
  'noir.A2.A.SG.Erg',
  'gros.A1.C.PAU.Abs',
  'nombreux.A2.A.PL.Abs',
  'terrible.A2.B.PAU.obl',
  'petit.A1.D.SG.obl',
  'rouge.A2.A.SG.Dat',
  'rouge.A2.D.PL.Abs',
  u'bless\xe9.A2.D.SG.obl',
  'trois.A2.D.PAU.Erg',
  'noir.A2.B.PAU.Abs',
  'rouge.A2.B.PL.Abs',
  u'm\xe9chant.A1.C.PL.Dat',
  'quatre.A1.D.PAU.Abs',
  'noir.A2.D.SG.obl',
  'trois.A2.C.PAU.Abs',
  'grand.A2.A.PAU.Erg',
  u'm\xe9chant.A1.B.SG.Abs',
  'grand.A2.A.SG.obl',
  u'bless\xe9.A2.D.SG.Erg',
  'petit.A1.A.PL.Abs',
  'autre.A1.A.PL.Abs',
  'noir.A2.B.PL.obl',
  'petit.A1.D.PL.Abs',
  'rouge.A2.A.SG.Abs',
  'petit.A1.A.PAU.erg',
  'maigre.A1.D.PL.Erg',
  'six.A1.A.PL.Abs',
  'grand.A2.B.PL.obl',
  'grand.A2.C.SG.Abs',
  'furieux.A2.B.PL.obl',
  'six.A1.A.PL.Erg',
  'deux.A1.D.PAU.Abs',
  u'm\xe9chant.A1.C.SG.Erg',
  'noir.A2.D.PL.obl',
  'gros.A1.A.PAU.Abs',
  'dernier.A2.C.SG.Abs',
  'treize.A2.D.PL.Abs',
  'grand.A2.D.SG.Abs',
  'rouge.A2.D.SG.obl',
  'petit.A1.B.PL.Abs',
  'grand.A2.B.SG.Abs',
  'deux.A1.C.PAU.obl',
  'vert.A1.B.PL.Abs',
  'nouveau.A1.C.SG.Erg',
  'profond.A2.B.SG.Erg',
  'petit.A1.C.SG.Erg',
  'petit.A1.C.PL.erg',
  'gros.A1.A.SG.Erg',
  'vert.A1.C.SG.Erg',
  'grand.A2.B.SG.Erg',
  'petit.A1.A.SG.Abs',
  'rouge.A2.C.SG.Erg',
  u'diff\xe9rent.A2.C.PL.obl',
  u'bless\xe9.A2.A.SG.obl'],
 'DET': ['DEF.A.PL.erg',
  'IND.A.SG.Abs',
  'IND.D.PL.Erg',
  'DEM.A.PAU.Erg',
  'IND.D.PAU.Abs',
  'IND.B.SG.Erg',
  'IND.D.PAU.Erg',
  'IND.B.PL.obl',
  'DEF.C.PL.Abs',
  'IND.A.SG.Erg',
  'DEF.B.PAU.erg',
  'DEF.C.PAU.erg',
  'DEF.D.PL.obl',
  'IND.A.SG.Dat',
  'DEF.B.SG.Dat',
  'DEF.A.SG.Erg',
  'DEM.B.PL.Dat',
  'DEF.C.SG.obl',
  'DEF.C.PL.Dat',
  'DEF.B.PL.Dat',
  'DEF.B.SG.Abs',
  'DEF.B.PAU.Erg',
  'DEF.C.PAU.Abs',
  'DEF.C.PAU.dat',
  'DEM.D.SG.erg',
  'DEM.D.PAU.Erg',
  'DEF.B.SG.dat',
  'DEM.D.PL.Erg',
  'IND.C.PL.obl',
  'IND.B.PAU.obl',
  'DEM.D.PL.obl',
  'DEF.C.PL.dat',
  'IND.B.SG.obl',
  'DEM.A.PL.Abs',
  'DEM.D.PL.Abs',
  'DEF.D.SG.dat',
  'IND.A.PL.obl',
  'DEF.B.SG.erg',
  'IND.D.PL.dat',
  'IND.C.PL.erg',
  'DEF.D.PAU.Erg',
  'IND.C.PAU.Dat',
  'IND.D.PL.Abs',
  'DEM.A.PL.obl',
  'IND.B.PAU.erg',
  'DEF.C.SG.Erg',
  'DEM.C.SG.Erg',
  'DEF.C.PL.obl',
  'DEF.A.SG.Abs',
  'IND.A.PL.Erg',
  'DEF.B.PL.erg',
  'DEM.A.SG.obl',
  'IND.B.PL.Abs',
  'DEM.B.PAU.Erg',
  'IND.A.PAU.Abs',
  'IND.D.SG.dat',
  'DEF.B.SG.obl',
  'DEF.C.SG.erg',
  'IND.C.SG.obl',
  'DEM.C.PL.obl',
  'DEM.A.PL.Dat',
  'DEF.C.PAU.obl',
  'DEF.D.SG.Abs',
  'DEF.C.SG.Dat',
  'IND.D.SG.Dat',
  'DEF.D.SG.Erg',
  'DEF.D.PL.Erg',
  'DEF.D.PL.Abs',
  'DEF.B.PL.Erg',
  'IND.D.PAU.obl',
  'DEM.D.PAU.Dat',
  'DEF.B.PAU.Dat',
  'IND.D.SG.Abs',
  'DEM.B.SG.Dat',
  'DEF.C.PL.Erg',
  'IND.D.SG.Erg',
  'IND.D.PAU.Dat',
  'IND.D.PL.erg',
  'IND.B.SG.erg',
  'DEM.B.SG.Abs',
  'IND.D.PAU.erg',
  'DEM.C.PAU.Dat',
  'IND.C.SG.Dat',
  'DEM.D.SG.Abs',
  'DEF.C.SG.Abs',
  'DEM.C.SG.Abs',
  'DEF.A.SG.erg',
  'DEF.A.SG.dat',
  'DEM.C.PAU.Abs',
  'DEM.B.PL.Abs',
  'DEF.A.PAU.Abs',
  'IND.A.PL.Abs',
  'DEM.A.SG.Abs',
  'DEM.C.PAU.Erg',
  'IND.C.PAU.Erg',
  'DEF.A.PL.Erg',
  'DEF.A.PAU.obl',
  'DEM.D.PL.Dat',
  'DEF.D.PAU.obl',
  'DEF.C.SG.dat',
  'IND.B.PL.Dat',
  'DEF.A.SG.Dat',
  'DEF.D.PAU.erg',
  'DEF.A.PL.dat',
  'DEF.A.PAU.Dat',
  'IND.C.PAU.erg',
  'DEM.D.SG.Erg',
  'DEF.D.PL.erg',
  'IND.B.PL.Erg',
  'DEF.A.PL.Dat',
  'DEF.D.SG.obl',
  'IND.C.PAU.Abs',
  'IND.D.PL.obl',
  'DEF.D.PL.Dat',
  'DEF.C.PAU.Dat',
  'DEF.D.PAU.Abs',
  'DEF.B.PL.obl',
  'DEF.B.PL.Abs',
  'DEM.B.SG.Erg',
  'IND.A.SG.obl',
  'IND.C.PL.Abs',
  'IND.B.SG.Abs',
  'DEF.D.SG.Dat',
  'IND.C.SG.Abs',
  'DEF.B.SG.Erg',
  'IND.D.PL.Dat',
  'DEF.A.PL.obl',
  'IND.D.SG.obl',
  'DEF.D.PAU.Dat',
  'IND.C.SG.dat',
  'DEF.D.SG.erg',
  'IND.C.PL.Dat',
  'IND.A.PAU.Erg',
  'IND.B.PAU.Erg',
  'DEM.A.PAU.Abs',
  'DEF.C.PAU.Erg',
  'DEM.C.PL.Abs',
  'DEM.D.PAU.obl',
  'DEF.A.PAU.erg',
  'DEF.B.PAU.obl',
  'IND.B.PAU.Abs',
  'IND.D.SG.erg',
  'DEF.B.PAU.Abs',
  'DEM.B.SG.obl',
  'IND.C.SG.erg',
  'DEM.C.SG.obl',
  'DEM.C.PAU.obl',
  'DEM.B.PL.Erg',
  'DEF.A.PAU.Erg',
  'DEF.A.SG.obl',
  'DEF.A.PL.Abs',
  'IND.A.SG.erg',
  'IND.C.SG.Erg',
  'DEM.D.PAU.Abs',
  'DEM.D.SG.obl',
  'DEF.C.PL.erg',
  'DEM.B.PAU.Abs'],
 'NOM': ['Mahira.A.N4.Sg.Erg',
  'main.D.N3.Pl.Abs',
  'viande.B.N4.Pau.Abs',
  'loup.B.N2.Pau.Abs',
  'maison.D.N1.Pau.Obl',
  'enfant.C.N2.Pl.Erg',
  u'lumi\xe8re.B.N4.Pl.Abs',
  'Clemencia.A.N1.Sg.Abs',
  'mort.B.N1.Sg.Dat',
  u'for\xeat.D.N3.Pl.Abs',
  'place.A.N1.Sg.Abs',
  u'gar\xe7on.D.N3.Pl.Erg',
  u'obscurit\xe9.C.N1.Sg.Obl',
  u'for\xeat.D.N3.Sg.Obl',
  u'caf\xe9.A.N4.Pau.Abs',
  'femme.B.N3.Pl.Obl',
  u'h\xe9ros.C.N3.Pau.Erg',
  'crapaud.D.N1.Pl.Abs',
  'histoire.D.N2.Pl.Obl',
  'chat.B.N3.Pl.Erg',
  'sorcier.C.N2.Pau.Erg',
  'caillou.D.N2.Pau.Dat',
  'nuit.D.N3.Pau.Abs',
  u'infirmi\xe8re.B.N2.Pl.Erg',
  'gargouille.D.N2.Pau.Erg',
  'Nabil.D.N2.Sg.Obl',
  'autruche.C.N1.Pl.Abs',
  'Freja.B.N1.Sg.Erg',
  'demande.C.N4.Sg.Obl',
  'villageois.D.N4.Pl.Dat',
  'raison.A.N1.Pl.Abs',
  u'd\xe9mon.C.N1.Pl.Abs',
  'serpent.A.N2.Pl.Abs',
  'souris.A.N4.Pau.Abs',
  u'b\xfbcher.D.N4.Sg.Abs',
  'Nicole.B.N3.Sg.Obl',
  'lune.A.N1.Sg.Erg',
  'villageoise.B.N4.Pl.Abs',
  'combattant.B.N1.Pau.Abs',
  u'infirmi\xe8re.B.N2.Sg.Abs',
  'combattant.B.N1.Sg.Obl',
  'chasseur.A.N2.Pl.Abs',
  'dragon.B.N3.Sg.Obl',
  'sorcier.C.N2.Sg.Abs',
  'blessure.D.N2.Sg.Erg',
  'nuit.D.N3.Sg.Erg',
  'poisson.D.N4.Sg.Obl',
  u'infirmi\xe8re.B.N2.Pau.Erg',
  'Violette.D.N4.Sg.Obl',
  'souris.A.N4.Pl.Obl',
  'arbre.C.N2.Pl.Abs',
  'enfant.C.N2.Sg.Obl',
  'chatte.C.N3.Pau.Dat',
  'homme.A.N2.Pl.Abs',
  u'd\xe9g\xe2t.C.N3.Pl.Abs',
  'chat.B.N3.Sg.Abs',
  'caillou.D.N2.Pl.Obl',
  u'col\xe8re.C.N4.Sg.Erg',
  'crapaud.D.N1.Pl.Obl',
  'jardin.C.N4.Pl.Obl',
  'enfant.C.N2.Sg.Abs',
  'table.B.N2.Sg.Abs',
  'cri.C.N4.Pl.Abs',
  u'l\xe9gume.D.N1.Pl.Abs',
  'visage.B.N4.Pl.Abs',
  'louve.B.N1.Sg.Erg',
  'Clemencia.A.N1.Sg.Obl',
  u'd\xe9mon.C.N1.Pl.Obl',
  'Kaleb.A.N4.Sg.Erg',
  'livre.C.N3.Sg.Abs',
  'serpent.A.N2.Sg.Erg',
  'chatte.C.N3.Sg.Dat',
  'lance.C.N4.Pau.Abs',
  'sort.C.N3.Sg.Abs',
  'enfant.C.N2.Pau.Obl',
  'combat.B.N2.Pl.Abs',
  u'h\xe9ros.C.N3.Pl.Abs',
  'chemin.A.N3.Sg.Abs',
  'milieu.B.N1.Pl.Obl',
  'lance.C.N4.Sg.Obl',
  'vengeance.D.N2.Sg.Obl',
  'gargouille.D.N2.Pl.Erg',
  'mort.B.N1.Sg.Obl',
  'histoire.D.N2.Sg.Obl',
  'coussin.D.N1.Pl.Obl',
  'table.B.N2.Sg.Obl',
  'lit.D.N1.Sg.Abs',
  'chef.A.N1.Sg.Abs',
  'lueur.B.N2.Sg.Abs',
  'Nabil.D.N2.Sg.Abs',
  'souffrance.B.N2.Sg.Obl',
  'louve.B.N1.Sg.Abs',
  'douleur.C.N1.Sg.Obl',
  'louve.B.N1.Pl.Obl',
  'coussin.D.N1.Sg.Obl',
  'tornade.D.N4.Sg.Erg',
  'Katisha.A.N3.Sg.Obl',
  u'm\xe8re.A.N2.Sg.Erg',
  'gorge.A.N4.Sg.Abs',
  u'd\xe9mon.C.N1.Sg.Obl',
  'souffrance.B.N2.Sg.Erg',
  'villageoise.B.N4.Sg.Erg',
  'coussin.D.N1.Pl.Erg',
  'combattant.B.N1.Pl.Abs',
  'manoir.B.N2.Sg.Erg',
  u'd\xe9mon.C.N1.Pl.Erg',
  'homme.A.N2.Sg.Erg',
  'soeur.B.N4.Pl.Abs',
  'autruche.C.N1.Sg.Dat',
  'corps.A.N3.Pau.Abs',
  'village.D.N1.Sg.Dat',
  'Freja.B.N1.Sg.Abs',
  'combattant.B.N1.Pl.Erg',
  'nouvelle-N.C.N4.Sg.Erg',
  'histoire.D.N2.Sg.Abs',
  u'lumi\xe8re.B.N4.Sg.Abs',
  'village.D.N1.Sg.Abs',
  'coyote.D.N4.Sg.Dat',
  'sort.C.N3.Pl.Abs',
  'chatte.C.N3.Pau.Obl',
  'harmonie.C.N2.Sg.Obl',
  'nuit.D.N3.Sg.Obl',
  'village.D.N1.Pau.Abs',
  'balai.D.N3.Sg.Erg',
  u'sortil\xe8ge.A.N1.Sg.Erg',
  'autruche.C.N1.Pau.Erg',
  'Mahira.A.N4.Sg.Dat',
  'fruit.D.N2.Pl.Abs',
  'villageoise.B.N4.Pl.Obl',
  'loup.B.N2.Pl.Erg',
  'lune.A.N1.Pl.Obl',
  'maison.D.N1.Sg.Obl',
  'couteau.C.N1.Pau.Dat',
  'village.D.N1.Pl.Obl',
  u'gar\xe7on.D.N3.Pau.Erg',
  'louve.B.N1.Pl.Abs',
  'mort.B.N1.Sg.Abs',
  'loup.B.N2.Sg.Dat',
  'sorcier.C.N2.Sg.Erg',
  'matin.B.N3.Sg.Dat',
  'Kaleb.A.N4.Pl.Erg',
  'combattant.B.N1.Sg.Erg',
  'bras.B.N1.Pl.Obl',
  u'infirmi\xe8re.B.N2.Pl.Abs',
  'histoire.D.N2.Pau.Abs',
  'dragon.B.N3.Sg.Abs',
  'table.B.N2.Pau.Erg',
  'manoir.B.N2.Sg.Dat',
  'grimoire.B.N4.Sg.Abs',
  'souris.A.N4.Pau.Erg',
  'balai.D.N3.Pl.Obl',
  'lune.A.N1.Sg.Abs',
  'dragon.B.N3.Sg.Dat',
  'tornade.D.N4.Pau.Erg',
  'autruche.C.N1.Sg.Obl',
  u'col\xe8re.C.N4.Pau.Erg',
  'fille.D.N3.Sg.Obl',
  'couteau.C.N1.Pau.Erg',
  'Agathos.C.N3.Pl.Obl',
  u'proximit\xe9.D.N1.Sg.Dat',
  u'infirmi\xe8re.B.N2.Sg.Erg',
  'milieu.B.N1.Sg.Dat',
  'nuit.D.N3.Pau.Erg',
  'mort.B.N1.Pl.Abs',
  'enfant.C.N2.Pl.Abs',
  'fruit.D.N2.Pau.Abs',
  'crapaud.D.N1.Pl.Erg',
  u'gar\xe7on.D.N3.Sg.Erg',
  'souffrance.B.N2.Pl.Erg',
  'villageoise.B.N4.Pl.Erg',
  u'cr\xe9ature.C.N1.Pl.Abs',
  'chatte.C.N3.Pau.Abs',
  'coussin.D.N1.Sg.Erg',
  'corps.A.N3.Sg.Dat',
  'cri.C.N4.Pl.Erg',
  'fille.D.N3.Sg.Erg',
  'Kaleb.A.N4.Sg.Abs',
  'sort.C.N3.Pau.Erg',
  'Nicole.B.N3.Sg.Erg',
  u'd\xe9g\xe2t.C.N3.Pl.Obl',
  'loup.B.N2.Pau.Dat',
  'sorcier.C.N2.Pl.Obl',
  'ombre.C.N2.Pau.Dat',
  'cri.C.N4.Sg.Abs',
  'coyote.D.N4.Pl.Erg',
  'Freja.B.N1.Sg.Dat',
  'marais.A.N1.Pl.Obl',
  u'gar\xe7on.D.N3.Sg.Abs',
  'arbre.C.N2.Sg.Obl',
  u'infirmi\xe8re.B.N2.Pau.Abs',
  'autruche.C.N1.Pau.Abs',
  'robe.A.N4.Sg.Obl',
  'lueur.B.N2.Pau.Erg',
  'Mahira.A.N4.Sg.Obl',
  'chasseur.A.N2.Pau.Dat',
  'livre.C.N3.Sg.Erg',
  'Hoderi.B.N1.Sg.Abs',
  u'infirmi\xe8re.B.N2.Pl.Dat',
  'gargouille.D.N2.Pau.Dat',
  'jour.C.N2.Sg.Obl',
  'feu.A.N3.Sg.Obl',
  'marais.A.N1.Sg.Abs',
  'villageois.D.N4.Sg.Dat',
  u'sortil\xe8ge.A.N1.Pl.Obl',
  'blessure.D.N2.Pl.Erg',
  'serpent.A.N2.Sg.Dat',
  'combat.B.N2.Pl.Erg',
  'louve.B.N1.Sg.Dat',
  'soeur.B.N4.Sg.Abs',
  'voleuse.B.N3.Pau.Abs',
  'enfant.C.N2.Pau.Erg',
  'parent.D.N3.Pl.Obl',
  'village.D.N1.Pl.Dat',
  'chat.B.N3.Sg.Obl',
  'tornade.D.N4.Sg.Abs',
  'arbre.C.N2.Pau.Erg',
  'mort.B.N1.Sg.Erg',
  'croc.B.N4.Pau.Erg',
  'autruche.C.N1.Pl.Dat',
  'chef.A.N1.Sg.Erg',
  'louve.B.N1.Pl.Dat',
  'raison.A.N1.Sg.Obl',
  'ombre.C.N2.Sg.Obl',
  'lance.C.N4.Pl.Erg',
  'souris.A.N4.Pl.Abs',
  'grimoire.B.N4.Sg.Obl',
  'Elphaba.B.N3.Sg.Erg',
  'souffrance.B.N2.Sg.Abs',
  'villageoise.B.N4.Sg.Abs',
  'fille.D.N3.Pl.Erg',
  'balai.D.N3.Sg.Abs',
  'marais.A.N1.Sg.Obl',
  u'l\xe9gende.B.N1.Sg.Abs',
  'main.D.N3.Sg.Obl',
  'manoir.B.N2.Sg.Abs',
  'villageoise.B.N4.Pau.Dat',
  u'b\xfbcher.D.N4.Sg.Obl',
  'robe.A.N4.Sg.Erg',
  'lance.C.N4.Pl.Abs',
  'feu.A.N3.Sg.Abs',
  'fille.D.N3.Sg.Dat',
  'lueur.B.N2.Sg.Obl',
  'couteau.C.N1.Pl.Erg',
  'main.D.N3.Pau.Obl',
  'loup.B.N2.Sg.Erg',
  'lune.A.N1.Sg.Obl',
  'oeil.C.N1.Pl.Dat',
  'blessure.D.N2.Sg.Dat',
  'loup.B.N2.Pau.Erg',
  'sorcier.C.N2.Pau.Dat',
  'ombre.C.N2.Pl.Abs',
  'lit.D.N1.Sg.Obl',
  'fille.D.N3.Pl.Obl',
  'lit.D.N1.Pl.Abs',
  'lance.C.N4.Pau.Erg',
  'parent.D.N3.Pl.Abs',
  'vote.D.N3.Sg.Erg',
  'plaine.A.N3.Sg.Obl',
  'fille.D.N3.Pau.Obl',
  'homme.A.N2.Sg.Obl',
  'chambre.A.N3.Sg.Obl',
  'corps.A.N3.Sg.Abs',
  u'd\xe9mon.C.N1.Sg.Dat',
  'combattant.B.N1.Pau.Obl',
  'chambre.A.N3.Pau.Obl',
  'Nicole.B.N3.Sg.Abs',
  'coup.D.N4.Sg.Abs',
  'arbre.C.N2.Pl.Obl',
  'table.B.N2.Pl.Obl',
  'Katisha.A.N3.Sg.Dat',
  'Kaleb.A.N4.Pl.Abs',
  'robe.A.N4.Pl.Abs',
  'dragon.B.N3.Sg.Erg',
  'dragon.B.N3.Pau.Erg',
  'sorcier.C.N2.Pl.Abs',
  'nuit.D.N3.Sg.Abs',
  'mort.B.N1.Pl.Dat',
  'coyote.D.N4.Pl.Abs',
  u'm\xe8re.A.N2.Pau.Erg',
  'ombre.C.N2.Sg.Erg',
  'autruche.C.N1.Pl.Obl',
  'chat.B.N3.Pl.Dat',
  u'col\xe8re.C.N4.Pl.Erg',
  'Mahira.A.N4.Sg.Abs',
  'sorcier.C.N2.Pl.Dat',
  'Nabil.D.N2.Sg.Erg',
  'coyote.D.N4.Pl.Dat',
  'donjon.A.N2.Sg.Abs',
  'main.D.N3.Pau.Abs',
  'louve.B.N1.Sg.Obl',
  'poisson.D.N4.Sg.Erg',
  'villageois.D.N4.Pl.Erg',
  'cri.C.N4.Sg.Obl',
  'corps.A.N3.Sg.Obl',
  'femme.B.N3.Pl.Erg',
  'soeur.B.N4.Sg.Obl',
  u'\u0153uf.D.N2.Sg.Abs',
  'fille.D.N3.Sg.Abs',
  'souris.A.N4.Sg.Erg',
  'chatte.C.N3.Sg.Erg',
  u'for\xeat.D.N3.Sg.Erg',
  'coussin.D.N1.Sg.Abs',
  u'l\xe9gende.B.N1.Pau.Abs',
  'main.D.N3.Pl.Obl',
  'balai.D.N3.Pau.Erg',
  'lune.A.N1.Pau.Abs',
  'Elphaba.B.N3.Sg.Abs',
  u'obscurit\xe9.C.N1.Sg.Erg',
  u'd\xe9mon.C.N1.Pau.Obl',
  'poisson.D.N4.Sg.Abs',
  'arbre.C.N2.Sg.Erg',
  'disparition.A.N3.Pl.Abs',
  'gorge.A.N4.Sg.Erg',
  'parent.D.N3.Sg.Dat',
  u'th\xe9.A.N2.Sg.Erg',
  'couteau.C.N1.Sg.Obl',
  u'gar\xe7on.D.N3.Pl.Obl',
  'villageois.D.N4.Sg.Abs',
  'coyote.D.N4.Pl.Obl',
  u'ma\xeetre.B.N4.Sg.Erg',
  'chat.B.N3.Pau.Erg',
  'sorcier.C.N2.Pau.Obl',
  u'cr\xe9ature.C.N1.Sg.Erg',
  'grimoire.B.N4.Sg.Erg',
  'place.A.N1.Sg.Obl',
  'villageois.D.N4.Sg.Obl',
  'Hoderi.B.N1.Sg.Erg',
  'plaine.A.N3.Pl.Obl',
  'corps.A.N3.Pl.Obl',
  'hurlement.B.N2.Pl.Abs',
  'peau.D.N1.Sg.Abs',
  'coyote.D.N4.Sg.Abs',
  'dragon.B.N3.Pl.Abs',
  'Kaleb.A.N4.Sg.Obl',
  'chasseur.A.N2.Sg.Abs',
  'main.D.N3.Sg.Abs',
  'construction.C.N4.Sg.Dat',
  'enfant.C.N2.Pau.Dat',
  'main.D.N3.Pau.Erg',
  'coussin.D.N1.Pau.Abs',
  'coussin.D.N1.Pl.Abs',
  'enfant.C.N2.Pau.Abs',
  'chasseur.A.N2.Sg.Obl',
  'cri.C.N4.Pau.Abs',
  'Agathos.C.N3.Sg.Obl',
  'homme.A.N2.Pl.Obl',
  'arbre.C.N2.Sg.Abs',
  'sort.C.N3.Pau.Abs',
  'coup.D.N4.Pau.Abs',
  'Violette.D.N4.Sg.Erg',
  'souris.A.N4.Pl.Erg',
  'couteau.C.N1.Sg.Abs',
  'blessure.D.N2.Sg.Abs',
  u'd\xe9mon.C.N1.Sg.Abs',
  'dernier-N.B.N3.Pl.Abs',
  'chambre.A.N3.Pl.Erg',
  'fille.D.N3.Pl.Abs',
  'enfant.C.N2.Pl.Dat',
  'village.D.N1.Sg.Obl',
  'couteau.C.N1.Sg.Erg',
  'villageoise.B.N4.Pl.Dat',
  'vote.D.N3.Sg.Abs',
  'Agathos.C.N3.Sg.Erg',
  'oeil.C.N1.Pau.Erg',
  'balai.D.N3.Pl.Erg',
  'livre.C.N3.Pau.Erg',
  'Freja.B.N1.Sg.Obl',
  'loup.B.N2.Sg.Abs',
  'lueur.B.N2.Sg.Erg',
  'chef.A.N1.Pl.Dat',
  'combat.B.N2.Sg.Obl',
  'coup.D.N4.Pl.Erg',
  'serpent.A.N2.Pau.Erg',
  'chambre.A.N3.Pl.Obl',
  'fille.D.N3.Pau.Erg',
  u'h\xe9ros.C.N3.Pau.Abs',
  u'h\xe9ros.C.N3.Pl.Obl',
  'maison.D.N1.Pl.Obl',
  'lever-N.D.N4.Sg.Dat',
  'parent.D.N3.Pl.Erg',
  'nuit.D.N3.Pl.Abs',
  'croc.B.N4.Pl.Erg',
  'excuse.A.N2.Pl.Abs',
  'soeur.B.N4.Sg.Erg',
  'arbre.C.N2.Pau.Obl',
  'harmonie.C.N2.Sg.Erg',
  'autruche.C.N1.Sg.Erg',
  'loup.B.N2.Pl.Obl',
  'souffrance.B.N2.Pau.Obl',
  'main.D.N3.Pl.Erg',
  u'sortil\xe8ge.A.N1.Sg.Abs',
  'villageois.D.N4.Pl.Obl',
  'tornade.D.N4.Pau.Obl',
  'donjon.A.N2.Sg.Obl',
  'balai.D.N3.Pau.Obl',
  'table.B.N2.Sg.Erg',
  u'l\xe9gume.D.N1.Pl.Erg',
  'esprit.A.N4.Pl.Erg',
  'chat.B.N3.Pau.Abs',
  'chasseur.A.N2.Pau.Erg',
  u'sortil\xe8ge.A.N1.Sg.Obl',
  'villageois.D.N4.Sg.Erg',
  'caillou.D.N2.Pl.Abs',
  'Clemencia.A.N1.Sg.Erg',
  'chasseur.A.N2.Pl.Obl',
  'villageois.D.N4.Pl.Abs',
  'gargouille.D.N2.Pau.Abs',
  'poisson.D.N4.Pl.Abs',
  'cri.C.N4.Sg.Erg',
  u'l\xe9gende.B.N1.Sg.Erg',
  'croc.B.N4.Sg.Abs',
  'manoir.B.N2.Sg.Obl',
  'enfant.C.N2.Pl.Obl',
  'poisson.D.N4.Pau.Abs',
  u'gar\xe7on.D.N3.Pl.Abs',
  u'caf\xe9.A.N4.Sg.Abs',
  u'\u0153uf.D.N2.Pau.Erg',

In [43]:
def sortLevel(level):
    sortedLevel=level
    name="???"
    if "Erg" in level:
        sortedLevel=[f for f in "Erg Abs Dat Obl".split(" ") if f in level]
        name="Cas"
    elif "Acc" in level or "Nom" in level:
        sortedLevel=[f for f in "Nom Acc Dat Obl".split(" ") if f in level]
        name="Cas"
    elif "3Sg" in level:
        sortedLevel=[f for f in u"3Sg 3Du 3Pau 3Pl".split(" ") if f in level]
        name="Pers"
    elif "Sg" in level or "Pl" in level:
        sortedLevel=[f for f in u"Sg Du Pau Pl".split(" ") if f in level]
        name="Nombre"
    elif "Hum" in level or "Ani" in level:
        sortedLevel=[f for f in "Hum Ani Anim Ina Inan".split(" ") if f in level]
        name="Genre"
    elif "H" in level:
        sortedLevel=[f for f in "H A I".split(" ") if f in level]
        name="Genre"
    elif "M" in level or "F" in level or "N" in level:
        sortedLevel=[f for f in "M F N".split(" ") if f in level]
        name="Genre"
    elif "A" in level and "B" in level:
        sortedLevel=[f for f in "A B C D".split(" ") if f in level]
        name="Genre"
    elif "Def" in level:
        sortedLevel=[f for f in "Def Indef Ind Dem".split(" ") if f in level]
        name="DET"

    elif "Prs" in level:
        print level
        sortedLevel=[f for f in "Prs PRS Pst PST Fut FUT".split(" ") if f in level]
        name="Temps"
    elif "V1" in level or "N1" in level or "A1" in level:
        name="CF"
    elif "Vt" in level:
        name="Trans"
    return sortedLevel, name
        
def filledTable(fc,lexeme,rows,cols):
    filled=[f.split(".") for f in fc]
    filled=[f if "hyper" not in f else [c for c in f if c!="hyper"] for f in filled]
    print [f for f in filled if f and len(f)>5]
    for iF,f in enumerate(filled):
        filled[iF]=[c.capitalize() if c[0] not in "123" else c for c in f]
    dfFilled=pd.DataFrame(filled)
    dfFilled.columns=["C"+str(n) for n in dfFilled.columns.tolist()]
    if lexeme!=0:
        dfFilled["lexeme"]=dfFilled["C0"]
        lLexeme="lexeme"
    else:
        lLexeme="C"+str(lexeme)
    lRows=["C"+str(n) for n in rows]
    lCols=["C"+str(n) for n in cols]
#     display(dfFilled)

    
    result=pd.pivot_table(dfFilled,index=lRows,columns=lCols,values=lLexeme,aggfunc="count",dropna = False,fill_value=0)
#     display(result)
    if isinstance(result.index, pd.MultiIndex):
        levels=result.index.levels
        for iL,level in enumerate(levels):
            print iL, level
            sort,name=sortLevel(level)
            result=result.reindex(sort,level=iL)
            result.index=result.index.set_names(name, level=iL)
    else:
        sort,name=sortLevel(result.index)
        result=result.reindex(sort)
        result.index=result.index.set_names(name)

    if isinstance(result.columns, pd.MultiIndex):
        levels=result.columns.levels
        for iL,level in enumerate(levels):
            sort,name=sortLevel(level)
            result=result.reindex(sort,level=iL,axis=1)
            result.columns=result.columns.set_names(name, level=iL)
#             result=result.reindex(sortLevel(level),level=-iL,axis=1)
    else:
        sort,name=sortLevel(result.columns)
        result=result.reindex(sort,axis=1)
        result.columns=result.columns.set_names(name)

#         result=result.reindex(sortLevel(result.columns),axis=1)


    
    return result

In [44]:
tableauxRemplissage={}

# Paramétrage des remplissages

In [45]:
fc=filledCells["NOM"]
print fc[0]
tableauxRemplissage["NOM"]=filledTable(fc,0,[1],[2])
# tableauxRemplissage["NOM"]=filledTable(fc,0,[1],[3])
tableauxRemplissage["NOM"]=filledTable(fc,0,[2],[3])
# tableauxRemplissage["NOM"]=filledTable(fc,0,[1],[2,3])
# tableauxRemplissage["NOM"]=filledTable(fc,0,[1],[3,4])
# tableauxRemplissage["NOM"]=filledTable(fc,0,[2,1],[3,4])
tableauxRemplissage["NOM"]=filledTable(fc,0,[2],[3,4])

Mahira.A.N4.Sg.Erg
[]
[]
[]

In [46]:
fc=filledCells["VER"]
print fc[0]
tableauxRemplissage["VER"]=filledTable(fc,0,[1],[2,3])
tableauxRemplissage["VER"]=filledTable(fc,0,[1,2],[3,4])
tableauxRemplissage["VER"]=filledTable(fc,0,[2,3],[4,5])

transpercer.VT.V2.Prs.3Pau.B
[['transpercer', 'VT', 'V2', 'Prs', '3Pau', 'B'], ['partir', 'VI', 'V2', 'Prs', '3Sg', 'B'], [u'prot\xe9ger', u'VT', u'V1', u'Prs', u'3Pl', u'D'], [u'\xeatre', u'VT', u'V2', u'Prs', u'3Pl', u'C'], [u'\xeatre', u'VT', u'V2', u'Prs', u'3Pl', u'B'], [u'prot\xe9ger', u'VT', u'V1', u'Prs', u'3Sg', u'B'], [u'br\xfbler-Med', u'VI', u'V2', u'Prs', u'3Sg', u'D'], [u'prot\xe9ger', u'VT', u'V1', u'Prs', u'3Sg', u'D'], ['aller', 'VI', 'V2', 'Pst', '3Pl', 'B'], ['chasser-Act', 'VT', 'V1', 'Prs', '3Pl', 'A'], ['chercher', 'VT', 'V1', 'Prs', '3Pl', 'A'], ['dormir', 'VI', 'V2', 'Prs', '3Pl', 'A'], ['mourir', 'VI', 'V1', 'Prs', '3Sg', 'B'], ['dormir', 'VI', 'V2', 'Prs', '3Pl', 'D'], ['offrir', 'VT', 'V2', 'Prs', '3Sg', 'D'], ['offrir', 'VT', 'V2', 'Prs', '3Sg', 'B'], [u'br\xfbler', u'VT', u'V1', u'Pst', u'3Sg', u'B'], ['donner', 'VT', 'V1', 'Prs', '3Pl', 'B'], ['chercher', 'VT', 'V1', 'Pst', '3Sg', 'A'], ['donner', 'VT', 'V1', 'Prs', '3Pl', 'D'], ['chercher', 'VT', 'V1', 'Pst', '3Pl', 'C'], ['courir', 'VI', 'V2', 'Pst', '3Pau', 'C'], ['vivre', 'VI', 'V1', 'Prs', '3Sg', 'D'], ['offrir', 'VT', 'V2', 'Pst', '3Pau', 'C'], ['donner', 'VT', 'V1', 'Prs', '3Sg', 'D'], ['redevenir', 'VT', 'V1', 'Prs', '3Sg', 'B'], ['donner', 'VT', 'V1', 'Prs', '3Sg', 'C'], ['donner', 'VT', 'V1', 'Prs', '3Sg', 'B'], ['voir', 'VT', 'V2', 'Pst', '3Pl', 'B'], ['montrer', 'VT', 'V1', 'Prs', '3Pl', 'D'], [u'poss\xe9der', u'VT', u'V2', u'Prs', u'3Sg', u'B'], ['lancer', 'VT', 'V2', 'Pst', '3Sg', 'A'], ['voir', 'VT', 'V2', 'Pst', '3Sg', 'C'], ['lancer', 'VT', 'V2', 'Pst', '3Sg', 'C'], ['voir', 'VT', 'V2', 'Pst', '3Sg', 'A'], ['lancer', 'VT', 'V2', 'Pst', '3Sg', 'D'], [u'dispara\xeetre', u'VI', u'V1', u'Prs', u'3Pl', u'C'], ['courir', 'VI', 'V2', 'Prs', '3Pau', 'B'], ['courir', 'VI', 'V2', 'Prs', '3Pau', 'A'], ['planter', 'VT', 'V1', 'Prs', '3Pau', 'C'], ['rejoindre', 'VT', 'V2', 'Prs', '3Sg', 'B'], ['rejoindre', 'VT', 'V2', 'Prs', '3Sg', 'D'], [u'prot\xe9ger', u'VT', u'V1', u'Pst', u'3Sg', u'B'], ['attraper', 'VT', 'V1', 'Prs', '3Sg', 'B'], [u'd\xe9couvrir', u'VT', u'V2', u'Prs', u'3Pau', u'C'], ['voir', 'VT', 'V2', 'Prs', '3Sg', 'C'], ['voir', 'VT', 'V2', 'Prs', '3Sg', 'A'], [u'inqui\xe9ter', u'VT', u'V1', u'Pst', u'3Pl', u'D'], ['parler', 'VI', 'V2', 'Pst', '3Pau', 'B'], ['lancer', 'VT', 'V2', 'Prs', '3Sg', 'D'], ['lancer', 'VT', 'V2', 'Prs', '3Sg', 'B'], ['sortir-Mov', 'VI', 'V1', 'Pst', '3Sg', 'A'], ['sortir-Mov', 'VI', 'V1', 'Pst', '3Sg', 'B'], ['approcher', 'VI', 'V1', 'Pst', '3Sg', 'A'], ['dormir', 'VI', 'V2', 'Prs', '3Sg', 'D'], ['approcher', 'VI', 'V1', 'Pst', '3Sg', 'D'], ['chercher', 'VT', 'V1', 'Prs', '3Sg', 'A'], ['chercher', 'VT', 'V1', 'Prs', '3Sg', 'C'], ['chercher', 'VT', 'V1', 'Prs', '3Sg', 'B'], ['accueillir', 'VT', 'V1', 'Prs', '3Sg', 'B'], ['sortir-Mov', 'VI', 'V1', 'Pst', '3Pl', 'B'], [u'prot\xe9ger', u'VT', u'V1', u'Prs', u'3Pl', u'C'], ['boire', 'VT', 'V1', 'Pst', '3Pl', 'A'], ['enfermer', 'VT', 'V2', 'Pst', '3Sg', 'B'], ['enfermer', 'VT', 'V2', 'Pst', '3Sg', 'C'], ['surplomber', 'VT', 'V1', 'Pst', '3Sg', 'D'], ['approcher', 'VI', 'V1', 'Prs', '3Sg', 'A'], ['surplomber', 'VT', 'V1', 'Pst', '3Sg', 'A'], ['cacher', 'VT', 'V1', 'Pst', '3Pl', 'B'], ['supporter', 'VT', 'V2', 'Pst', '3Pau', 'A'], ['supporter', 'VT', 'V2', 'Pst', '3Pau', 'B'], ['acheter', 'VT', 'V1', 'Pst', '3Sg', 'D'], ['survoler', 'VT', 'V2', 'Prs', '3Sg', 'B'], ['changer', 'VT', 'V2', 'Prs', '3Pl', 'C'], ['passer', 'VI', 'V2', 'Pst', '3Pl', 'D'], ['changer', 'VT', 'V2', 'Prs', '3Pl', 'D'], ['revenir', 'VI', 'V2', 'Pst', '3Pau', 'C'], ['voler', 'VT', 'V1', 'Prs', '3Sg', 'B'], ['voler', 'VT', 'V1', 'Prs', '3Sg', 'C'], ['manger', 'VT', 'V2', 'Prs', '3Sg', 'D'], ['recouvrir', 'VT', 'V2', 'Prs', '3Pau', 'D'], ['jeter', 'VT', 'V1', 'Pst', '3Pau', 'A'], ['montrer', 'VT', 'V1', 'Prs', '3Sg', 'C'], ['montrer', 'VT', 'V1', 'Prs', '3Sg', 'B'], ['courir', 'VI', 'V2', 'Prs', '3Sg', 'A'], ['cacher', 'VT', 'V1', 'Pst', '3Sg', 'A'], ['courir', 'VI', 'V2', 'Prs', '3Sg', 'B'], ['planter', 'VT', 'V1', 'Prs', '3Sg', 'D'], ['courir', 'VI', 'V2', 'Prs', '3Sg', 'D'], ['voir', 'VT', 'V2', 'Prs', '3Pl', 'A'], ['planter', 'VT', 'V1', 'Pst', '3Sg', 'C'], ['prendre', 'VT', 'V1', 'Prs', '3Pl', 'C'], [u'dispara\xeetre', u'VI', u'V1', u'Prs', u'3Pau', u'B'], [u'prot\xe9ger', u'VT', u'V1', u'Pst', u'3Pl', u'C'], [u'prot\xe9ger', u'VT', u'V1', u'Pst', u'3Pl', u'B'], ['boire', 'VT', 'V1', 'Pst', '3Sg', 'A'], ['interroger', 'VT', 'V1', 'Prs', '3Pau', 'C'], ['voir', 'VT', 'V2', 'Prs', '3Sg', 'B'], ['nourrir', 'VT', 'V2', 'Prs', '3Pl', 'A'], ['illustrer', 'VT', 'V1', 'Prs', '3Pau', 'D'], ['chercher', 'VT', 'V1', 'Prs', '3Pau', 'C'], ['chercher', 'VT', 'V1', 'Prs', '3Pau', 'A'], ['envahir', 'VT', 'V1', 'Prs', '3Pl', 'B'], ['entrer', 'VI', 'V1', 'Prs', '3Sg', 'D'], ['entrer', 'VI', 'V1', 'Prs', '3Sg', 'B'], ['noyer', 'VT', 'V2', 'Prs', '3Sg', 'B'], ['entrer', 'VI', 'V1', 'Prs', '3Sg', 'A'], ['acheter', 'VT', 'V1', 'Pst', '3Pl', 'D'], ['transformer', 'VT', 'V1', 'Prs', '3Sg', 'B'], ['recouvrir', 'VT', 'V2', 'Pst', '3Sg', 'B'], ['hurler', 'VI', 'V2', 'Prs', '3Pau', 'A'], ['voler-Act', 'VI', 'V2', 'Pst', '3Pau', 'C'], ['supporter', 'VT', 'V2', 'Prs', '3Pau', 'A'], ['supporter', 'VT', 'V2', 'Prs', '3Pau', 'C'], ['retourner', 'VI', 'V1', 'Pst', '3Pau', 'C'], ['changer', 'VT', 'V2', 'Prs', '3Sg', 'B'], ['arriver', 'VI', 'V1', 'Pst', '3Pl', 'D'], [u'r\xeavasser', u'VI', u'V1', u'Prs', u'3Pl', u'D'], ['chasser-Act', 'VT', 'V1', 'Pst', '3Sg', 'A'], [u'\xe9changer', u'VT', u'V2', u'Prs', u'3Pl', u'D'], ['interroger', 'VT', 'V1', 'Prs', '3Sg', 'B'], ['interroger', 'VT', 'V1', 'Prs', '3Sg', 'C'], ['prendre', 'VT', 'V1', 'Prs', '3Sg', 'D'], ['prendre', 'VT', 'V1', 'Prs', '3Sg', 'A'], ['prendre', 'VT', 'V1', 'Prs', '3Sg', 'C'], ['jeter', 'VT', 'V1', 'Prs', '3Pl', 'D'], ['hurler', 'VI', 'V2', 'Prs', '3Sg', 'D'], ['jeter', 'VT', 'V1', 'Prs', '3Pl', 'A'], ['porter', 'VT', 'V2', 'Pst', '3Pl', 'A'], ['tourner-Mov', 'VI', 'V1', 'Prs', '3Sg', 'C'], ['lancer', 'VT', 'V2', 'Pst', '3Pau', 'C'], ['allumer', 'VT', 'V2', 'Prs', '3Sg', 'A'], ['acheter', 'VT', 'V1', 'Prs', '3Sg', 'B'], ['allumer', 'VT', 'V2', 'Prs', '3Sg', 'D'], ['enfermer', 'VT', 'V2', 'Pst', '3Pau', 'D'], ['faire', 'VT', 'V2', 'Prs', '3Pl', 'B'], ['faire', 'VT', 'V2', 'Prs', '3Pl', 'C'], ['jeter', 'VT', 'V1', 'Pst', '3Pl', 'D'], ['jeter', 'VT', 'V1', 'Pst', '3Pl', 'A'], [u'd\xe9couvrir', u'VT', u'V2', u'Pst', u'3Sg', u'B'], ['arriver', 'VI', 'V1', 'Pst', '3Sg', 'A'], ['arriver', 'VI', 'V1', 'Pst', '3Sg', 'B'], [u'arr\xeater', u'VT', u'V2', u'Prs', u'3Sg', u'A'], ['faire', 'VT', 'V2', 'Pst', '3Sg', 'A'], ['faire', 'VT', 'V2', 'Pst', '3Sg', 'D'], ['donner', 'VT', 'V1', 'Prs', '3Pau', 'B'], ['donner', 'VT', 'V1', 'Prs', '3Pau', 'C'], ['pousser', 'VT', 'V1', 'Prs', '3Pl', 'B'], ['vivre', 'VI', 'V1', 'Pst', '3Sg', 'B'], ['approcher', 'VI', 'V1', 'Prs', '3Sg', 'B'], ['faire', 'VT', 'V2', 'Prs', '3Sg', 'B'], ['approcher', 'VI', 'V1', 'Pst', '3Pau', 'B'], ['enlever', 'VT', 'V2', 'Pst', '3Pl', 'C'], ['voler', 'VT', 'V1', 'Pst', '3Pl', 'D'], ['chasser-Act', 'VT', 'V1', 'Prs', '3Sg', 'D'], ['pleurer', 'VT', 'V1', 'Prs', '3Sg', 'B'], ['manger', 'VT', 'V2', 'Prs', '3Pau', 'D'], ['manger', 'VT', 'V2', 'Prs', '3Pau', 'A'], ['planter', 'VT', 'V1', 'Prs', '3Pl', 'B'], [u'reconna\xeetre', u'VT', u'V2', u'Prs', u'3Sg', u'C'], ['transpercer', 'VT', 'V2', 'Prs', '3Sg', 'D'], ['boire', 'VT', 'V1', 'Prs', '3Pau', 'A'], ['transpercer', 'VT', 'V2', 'Prs', '3Sg', 'C'], ['transpercer', 'VT', 'V2', 'Prs', '3Sg', 'A'], ['reconstruire', 'VT', 'V1', 'Prs', '3Sg', 'B'], ['donner', 'VT', 'V1', 'Pst', '3Pl', 'D'], ['donner', 'VT', 'V1', 'Pst', '3Pl', 'A'], ['passer', 'VI', 'V2', 'Pst', '3Pau', 'D'], ['jeter', 'VT', 'V1', 'Pst', '3Sg', 'A'], ['dormir', 'VI', 'V2', 'Prs', '3Pl', 'B'], ['arriver', 'VI', 'V1', 'Prs', '3Sg', 'A'], ['arriver', 'VI', 'V1', 'Prs', '3Sg', 'D'], ['pousser', 'VT', 'V1', 'Pst', '3Pl', 'B'], ['hurler', 'VI', 'V2', 'Pst', '3Sg', 'B'], ['voir', 'VT', 'V2', 'Prs', '3Pau', 'D'], ['voir', 'VT', 'V2', 'Prs', '3Pau', 'B'], ['chasser-Act', 'VT', 'V1', 'Prs', '3Pl', 'B'], ['chasser-Act', 'VT', 'V1', 'Prs', '3Pl', 'C'], ['planter', 'VT', 'V1', 'Prs', '3Sg', 'C'], ['chasser-Act', 'VT', 'V1', 'Prs', '3Pl', 'D'], ['ressusciter', 'VT', 'V2', 'Prs', '3Sg', 'B'], ['pousser', 'VT', 'V1', 'Pst', '3Sg', 'A'], ['pousser', 'VT', 'V1', 'Pst', '3Sg', 'C'], [u'd\xe9tester', u'VT', u'V1', u'Prs', u'3Pl', u'D'], [u'd\xe9tester', u'VT', u'V1', u'Prs', u'3Pl', u'C'], ['acheter', 'VT', 'V1', 'Prs', '3Pau', 'D'], ['attraper', 'VT', 'V1', 'Pst', '3Pau', 'D'], ['prendre', 'VT', 'V1', 'Pst', '3Pl', 'C'], ['pousser', 'VT', 'V1', 'Pst', '3Pau', 'D'], ['manquer-Med', 'VI', 'V1', 'Prs', '3Sg', 'B'], ['pleurer', 'VT', 'V1', 'Prs', '3Pl', 'D'], ['planter', 'VT', 'V1', 'Pst', '3Pl', 'C'], ['transformer', 'VT', 'V1', 'Pst', '3Pl', 'D'], ['dormir', 'VI', 'V2', 'Pst', '3Pau', 'A'], ['chasser-Mov', 'VT', 'V1', 'Prs', '3Pl', 'C'], ['jeter', 'VT', 'V1', 'Prs', '3Sg', 'D'], ['chasser-Act', 'VT', 'V1', 'Pst', '3Pau', 'A'], ['jeter', 'VT', 'V1', 'Prs', '3Sg', 'B'], ['jeter', 'VT', 'V1', 'Prs', '3Sg', 'C'], ['envahir', 'VT', 'V1', 'Prs', '3Sg', 'D'], ['envahir', 'VT', 'V1', 'Prs', '3Sg', 'B'], ['chasser-Act', 'VT', 'V1', 'Pst', '3Pl', 'D'], ['apporter', 'VT', 'V2', 'Prs', '3Pau', 'A'], ['chasser-Act', 'VT', 'V1', 'Pst', '3Pl', 'B'], ['chasser-Act', 'VT', 'V1', 'Pst', '3Pl', 'C'], ['chasser-Act', 'VT', 'V1', 'Pst', '3Pl', 'A'], ['offrir', 'VT', 'V2', 'Pst', '3Sg', 'A'], ['arriver', 'VI', 'V1', 'Pst', '3Pau', 'D'], ['offrir', 'VT', 'V2', 'Pst', '3Sg', 'D'], ['changer', 'VT', 'V2', 'Pst', '3Pau', 'C'], [u'dispara\xeetre', u'VI', u'V1', u'Prs', u'3Pau', u'A'], ['dormir', 'VI', 'V2', 'Pst', '3Pl', 'D'], ['parler', 'VI', 'V2', 'Prs', '3Sg', 'A'], ['dormir', 'VI', 'V2', 'Pst', '3Pl', 'A'], ['jeter', 'VT', 'V1', 'Pst', '3Sg', 'B'], ['sauter', 'VI', 'V2', 'Prs', '3Sg', 'B'], ['acheter', 'VT', 'V1', 'Prs', '3Pl', 'A'], ['tomber', 'VI', 'V1', 'Prs', '3Pau', 'D'], ['donner', 'VT', 'V1', 'Pst', '3Sg', 'C'], ['donner', 'VT', 'V1', 'Pst', '3Sg', 'B'], ['tomber', 'VI', 'V1', 'Prs', '3Pau', 'A'], ['tomber', 'VI', 'V1', 'Prs', '3Pau', 'C'], ['retourner', 'VI', 'V1', 'Prs', '3Pau', 'B'], ['envahir', 'VT', 'V1', 'Pst', '3Sg', 'D'], ['envahir', 'VT', 'V1', 'Pst', '3Sg', 'B'], ['avoir', 'VT', 'V1', 'Pst', '3Pl', 'C'], ['jeter', 'VT', 'V1', 'Prs', '3Pl', 'C'], ['arriver', 'VI', 'V1', 'Prs', '3Pl', 'D'], ['arriver', 'VI', 'V1', 'Prs', '3Pl', 'C'], ['offrir', 'VT', 'V2', 'Pst', '3Pl', 'D'], ['parler', 'VI', 'V2', 'Prs', '3Pl', 'C'], ['pleurer-Act', 'VI', 'V1', 'Prs', '3Sg', 'C'], ['tomber', 'VI', 'V1', 'Pst', '3Pau', 'A'], [u'pr\xe9parer', u'VT', u'V2', u'Prs', u'3Pl', u'D'], ['chasser-Act', 'VT', 'V1', 'Prs', '3Pau', 'B'], ['chasser-Act', 'VT', 'V1', 'Prs', '3Pau', 'D'], ['courir', 'VI', 'V2', 'Pst', '3Sg', 'B'], ['entrer', 'VI', 'V1', 'Prs', '3Pau', 'D'], ['surplomber', 'VT', 'V1', 'Prs', '3Sg', 'D'], ['passer', 'VI', 'V2', 'Pst', '3Sg', 'B'], [u'dispara\xeetre', u'VI', u'V1', u'Pst', u'3Pau', u'C'], ['descendre', 'VT', 'V1', 'Prs', '3Sg', 'A'], [u'dispara\xeetre', u'VI', u'V1', u'Pst', u'3Pau', u'D'], ['compter', 'VT', 'V2', 'Pst', '3Pl', 'A'], [u'd\xe9vorer', u'VT', u'V2', u'Pst', u'3Pl', u'C'], ['tomber', 'VI', 'V1', 'Prs', '3Sg', 'D'], ['tomber', 'VI', 'V1', 'Prs', '3Sg', 'C'], ['tomber', 'VI', 'V1', 'Prs', '3Sg', 'B'], ['tomber', 'VI', 'V1', 'Prs', '3Sg', 'A'], ['transformer', 'VT', 'V1', 'Pst', '3Sg', 'C'], ['boire', 'VT', 'V1', 'Prs', '3Sg', 'A'], ['sauter', 'VI', 'V2', 'Pst', '3Sg', 'A'], ['arriver', 'VI', 'V1', 'Prs', '3Pau', 'D'], ['arriver', 'VI', 'V1', 'Prs', '3Pau', 'A'], ['sortir-Mov', 'VI', 'V1', 'Prs', '3Pau', 'C'], ['arriver', 'VI', 'V1', 'Prs', '3Pau', 'B'], ['noyer', 'VT', 'V2', 'Pst', '3Sg', 'A'], ['supporter', 'VT', 'V2', 'Pst', '3Sg', 'B'], [u'd\xe9tester', u'VT', u'V1', u'Pst', u'3Pau', u'D'], ['tomber', 'VI', 'V1', 'Pst', '3Sg', 'D'], ['tomber', 'VI', 'V1', 'Pst', '3Sg', 'B'], ['acheter', 'VT', 'V1', 'Pst', '3Pau', 'D'], ['manger', 'VT', 'V2', 'Pst', '3Sg', 'C'], ['supporter', 'VT', 'V2', 'Prs', '3Sg', 'C'], ['supporter', 'VT', 'V2', 'Prs', '3Sg', 'B'], ['supporter', 'VT', 'V2', 'Prs', '3Sg', 'D'], ['cacher', 'VT', 'V1', 'Prs', '3Sg', 'B'], ['tomber', 'VI', 'V1', 'Prs', '3Pl', 'A'], ['tomber', 'VI', 'V1', 'Prs', '3Pl', 'C'], [u'pr\xe9parer', u'VT', u'V2', u'Prs', u'3Sg', u'D'], ['apporter', 'VT', 'V2', 'Pst', '3Pl', 'C'], ['apporter', 'VT', 'V2', 'Pst', '3Pl', 'B'], ['apporter', 'VT', 'V2', 'Pst', '3Pl', 'D'], ['supporter', 'VT', 'V2', 'Prs', '3Pl', 'D'], ['boire', 'VT', 'V1', 'Prs', '3Pl', 'A'], ['manger', 'VT', 'V2', 'Pst', '3Pau', 'D'], [u'pr\xe9senter', u'VT', u'V2', u'Prs', u'3Pl', u'A'], [u'd\xe9vorer', u'VT', u'V2', u'Prs', u'3Pl', u'B'], ['fuir', 'VT', 'V1', 'Pst', '3Pau', 'A'], [u'\xeatre', u'VT', u'V2', u'Prs', u'3Sg', u'B'], [u'\xeatre', u'VT', u'V2', u'Prs', u'3Sg', u'A'], ['fuir', 'VT', 'V1', 'Prs', '3Sg', 'D'], ['fuir', 'VT', 'V1', 'Prs', '3Sg', 'A'], [u'\xeatre', u'VT', u'V2', u'Prs', u'3Sg', u'D'], ['manger', 'VT', 'V2', 'Pst', '3Pl', 'D'], ['demander', 'VT', 'V1', 'Prs', '3Pl', 'A'], ['courir', 'VI', 'V2', 'Prs', '3Pau', 'D'], ['compter', 'VT', 'V2', 'Prs', '3Pl', 'D'], ['entrer', 'VI', 'V1', 'Prs', '3Pl', 'A'], ['dormir', 'VI', 'V2', 'Pst', '3Sg', 'D'], ['dormir', 'VI', 'V2', 'Pst', '3Sg', 'B'], ['dormir', 'VI', 'V2', 'Pst', '3Sg', 'A'], ['rejoindre', 'VT', 'V2', 'Pst', '3Sg', 'D'], ['passer', 'VI', 'V2', 'Prs', '3Pl', 'D'], ['hurler', 'VI', 'V2', 'Pst', '3Pau', 'C'], ['apporter', 'VT', 'V2', 'Prs', '3Pl', 'B'], ['fuir', 'VT', 'V1', 'Pst', '3Sg', 'A'], ['allumer', 'VT', 'V2', 'Pst', '3Sg', 'B'], ['allumer', 'VT', 'V2', 'Pst', '3Sg', 'A'], ['parler', 'VI', 'V2', 'Pst', '3Sg', 'A'], ['parler', 'VI', 'V2', 'Pst', '3Sg', 'C'], ['parler', 'VI', 'V2', 'Pst', '3Sg', 'D'], ['sauter', 'VI', 'V2', 'Prs', '3Pau', 'A'], [u'r\xeavasser', u'VI', u'V1', u'Pst', u'3Pau', u'C'], ['changer', 'VT', 'V2', 'Pst', '3Pl', 'D'], [u'd\xe9vorer', u'VT', u'V2', u'Pst', u'3Sg', u'D'], ['pleurer-Act', 'VI', 'V1', 'Pst', '3Pau', 'C'], ['supporter', 'VT', 'V2', 'Pst', '3Pl', 'D'], ['raconter', 'VT', 'V1', 'Pst', '3Pau', 'B'], ['partir', 'VI', 'V2', 'Pst', '3Pau', 'C'], ['partir', 'VI', 'V2', 'Pst', '3Pau', 'A'], [u'dispara\xeetre', u'VI', u'V1', u'Pst', u'3Sg', u'B'], [u'dispara\xeetre', u'VI', u'V1', u'Pst', u'3Sg', u'A'], ['tomber', 'VI', 'V1', 'Pst', '3Pl', 'D'], ['montrer', 'VT', 'V1', 'Pst', '3Pau', 'D'], ['aller', 'VI', 'V2', 'Prs', '3Pl', 'C'], ['aller', 'VI', 'V2', 'Prs', '3Pl', 'A'], ['remercier', 'VT', 'V1', 'Pst', '3Pl', 'D'], ['remercier', 'VT', 'V1', 'Pst', '3Pl', 'A'], ['surplomber', 'VT', 'V1', 'Prs', '3Sg', 'A'], ['manger', 'VT', 'V2', 'Prs', '3Pl', 'D'], ['pousser', 'VT', 'V1', 'Prs', '3Pl', 'C'], ['manger', 'VT', 'V2', 'Prs', '3Pl', 'A'], ['aller', 'VI', 'V2', 'Pst', '3Sg', 'A'], ['compter', 'VT', 'V2', 'Prs', '3Pau', 'C'], ['sortir-Mov', 'VI', 'V1', 'Prs', '3Sg', 'B'], [u'conna\xeetre', u'VT', u'V2', u'Prs', u'3Pl', u'A'], ['montrer', 'VT', 'V1', 'Pst', '3Sg', 'C'], ['pousser', 'VT', 'V1', 'Prs', '3Sg', 'C'], ['apporter', 'VT', 'V2', 'Pst', '3Sg', 'B'], ['montrer', 'VT', 'V1', 'Pst', '3Sg', 'D'], ['lancer', 'VT', 'V2', 'Prs', '3Pau', 'B'], ['partir', 'VI', 'V2', 'Pst', '3Sg', 'C'], ['lancer', 'VT', 'V2', 'Prs', '3Pau', 'A'], ['donner', 'VT', 'V1', 'Pst', '3Sg', 'D'], [u'\xeatre', u'VT', u'V2', u'Pst', u'3Sg', u'D'], [u'\xeatre', u'VT', u'V2', u'Pst', u'3Sg', u'C'], [u'\xeatre', u'VT', u'V2', u'Pst', u'3Sg', u'B'], [u'\xeatre', u'VT', u'V2', u'Pst', u'3Sg', u'A'], ['raconter', 'VT', 'V1', 'Prs', '3Sg', 'D'], ['raconter', 'VT', 'V1', 'Prs', '3Sg', 'B'], ['compter', 'VT', 'V2', 'Prs', '3Sg', 'A'], ['entrer', 'VI', 'V1', 'Pst', '3Pau', 'C'], ['aller', 'VI', 'V2', 'Prs', '3Sg', 'B'], ['pleurer-Act', 'VI', 'V1', 'Pst', '3Pl', 'D'], [u'dispara\xeetre', u'VI', u'V1', u'Prs', u'3Sg', u'A'], ['lancer', 'VT', 'V2', 'Pst', '3Pl', 'D'], [u'd\xe9vorer', u'VT', u'V2', u'Prs', u'3Sg', u'B'], ['jardiner', 'VI', 'V2', 'Pst', '3Pau', 'C'], ['recouvrir', 'VT', 'V2', 'Prs', '3Sg', 'A'], ['partir', 'VI', 'V2', 'Pst', '3Pl', 'A'], ['embrasser', 'VT', 'V2', 'Pst', '3Pau', 'C'], ['hurler', 'VI', 'V2', 'Pst', '3Sg', 'D'], ['montrer', 'VT', 'V1', 'Pst', '3Pl', 'A'], [u'd\xe9tester', u'VT', u'V1', u'Pst', u'3Pl', u'C'], ['chercher', 'VT', 'V1', 'Pst', '3Pau', 'C'], ['dormir', 'VI', 'V2', 'Prs', '3Pau', 'C'], ['dormir', 'VI', 'V2', 'Prs', '3Pau', 'B'], [u'dispara\xeetre', u'VI', u'V1', u'Prs', u'3Sg', u'D'], [u'dispara\xeetre', u'VI', u'V1', u'Prs', u'3Sg', u'B'], [u'dispara\xeetre', u'VI', u'V1', u'Prs', u'3Sg', u'C'], ['dormir', 'VI', 'V2', 'Prs', '3Pau', 'D'], ['offrir', 'VT', 'V2', 'Prs', '3Pl', 'B']]
Index([u'Prs', u'Pst'], dtype='object', name=u'C3')

In [47]:
fc=filledCells["ADJ"]
print fc[0]
tableauxRemplissage["ADJ"]=filledTable(fc,0,[1],[2])
tableauxRemplissage["ADJ"]=filledTable(fc,0,[1],[2,3])
tableauxRemplissage["ADJ"]=filledTable(fc,0,[1,2],[3,4])

maigre.A1.C.PAU.Erg
[]
[]
[]
0 Index([u'A1', u'A2'], dtype='object', name=u'C1')
1 Index([u'A', u'B', u'C', u'D'], dtype='object', name=u'C2')

In [48]:
fc=filledCells["DET"]
print fc[0]
tableauxRemplissage["DET"]=filledTable(fc,0,[1],[2])
tableauxRemplissage["DET"]=filledTable(fc,0,[1],[2,3])
# tableauxRemplissage["DET"]=filledTable(fc,0,[1,2],[3,4])

DEF.A.PL.erg
[]
[]

In [49]:
fc=filledCells["PRO"]
print fc[0]
if fc[0]:
    tableauxRemplissage["PRO"]=filledTable(fc,0,[1],[2])
    tableauxRemplissage["PRO"]=filledTable(fc,0,[1],[3,2])

PRO.D.Sg.Abs
[]
[]

# Tableaux remplis

In [50]:
tableauxLatexRemplissage=[]
tableauxLatexRemplissage.append(ur"\subsection*{Tableaux de remplissage}")
for cat in "DET PRO NOM ADJ VER".split(" "):
#    print ur"\section{%s}"%cat
    if cat in tableauxRemplissage:
        tableauxLatexRemplissage.append(u"%%\\columnbreak\n\\subsubsection*{%s}"%cat)
        tableauxLatexRemplissage.append(tableauxRemplissage[cat].to_latex(multirow=True)+u" \\\\ \\medskip")
        tableauxLatexRemplissage.append("")
print "\n".join(tableauxLatexRemplissage)

\subsection*{Tableaux de remplissage}
%\columnbreak
\subsubsection*{DET}
\begin{tabular}{lrrrrrrrrrrrr}
\toprule
Nombre & \multicolumn{4}{l}{Sg} & \multicolumn{4}{l}{Pau} & \multicolumn{4}{l}{Pl} \\
Cas & Erg & Abs & Dat & Obl & Erg & Abs & Dat & Obl & Erg & Abs & Dat & Obl \\
Genre &     &     &     &     &     &     &     &     &     &     &     &     \\
\midrule
A     &   4 &   3 &   3 &   3 &   4 &   3 &   1 &   1 &   3 &   3 &   3 &   3 \\
B     &   5 &   3 &   3 &   3 &   5 &   3 &   1 &   2 &   4 &   3 &   3 &   2 \\
C     &   5 &   3 &   4 &   3 &   5 &   3 &   4 &   2 &   3 &   3 &   3 &   3 \\
D     &   6 &   3 &   4 &   3 &   5 &   3 &   3 &   3 &   5 &   3 &   4 &   3 \\
\bottomrule
\end{tabular}
 \\ \medskip

%\columnbreak
\subsubsection*{PRO}
\begin{tabular}{lrrrrrrrrr}
\toprule
Cas & \multicolumn{3}{l}{Erg} & \multicolumn{3}{l}{Abs} & \multicolumn{3}{l}{Obl} \\
Nombre &  Sg & Pau & Pl &  Sg & Pau & Pl &  Sg & Pau & Pl \\
Genre &     &     &    &     &     &    &     &     &    \\
\midrule
A     &   1 &   1 &  1 &   0 &   1 &  0 &   0 &   0 &  0 \\
B     &   1 &   1 &  0 &   1 &   0 &  0 &   0 &   0 &  0 \\
C     &   0 &   1 &  0 &   0 &   1 &  0 &   0 &   1 &  0 \\
D     &   0 &   0 &  1 &   1 &   0 &  0 &   0 &   0 &  0 \\
\bottomrule
\end{tabular}
 \\ \medskip

%\columnbreak
\subsubsection*{NOM}
\begin{tabular}{lrrrrrrrrrrrr}
\toprule
Nombre & \multicolumn{4}{l}{Sg} & \multicolumn{4}{l}{Pau} & \multicolumn{4}{l}{Pl} \\
Cas & Erg & Abs & Dat & Obl & Erg & Abs & Dat & Obl & Erg & Abs & Dat & Obl \\
CF &     &     &     &     &     &     &     &     &     &     &     &     \\
\midrule
N1 &  18 &  20 &   9 &  21 &   3 &   7 &   1 &   4 &   8 &  12 &   8 &  14 \\
N2 &  18 &  20 &   7 &  20 &  12 &   9 &   7 &   6 &  10 &  17 &   4 &  12 \\
N3 &  15 &  17 &  11 &  15 &  12 &  10 &   2 &   6 &   9 &  14 &   3 &  12 \\
N4 &  18 &  23 &  10 &  14 &   8 &  11 &   1 &   1 &  11 &  15 &   3 &   9 \\
\bottomrule
\end{tabular}
 \\ \medskip

%\columnbreak
\subsubsection*{ADJ}
\begin{tabular}{llrrrrrrrrrrrr}
\toprule
   & Nombre & \multicolumn{4}{l}{Sg} & \multicolumn{4}{l}{Pau} & \multicolumn{4}{l}{Pl} \\
   & Cas & Erg & Abs & Dat & Obl & Erg & Abs & Dat & Obl & Erg & Abs & Dat & Obl \\
CF & Genre &     &     &     &     &     &     &     &     &     &     &     &     \\
\midrule
\multirow{4}{*}{A1} & A &   5 &   3 &   0 &   1 &   6 &   6 &   1 &   3 &   4 &   6 &   0 &   1 \\
   & B &   4 &   5 &   1 &   5 &   5 &   4 &   1 &   3 &   3 &   4 &   1 &   0 \\
   & C &   7 &   1 &   0 &   2 &   4 &   4 &   4 &   4 &   2 &   4 &   2 &   0 \\
   & D &   4 &   3 &   3 &   3 &   7 &   4 &   3 &   2 &   4 &   4 &   1 &   5 \\
\cline{1-14}
\multirow{4}{*}{A2} & A &   3 &   5 &   1 &   3 &   2 &   4 &   0 &   0 &   0 &   3 &   0 &   2 \\
   & B &   6 &   7 &   2 &   4 &   6 &   2 &   0 &   1 &   3 &   3 &   0 &   4 \\
   & C &   7 &   4 &   1 &   2 &   3 &   2 &   1 &   3 &   0 &   4 &   2 &   2 \\
   & D &   4 &   5 &   0 &   8 &   2 &   6 &   0 &   0 &   5 &   4 &   0 &   2 \\
\bottomrule
\end{tabular}
 \\ \medskip

%\columnbreak
\subsubsection*{VER}
\begin{tabular}{llrrrrrrrrrrrr}
\toprule
   & Pers & \multicolumn{4}{l}{3Sg} & \multicolumn{4}{l}{3Pau} & \multicolumn{4}{l}{3Pl} \\
   & Genre &   A &   B &   C &   D &    A &  B &   C &  D &   A &  B &   C &   D \\
CF & Temps &     &     &     &     &      &    &     &    &     &    &     &     \\
\midrule
\multirow{2}{*}{V1} & Prs &  11 &  24 &  13 &  15 &    5 &  5 &   6 &  6 &   8 &  5 &  10 &   9 \\
   & Pst &  12 &  10 &   5 &   7 &    4 &  2 &   6 &  7 &   6 &  5 &   7 &  11 \\
\cline{1-14}
\multirow{2}{*}{V2} & Prs &   9 &  17 &   4 &  13 &    7 &  5 &   4 &  5 &   7 &  6 &   5 &   8 \\
   & Pst &  11 &  11 &   7 &   9 &    3 &  2 &  10 &  3 &   4 &  3 &   3 &   8 \\
\bottomrule
\end{tabular}
 \\ \medskip

In [51]:
with codecs.open(serie+"Flexions.tex","w",encoding="utf8") as outFile:
    print "\n".join(tableauxLatex+cfLatex+genresLatex+tableauxLatexRemplissage)
    outFile.write("\n".join(tableauxLatex+cfLatex+genresLatex+tableauxLatexRemplissage))

\subsection*{Tableaux de flexion}
\subsubsection*{DET}
\needspace{6\baselineskip}
\noindent
DET IND => l\\
\begin{tabular}{lllll}
\toprule
    & Nombre &       Sg &      Pau &       Pl \\
Cas & Genre &          &          &          \\
\midrule
\multirow{4}{*}{Abs} & A &    l-a-b &    l-a-v &    l-a-n \\
    & B &    l-a-b &    l-a-v &    l-a-n \\
    & C &    l-e-p &    l-e-f &    l-e-ŋ \\
    & D &    l-e-p &    l-e-f &    l-e-n \\
\cline{1-5}
\multirow{4}{*}{Dat} & A &  l-a-b-a &  l-a-v-a &  l-a-n-a \\
    & B &  l-a-b-a &  l-a-v-a &  l-a-n-a \\
    & C &  l-e-p-a &  l-e-f-a &  l-e-ŋ-a \\
    & D &  l-e-p-a &  l-e-f-a &  l-e-n-a \\
\cline{1-5}
\multirow{4}{*}{Erg} & A &  l-a-b-e &  l-a-v-e &  l-a-n-e \\
    & B &  l-a-b-e &  l-a-v-e &  l-a-n-e \\
    & C &  l-e-p-e &  l-e-f-e &  l-e-ŋ-e \\
    & D &  l-e-p-e &  l-e-f-e &  l-e-n-e \\
\cline{1-5}
\multirow{4}{*}{Obl} & A &  l-a-b-o &  l-a-v-o &  l-a-n-o \\
    & B &  l-a-b-o &  l-a-v-o &  l-a-n-o \\
    & C &  l-e-p-o &  l-e-f-o &  l-e-ŋ-o \\
    & D &  l-e-p-o &  l-e-f-o &  l-e-n-o \\
\bottomrule
\end{tabular}
 \\ \medskip

\subsubsection*{PRO}
\needspace{6\baselineskip}
\noindent
PRO PRO => r\\
\begin{tabular}{lllll}
\toprule
    & Nombre &        Sg &       Pau &        Pl \\
Cas & Genre &           &           &           \\
\midrule
\multirow{4}{*}{Abs} & A &    r-a-st &    r-a-ks &    r-a-sp \\
    & B &    r-o-st &    r-o-ks &    r-o-sp \\
    & C &    r-e-st &    r-e-ks &    r-e-sp \\
    & D &    r-i-st &    r-i-ks &    r-i-sp \\
\cline{1-5}
\multirow{4}{*}{Dat} & A &  r-a-st-e &  r-a-ks-e &  r-a-sp-e \\
    & B &  r-o-st-e &  r-o-ks-e &  r-o-sp-e \\
    & C &  r-e-st-e &  r-e-ks-e &  r-e-sp-e \\
    & D &  r-i-st-e &  r-i-ks-e &  r-i-sp-e \\
\cline{1-5}
\multirow{4}{*}{Erg} & A &  r-a-st-i &  r-a-ks-i &  r-a-sp-i \\
    & B &  r-o-st-i &  r-o-ks-i &  r-o-sp-i \\
    & C &  r-e-st-i &  r-e-ks-i &  r-e-sp-i \\
    & D &  r-i-st-i &  r-i-ks-i &  r-i-sp-i \\
\cline{1-5}
\multirow{4}{*}{Obl} & A &  r-a-st-u &  r-a-ks-u &  r-a-sp-u \\
    & B &  r-o-st-u &  r-o-ks-u &  r-o-sp-u \\
    & C &  r-e-st-u &  r-e-ks-u &  r-e-sp-u \\
    & D &  r-i-st-u &  r-i-ks-u &  r-i-sp-u \\
\bottomrule
\end{tabular}
 \\ \medskip

\subsubsection*{NOM}
\needspace{6\baselineskip}
\noindent
N1 chef => fojub\\
\begin{tabular}{llll}
\toprule
Nombre &         Sg &         Pau &                           Pl \\
Cas &            &             &                              \\
\midrule
Abs &    fojub-o &     fojub-i &       racine(fojub)x1Vb2i33o \\
Dat &  fojub-o-m &  ʒe-fojub-i &  ʒe+racine(fojub)x1Vb2i33o+m \\
Erg &  fojub-o-θ &   fojub-i-θ &     racine(fojub)x1Vb2i33o-ð \\
Obl &  fojub-o-l &   fojub-i-l &     racine(fojub)x1Vb2i33o-l \\
\bottomrule
\end{tabular}
 \\ \medskip

\needspace{6\baselineskip}
\noindent
N2 thé => letig\\
\begin{tabular}{llll}
\toprule
Nombre &          Sg &                       Pau &                        Pl \\
Cas &             &                           &                           \\
\midrule
Abs &   letig-o-p &   racine(letig)x1V23oθi-p &   racine(letig)x1V22i3o-p \\
Dat &   letig-o-ŋ &   racine(letig)x1V23oθi-ŋ &   racine(letig)x1V22i3o-ŋ \\
Erg &  ʒo-letig-o &  ʒo-racine(letig)x1V23oθi &  ʒo-racine(letig)x1V22i3o \\
Obl &   letig-o-s &   racine(letig)x1V23oθi-l &   racine(letig)x1V22i3o-l \\
\bottomrule
\end{tabular}
 \\ \medskip

\needspace{6\baselineskip}
\noindent
N3 chambre => figam\\
\begin{tabular}{llll}
\toprule
Nombre &                       Sg &                      Pau &           Pl \\
Cas &                          &                          &              \\
\midrule
Abs &  racine(figam)x1V22u3i-p &  racine(figam)x1V23oθi-g &  figam-oθi-g \\
Dat &  racine(figam)x1V22u3i-ŋ &  racine(figam)x1V23oθi-ŋ &  figam-oθi-ŋ \\
Erg &  racine(figam)x1V22u3i-v &  racine(figam)x1V23oθi-ʒ &  figam-oθi-ʒ \\
Obl &  racine(figam)x1V22u3i-l &  racine(figam)x1V23oθi-ʒ &  figam-oθi-l \\
\bottomrule
\end{tabular}
 \\ \medskip

\needspace{6\baselineskip}
\noindent
N4 gorge => buʃog\\
\begin{tabular}{llll}
\toprule
Nombre &            Sg &                      Pau &            Pl \\
Cas &               &                          &               \\
\midrule
Abs &  θe+buʃog+a-b &  racine(buʃog)x1V23o3i-b &   buʃog-oθi-f \\
Dat &  θe+buʃog+a-ŋ &  racine(buʃog)x1V23o3i-ŋ &   buʃog-oθi-ŋ \\
Erg &  θe+buʃog+a-j &  racine(buʃog)x1V23o3i-j &   buʃog-oθi-j \\
Obl &  θe+buʃog+a-l &  racine(buʃog)x1V23o3i-l &  mu-buʃog-oθi \\
\bottomrule
\end{tabular}
 \\ \medskip

\subsubsection*{ADJ}
\needspace{6\baselineskip}
\noindent
A1 quatre => bufoʃ\\
\begin{tabular}{lllll}
\toprule
    & Nombre &               Sg &                          Pau &               Pl \\
Cas & Genre &                  &                              &                  \\
\midrule
\multirow{4}{*}{Abs} & A &       bufoʃ-oʃ-a &       racine(bufoʃ)x1V23a3-a &       bufoʃ-eʒ-a \\
    & B &    le+bufoʃ-oʃ+a &    le+racine(bufoʃ)x1V23a3+a &    le+bufoʃ-eʒ+a \\
    & C &      bufoʃ-oʃ-le &      racine(bufoʃ)x1V23a3-le &      bufoʃ-eʒ-le \\
    & D &       bufoʃ-oʃ-e &       racine(bufoʃ)x1V23a3-e &       bufoʃ-eʒ-e \\
\cline{1-5}
\multirow{4}{*}{Dat} & A &     bufoʃ-oʃ-a-θ &     racine(bufoʃ)x1V23a3-a-θ &     bufoʃ-eʒ-a-θ \\
    & B &  le+bufoʃ-oʃ+a-θ &  le+racine(bufoʃ)x1V23a3+a-θ &  le+bufoʃ-eʒ+a-θ \\
    & C &    bufoʃ-oʃ-le-θ &    racine(bufoʃ)x1V23a3-le-θ &    bufoʃ-eʒ-le-θ \\
    & D &     bufoʃ-oʃ-e-θ &     racine(bufoʃ)x1V23a3-e-θ &     bufoʃ-eʒ-e-θ \\
\cline{1-5}
\multirow{4}{*}{Erg} & A &     bufoʃ-oʃ-a-ŋ &     racine(bufoʃ)x1V23a3-a-ŋ &     bufoʃ-eʒ-a-ŋ \\
    & B &  le+bufoʃ-oʃ+a-ŋ &  le+racine(bufoʃ)x1V23a3+a-ŋ &  le+bufoʃ-eʒ+a-ŋ \\
    & C &    bufoʃ-oʃ-le-ŋ &    racine(bufoʃ)x1V23a3-le-ŋ &    bufoʃ-eʒ-le-ŋ \\
    & D &     bufoʃ-oʃ-e-ŋ &     racine(bufoʃ)x1V23a3-e-ŋ &     bufoʃ-eʒ-e-ŋ \\
\cline{1-5}
\multirow{4}{*}{Obl} & A &     bufoʃ-oʃ-a-l &     racine(bufoʃ)x1V23a3-a-l &     bufoʃ-eʒ-a-l \\
    & B &  le+bufoʃ-oʃ+a-l &  le+racine(bufoʃ)x1V23a3+a-l &  le+bufoʃ-eʒ+a-l \\
    & C &    bufoʃ-oʃ-le-l &    racine(bufoʃ)x1V23a3-le-l &    bufoʃ-eʒ-le-l \\
    & D &     bufoʃ-oʃ-e-l &     racine(bufoʃ)x1V23a3-e-l &     bufoʃ-eʒ-e-l \\
\bottomrule
\end{tabular}
 \\ \medskip

\needspace{6\baselineskip}
\noindent
A2 rouge => labið\\
\begin{tabular}{lllll}
\toprule
    & Nombre &               Sg &                          Pau &                             Pl \\
Cas & Genre &                  &                              &                                \\
\midrule
\multirow{4}{*}{Abs} & A &       labið-oʃ-e &       racine(labið)x1V23a3-e &       racine(labið)xsi1a12o3-e \\
    & B &    le+labið-oʃ+a &    le+racine(labið)x1V23a3+a &    le+racine(labið)xsi1a12o3+a \\
    & C &         labið-oʃ &         racine(labið)x1V23a3 &         racine(labið)xsi1a12o3 \\
    & D &    le+labið-oʃ+e &    le+racine(labið)x1V23a3+e &    le+racine(labið)xsi1a12o3+e \\
\cline{1-5}
\multirow{4}{*}{Dat} & A &     labið-oʃ-e-θ &     racine(labið)x1V23a3-e-θ &     racine(labið)xsi1a12o3-e-θ \\
    & B &  le+labið-oʃ+a-θ &  le+racine(labið)x1V23a3+a-θ &  le+racine(labið)xsi1a12o3+a-θ \\
    & C &       labið-oʃ-θ &       racine(labið)x1V23a3-θ &       racine(labið)xsi1a12o3-θ \\
    & D &  le+labið-oʃ+e-θ &  le+racine(labið)x1V23a3+e-θ &  le+racine(labið)xsi1a12o3+e-θ \\
\cline{1-5}
\multirow{4}{*}{Erg} & A &     labið-oʃ-e-ŋ &     racine(labið)x1V23a3-e-ŋ &     racine(labið)xsi1a12o3-e-ŋ \\
    & B &  le+labið-oʃ+a-ŋ &  le+racine(labið)x1V23a3+a-ŋ &  le+racine(labið)xsi1a12o3+a-ŋ \\
    & C &       labið-oʃ-ŋ &       racine(labið)x1V23a3-ŋ &       racine(labið)xsi1a12o3-ŋ \\
    & D &  le+labið-oʃ+e-ŋ &  le+racine(labið)x1V23a3+e-ŋ &  le+racine(labið)xsi1a12o3+e-ŋ \\
\cline{1-5}
\multirow{4}{*}{Obl} & A &     labið-oʃ-e-l &     racine(labið)x1V23a3-e-l &     racine(labið)xsi1a12o3-e-l \\
    & B &  le+labið-oʃ+a-l &  le+racine(labið)x1V23a3+a-l &  le+racine(labið)xsi1a12o3+a-l \\
    & C &       labið-oʃ-l &       racine(labið)x1V23a3-l &       racine(labið)xsi1a12o3-l \\
    & D &  le+labið-oʃ+e-l &  le+racine(labið)x1V23a3+e-l &  le+racine(labið)xsi1a12o3+e-l \\
\bottomrule
\end{tabular}
 \\ \medskip

\subsubsection*{VER}
\needspace{6\baselineskip}
\noindent
V1 approcher => luθaʒ\\
\begin{tabular}{lllll}
\toprule
    & Pers &                     3Sg &                      3Pau &                       3Pl \\
Temps & Genre &                         &                           &                           \\
\midrule
\multirow{4}{*}{PRS} & A &  racine(luθaʒ)x1V1a23-u &  racine(luθaʒ)x1V1a23-u-w &  racine(luθaʒ)x1V1a23-u-ŋ \\
    & B &  racine(luθaʒ)x1V1a23-o &  racine(luθaʒ)x1V1a23-o-w &  racine(luθaʒ)x1V1a23-o-ŋ \\
    & C &  racine(luθaʒ)x1V1a23-i &  racine(luθaʒ)x1V1a23-i-w &  racine(luθaʒ)x1V1a23-i-ŋ \\
    & D &  racine(luθaʒ)x1V1a23-e &  racine(luθaʒ)x1V1a23-e-w &  racine(luθaʒ)x1V1a23-e-ŋ \\
\cline{1-5}
\multirow{4}{*}{PST} & A &              luθaʒ-ow-u &              luθaʒ-ow-u-w &              luθaʒ-ow-u-ŋ \\
    & B &              luθaʒ-ow-o &              luθaʒ-ow-o-w &              luθaʒ-ow-o-ŋ \\
    & C &              luθaʒ-ow-i &              luθaʒ-ow-i-w &              luθaʒ-ow-i-ŋ \\
    & D &              luθaʒ-ow-e &              luθaʒ-ow-e-w &              luθaʒ-ow-e-ŋ \\
\bottomrule
\end{tabular}
 \\ \medskip

\needspace{6\baselineskip}
\noindent
V2 hurler => siren\\
\begin{tabular}{lllll}
\toprule
    & Pers &                       3Sg &                      3Pau &                       3Pl \\
Temps & Genre &                           &                           &                           \\
\midrule
\multirow{4}{*}{PRS} & A &  racine(siren)x1V1a23-u-j &  racine(siren)x1V1a23-u-k &  racine(siren)x1V1a23-u-k \\
    & B &  racine(siren)x1V1a23-u-j &  racine(siren)x1V1a23-u-k &  racine(siren)x1V1a23-u-k \\
    & C &  racine(siren)x1V1a23-e-j &  racine(siren)x1V1a23-e-k &  racine(siren)x1V1a23-e-k \\
    & D &  racine(siren)x1V1a23-e-j &  racine(siren)x1V1a23-e-k &  racine(siren)x1V1a23-e-k \\
\cline{1-5}
\multirow{4}{*}{PST} & A &  racine(siren)x1V2a23-u-j &  racine(siren)x1V2a23-u-k &  racine(siren)x1V2a23-u-k \\
    & B &  racine(siren)x1V2a23-u-j &  racine(siren)x1V2a23-u-k &  racine(siren)x1V2a23-u-k \\
    & C &  racine(siren)x1V2a23-e-j &  racine(siren)x1V2a23-e-k &  racine(siren)x1V2a23-e-k \\
    & D &  racine(siren)x1V2a23-e-j &  racine(siren)x1V2a23-e-k &  racine(siren)x1V2a23-e-k \\
\bottomrule
\end{tabular}
 \\ \medskip

\subsection*{Classes flexionnelles}
NOM :
\begin{description}
\item[- N1] Clemencia, Freja, Hoderi, autruche, bras, chef, combattant, coussin, couteau, crapaud, créature, douleur, démon, lit, louve, lune, légende, légume, maison, marais, milieu, mort, obscurité, oeil, peau, place, proximité, raison, sortilège, village
\item[- N2] Nabil, arbre, blessure, caillou, chasseur, combat, cuisine, donjon, enfant, excuse, fruit, gargouille, harmonie, histoire, homme, hurlement, infirmière, jour, loup, lueur, manoir, mère, ombre, serpent, sorcier, souffrance, table, thé, vengeance, œuf
\item[- N3] Agathos, Elphaba, Katisha, Nicole, balai, chambre, chat, chatte, chemin, corps, dernier-n, disparition, dragon, dégât, femme, feu, fille, forêt, garçon, héros, livre, main, matin, nuit, parent, plaine, père, sort, voleuse, vote
\item[- N4] Kaleb, Mahira, Violette, bûcher, café, colère, construction, coup, coyote, cri, croc, côté, demande, esprit, gorge, grimoire, jardin, lance, lever-n, lumière, maître, nouvelle-n, poisson, robe, soeur, souris, tornade, viande, villageois, villageoise, visage
\end{description}
ADJ :
\begin{description}
\item[- A1] autre, blanc, cinq, courageux, deux, effrayé, gros, héroïque, maigre, méchant, nouveau, petit, quatre, sept, six, vert, vilain
\item[- A2] bas, blessé, dernier, différent, disparu, furieux, grand, jaune, noir, nombreux, profond, rouge, suivant, terrible, treize, trois, troisième
\end{description}
VER :
\begin{description}
\item[- V1] accueillir, acheter, approcher, arriver, attraper, avoir, boire, brûler, cacher, chasser-act, chasser-mov, chercher, demander, descendre, disparaître, donner, détester, entrer, envahir, fuir, illustrer, inquiéter, interroger, jeter, manquer-med, montrer, mourir, pendre, planter, pleurer, pleurer-act, pousser, prendre, protéger, raconter, reconstruire, redevenir, remercier, retourner, rêvasser, sortir-mov, surplomber, tomber, tourner-mov, transformer, vivre, voler, voter
\item[- V2] aller, allumer, apporter, arrêter, brûler-med, changer, compter, connaître, courir, dormir, découvrir, dévorer, embrasser, enfermer, enlever, excuser, faire, hurler, jardiner, lancer, lever, manger, nourrir, noyer, nuire, offrir, parler, partir, passer, placer, porter, posséder, préparer, présenter, reconnaître, recouvrir, rejoindre, ressusciter, revenir, sauter, supporter, survoler, transpercer, voir, voler-act, échanger, être
\end{description}
\subsection*{Genre des noms}
\begin{description}
\item[- A] Clemencia, Kaleb, Katisha, Mahira, café, chambre, chasseur, chef, chemin, corps, disparition, donjon, esprit, excuse, feu, gorge, homme, lune, marais, mère, place, plaine, raison, robe, serpent, sortilège, souris, thé
\item[- B] Elphaba, Freja, Hoderi, Nicole, bras, chat, combat, combattant, croc, dernier-n, dragon, femme, grimoire, hurlement, infirmière, loup, louve, lueur, lumière, légende, manoir, matin, maître, milieu, mort, soeur, souffrance, table, viande, villageoise, visage, voleuse
\item[- C] Agathos, arbre, autruche, chatte, colère, construction, couteau, cri, créature, cuisine, côté, demande, douleur, dégât, démon, enfant, harmonie, héros, jardin, jour, lance, livre, nouvelle-n, obscurité, oeil, ombre, père, sorcier, sort
\item[- D] Nabil, Violette, balai, blessure, bûcher, caillou, coup, coussin, coyote, crapaud, fille, forêt, fruit, gargouille, garçon, histoire, lever-n, lit, légume, main, maison, nuit, parent, peau, poisson, proximité, tornade, vengeance, village, villageois, vote, œuf
\end{description}
\subsection*{Tableaux de remplissage}
%\columnbreak
\subsubsection*{DET}
\begin{tabular}{lrrrrrrrrrrrr}
\toprule
Nombre & \multicolumn{4}{l}{Sg} & \multicolumn{4}{l}{Pau} & \multicolumn{4}{l}{Pl} \\
Cas & Erg & Abs & Dat & Obl & Erg & Abs & Dat & Obl & Erg & Abs & Dat & Obl \\
Genre &     &     &     &     &     &     &     &     &     &     &     &     \\
\midrule
A     &   4 &   3 &   3 &   3 &   4 &   3 &   1 &   1 &   3 &   3 &   3 &   3 \\
B     &   5 &   3 &   3 &   3 &   5 &   3 &   1 &   2 &   4 &   3 &   3 &   2 \\
C     &   5 &   3 &   4 &   3 &   5 &   3 &   4 &   2 &   3 &   3 &   3 &   3 \\
D     &   6 &   3 &   4 &   3 &   5 &   3 &   3 &   3 &   5 &   3 &   4 &   3 \\
\bottomrule
\end{tabular}
 \\ \medskip

%\columnbreak
\subsubsection*{PRO}
\begin{tabular}{lrrrrrrrrr}
\toprule
Cas & \multicolumn{3}{l}{Erg} & \multicolumn{3}{l}{Abs} & \multicolumn{3}{l}{Obl} \\
Nombre &  Sg & Pau & Pl &  Sg & Pau & Pl &  Sg & Pau & Pl \\
Genre &     &     &    &     &     &    &     &     &    \\
\midrule
A     &   1 &   1 &  1 &   0 &   1 &  0 &   0 &   0 &  0 \\
B     &   1 &   1 &  0 &   1 &   0 &  0 &   0 &   0 &  0 \\
C     &   0 &   1 &  0 &   0 &   1 &  0 &   0 &   1 &  0 \\
D     &   0 &   0 &  1 &   1 &   0 &  0 &   0 &   0 &  0 \\
\bottomrule
\end{tabular}
 \\ \medskip

%\columnbreak
\subsubsection*{NOM}
\begin{tabular}{lrrrrrrrrrrrr}
\toprule
Nombre & \multicolumn{4}{l}{Sg} & \multicolumn{4}{l}{Pau} & \multicolumn{4}{l}{Pl} \\
Cas & Erg & Abs & Dat & Obl & Erg & Abs & Dat & Obl & Erg & Abs & Dat & Obl \\
CF &     &     &     &     &     &     &     &     &     &     &     &     \\
\midrule
N1 &  18 &  20 &   9 &  21 &   3 &   7 &   1 &   4 &   8 &  12 &   8 &  14 \\
N2 &  18 &  20 &   7 &  20 &  12 &   9 &   7 &   6 &  10 &  17 &   4 &  12 \\
N3 &  15 &  17 &  11 &  15 &  12 &  10 &   2 &   6 &   9 &  14 &   3 &  12 \\
N4 &  18 &  23 &  10 &  14 &   8 &  11 &   1 &   1 &  11 &  15 &   3 &   9 \\
\bottomrule
\end{tabular}
 \\ \medskip

%\columnbreak
\subsubsection*{ADJ}
\begin{tabular}{llrrrrrrrrrrrr}
\toprule
   & Nombre & \multicolumn{4}{l}{Sg} & \multicolumn{4}{l}{Pau} & \multicolumn{4}{l}{Pl} \\
   & Cas & Erg & Abs & Dat & Obl & Erg & Abs & Dat & Obl & Erg & Abs & Dat & Obl \\
CF & Genre &     &     &     &     &     &     &     &     &     &     &     &     \\
\midrule
\multirow{4}{*}{A1} & A &   5 &   3 &   0 &   1 &   6 &   6 &   1 &   3 &   4 &   6 &   0 &   1 \\
   & B &   4 &   5 &   1 &   5 &   5 &   4 &   1 &   3 &   3 &   4 &   1 &   0 \\
   & C &   7 &   1 &   0 &   2 &   4 &   4 &   4 &   4 &   2 &   4 &   2 &   0 \\
   & D &   4 &   3 &   3 &   3 &   7 &   4 &   3 &   2 &   4 &   4 &   1 &   5 \\
\cline{1-14}
\multirow{4}{*}{A2} & A &   3 &   5 &   1 &   3 &   2 &   4 &   0 &   0 &   0 &   3 &   0 &   2 \\
   & B &   6 &   7 &   2 &   4 &   6 &   2 &   0 &   1 &   3 &   3 &   0 &   4 \\
   & C &   7 &   4 &   1 &   2 &   3 &   2 &   1 &   3 &   0 &   4 &   2 &   2 \\
   & D &   4 &   5 &   0 &   8 &   2 &   6 &   0 &   0 &   5 &   4 &   0 &   2 \\
\bottomrule
\end{tabular}
 \\ \medskip

%\columnbreak
\subsubsection*{VER}
\begin{tabular}{llrrrrrrrrrrrr}
\toprule
   & Pers & \multicolumn{4}{l}{3Sg} & \multicolumn{4}{l}{3Pau} & \multicolumn{4}{l}{3Pl} \\
   & Genre &   A &   B &   C &   D &    A &  B &   C &  D &   A &  B &   C &   D \\
CF & Temps &     &     &     &     &      &    &     &    &     &    &     &     \\
\midrule
\multirow{2}{*}{V1} & Prs &  11 &  24 &  13 &  15 &    5 &  5 &   6 &  6 &   8 &  5 &  10 &   9 \\
   & Pst &  12 &  10 &   5 &   7 &    4 &  2 &   6 &  7 &   6 &  5 &   7 &  11 \\
\cline{1-14}
\multirow{2}{*}{V2} & Prs &   9 &  17 &   4 &  13 &    7 &  5 &   4 &  5 &   7 &  6 &   5 &   8 \\
   & Pst &  11 &  11 &   7 &   9 &    3 &  2 &  10 &  3 &   4 &  3 &   3 &   8 \\
\bottomrule
\end{tabular}
 \\ \medskip

In [52]:
ding()