In [25]:
import glob,codecs,os,yaml
import pandas as pd
from unidecode import unidecode
from os.path import expanduser
def ding():
    os.system('afplay /System/Library/Sounds/Submarine.aiff')
from IPython.core.display import HTML,display

## ⚠️
Pour les cas où le genre des noms est marqué explicitement, on utilise *nomGenre=True*

In [26]:
%store -r numerosKalaba typeKalaba
# numerosKalaba=[1]
print numerosKalaba, typeKalaba
nomGenre=False

[1] Kalaba

In [27]:
debug=0
home = expanduser("~")
repertoire=home+"/sDrive/Cours/Bordeaux/L1-LinguistiqueGenerale/00-ProjetKalaba/"
annee=24
if typeKalaba!="Kanonik":
    serie=repertoire+"%d-K%d/"%(annee,numerosKalaba[0])
else:
    serie=repertoire+"%d-Kanoniks/"%(annee,numerosKalaba[0])
    nomsKalabas=[serie+"Kanonik-%02d/"%num for num in numerosKalaba]
print serie

/Users/gilles/sDrive/Cours/Bordeaux/L1-LinguistiqueGenerale/00-ProjetKalaba/24-K1/

In [28]:
nomDeclarationRad="Declarations-Radicaux.tex"
nomDeclarationDec="Declarations-Decoupages.tex"
nomTableauxRad="Tableaux-Gloses.yaml"
nomDeclaration="Declarations.tex"
nomTableaux="Tableaux.yaml"

In [29]:
flexion=pd.read_csv(serie+"Clozes.txt",sep=";",header=None, names=list(range(20)),encoding="utf8").dropna(axis='columns', how='all')
flexion.head()

,0,1,2,3,5,6,7,8,9,10,11,12,13,14,15
0,#\tNOM,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,#,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,#,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,filleFSgNom,fille,NOM,zozuʒ,nozozuʒi,no-zozuʒ-i,"NOM, Genre=F, Nombre=Sg, Cas=Nom",Nom-fille.F-Sg,4.0,Nom-,fille,.F,-Sg,NaN,NaN
4,filleFSgAcc,fille,NOM,zozuʒ,kazozuʒi,ka-zozuʒ-i,"NOM, Genre=F, Nombre=Sg, Cas=Acc",Acc-fille.F-Sg,4.0,Acc-,fille,.F,-Sg,NaN,NaN

In [30]:
categories=flexion[2].dropna().unique().tolist()
categories

[u'NOM', u'VER', u'PRO', u'DET', u'ADJ', u'PREP']

bFlex sélectionne les lignes non-vides correspondant à une catégorie

In [31]:
bFlex={c:(flexion[7].notnull()) & (flexion[2]==c.upper()) for c in categories}
flexion[bFlex["NOM"]]

,0,1,2,3,5,6,7,8,9,10,11,12,13,14,15
3,filleFSgNom,fille,NOM,zozuʒ,nozozuʒi,no-zozuʒ-i,"NOM, Genre=F, Nombre=Sg, Cas=Nom",Nom-fille.F-Sg,4.0,Nom-,fille,.F,-Sg,NaN,NaN
4,filleFSgAcc,fille,NOM,zozuʒ,kazozuʒi,ka-zozuʒ-i,"NOM, Genre=F, Nombre=Sg, Cas=Acc",Acc-fille.F-Sg,4.0,Acc-,fille,.F,-Sg,NaN,NaN
5,filleFSgDat,fille,NOM,zozuʒ,dazozuʒi,da-zozuʒ-i,"NOM, Genre=F, Nombre=Sg, Cas=Dat",Dat-fille.F-Sg,4.0,Dat-,fille,.F,-Sg,NaN,NaN
6,filleFSgObl,fille,NOM,zozuʒ,zozuʒni,zozuʒ-n-i,"NOM, Genre=F, Nombre=Sg, Cas=Obl",fille.F-Obl-Sg,4.0,fille,.F,-Obl,-Sg,NaN,NaN
7,filleFDuNom,fille,NOM,zozuʒ,nozozuʒo,no-zozuʒ-o,"NOM, Genre=F, Nombre=Du, Cas=Nom",Nom-fille.F-Du,4.0,Nom-,fille,.F,-Du,NaN,NaN
8,filleFDuAcc,fille,NOM,zozuʒ,kazozuʒo,ka-zozuʒ-o,"NOM, Genre=F, Nombre=Du, Cas=Acc",Acc-fille.F-Du,4.0,Acc-,fille,.F,-Du,NaN,NaN
9,filleFDuDat,fille,NOM,zozuʒ,dazozuʒo,da-zozuʒ-o,"NOM, Genre=F, Nombre=Du, Cas=Dat",Dat-fille.F-Du,4.0,Dat-,fille,.F,-Du,NaN,NaN
10,filleFDuObl,fille,NOM,zozuʒ,zozuʒno,zozuʒ-n-o,"NOM, Genre=F, Nombre=Du, Cas=Obl",fille.F-Obl-Du,4.0,fille,.F,-Obl,-Du,NaN,NaN
11,filleFPlNom,fille,NOM,zozuʒ,nozozuʒa,no-zozuʒ-a,"NOM, Genre=F, Nombre=Pl, Cas=Nom",Nom-fille.F-Pl,4.0,Nom-,fille,.F,-Pl,NaN,NaN
12,filleFPlAcc,fille,NOM,zozuʒ,kazozuʒa,ka-zozuʒ-a,"NOM, Genre=F, Nombre=Pl, Cas=Acc",Acc-fille.F-Pl,4.0,Acc-,fille,.F,-Pl,NaN,NaN
13,filleFPlDat,fille,NOM,zozuʒ,dazozuʒa,da-zozuʒ-a,"NOM, Genre=F, Nombre=Pl, Cas=Dat",Dat-fille.F-Pl,4.0,Dat-,fille,.F,-Pl,NaN,NaN
14,filleFPlObl,fille,NOM,zozuʒ,zozuʒna,zozuʒ-n-a,"NOM, Genre=F, Nombre=Pl, Cas=Obl",fille.F-Obl-Pl,4.0,fille,.F,-Obl,-Pl,NaN,NaN
15,chefFSgNom,chef,NOM,buduk,nobuduki,no-buduk-i,"NOM, Genre=F, Nombre=Sg, Cas=Nom",Nom-chef.F-Sg,4.0,Nom-,chef,.F,-Sg,NaN,NaN
16,chefFSgAcc,chef,NOM,buduk,kabuduki,ka-buduk-i,"NOM, Genre=F, Nombre=Sg, Cas=Acc",Acc-chef.F-Sg,4.0,Acc-,chef,.F,-Sg,NaN,NaN
17,chefFSgDat,chef,NOM,buduk,dabuduki,da-buduk-i,"NOM, Genre=F, Nombre=Sg, Cas=Dat",Dat-chef.F-Sg,4.0,Dat-,chef,.F,-Sg,NaN,NaN
18,chefFSgObl,chef,NOM,buduk,budukni,buduk-n-i,"NOM, Genre=F, Nombre=Sg, Cas=Obl",chef.F-Obl-Sg,4.0,chef,.F,-Obl,-Sg,NaN,NaN
19,chefFDuNom,chef,NOM,buduk,nobuduko,no-buduk-o,"NOM, Genre=F, Nombre=Du, Cas=Nom",Nom-chef.F-Du,4.0,Nom-,chef,.F,-Du,NaN,NaN
20,chefFDuAcc,chef,NOM,buduk,kabuduko,ka-buduk-o,"NOM, Genre=F, Nombre=Du, Cas=Acc",Acc-chef.F-Du,4.0,Acc-,chef,.F,-Du,NaN,NaN
21,chefFDuDat,chef,NOM,buduk,dabuduko,da-buduk-o,"NOM, Genre=F, Nombre=Du, Cas=Dat",Dat-chef.F-Du,4.0,Dat-,chef,.F,-Du,NaN,NaN
22,chefFDuObl,chef,NOM,buduk,budukno,buduk-n-o,"NOM, Genre=F, Nombre=Du, Cas=Obl",chef.F-Obl-Du,4.0,chef,.F,-Obl,-Du,NaN,NaN
23,chefFPlNom,chef,NOM,buduk,nobuduka,no-buduk-a,"NOM, Genre=F, Nombre=Pl, Cas=Nom",Nom-chef.F-Pl,4.0,Nom-,chef,.F,-Pl,NaN,NaN
24,chefFPlAcc,chef,NOM,buduk,kabuduka,ka-buduk-a,"NOM, Genre=F, Nombre=Pl, Cas=Acc",Acc-chef.F-Pl,4.0,Acc-,chef,.F,-Pl,NaN,NaN
25,chefFPlDat,chef,NOM,buduk,dabuduka,da-buduk-a,"NOM, Genre=F, Nombre=Pl, Cas=Dat",Dat-chef.F-Pl,4.0,Dat-,chef,.F,-Pl,NaN,NaN
26,chefFPlObl,chef,NOM,buduk,budukna,buduk-n-a,"NOM, Genre=F, Nombre=Pl, Cas=Obl",chef.F-Obl-Pl,4.0,chef,.F,-Obl,-Pl,NaN,NaN
27,infirmiereFSgNom,infirmière,NOM,dubop,nodubopi,no-dubop-i,"NOM, Genre=F, Nombre=Sg, Cas=Nom",Nom-infirmière.F-Sg,4.0,Nom-,infirmière,.F,-Sg,NaN,NaN
28,infirmiereFSgAcc,infirmière,NOM,dubop,kadubopi,ka-dubop-i,"NOM, Genre=F, Nombre=Sg, Cas=Acc",Acc-infirmière.F-Sg,4.0,Acc-,infirmière,.F,-Sg,NaN,NaN
29,infirmiereFSgDat,infirmière,NOM,dubop,dadubopi,da-dubop-i,"NOM, Genre=F, Nombre=Sg, Cas=Dat",Dat-infirmière.F-Sg,4.0,Dat-,infirmière,.F,-Sg,NaN,NaN
30,infirmiereFSgObl,infirmière,NOM,dubop,dubopni,dubop-n-i,"NOM, Genre=F, Nombre=Sg, Cas=Obl",infirmière.F-Obl-Sg,4.0,infirmière,.F,-Obl,-Sg,NaN,NaN
31,infirmiereFDuNom,infirmière,NOM,dubop,nodubopo,no-dubop-o,"NOM, Genre=F, Nombre=Du, Cas=Nom",Nom-infirmière.F-Du,4.0,Nom-,infirmière,.F,-Du,NaN,NaN
32,infirmiereFDuAcc,infirmière,NOM,dubop,kadubopo,ka-dubop-o,"NOM, Genre=F, Nombre=Du, Cas=Acc",Acc-infirmière.F-Du,4.0,Acc-,infirmière,.F,-Du,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1449,criNDuDat,cri,NOM,vovuge,davovugeo,da-vovuge-o,"NOM, Genre=N, Nombre=Du, Cas=Dat",Dat-cri.N-Du,4.0,Dat-,cri,.N,-Du,NaN,NaN
1450,criNDuObl,cri,NOM,vovuge,vovugeno,vovuge-n-o,"NOM, Genre=N, Nombre=Du, Cas=Obl",cri.N-Obl-Du,4.0,cri,.N,-Obl,-Du,NaN,NaN
1451,criNPlNom,cri,NOM,vovuge,novovugea,no-vovuge-a,"NOM, Genre=N, Nombre=Pl, Cas=Nom",Nom-cri.N-Pl,4.0,Nom-,cri,.N,-Pl,NaN,NaN
1452,criNPlAcc,cri,NOM,vovuge,kavovugea,ka-vovuge-a,"NOM, Genre=N, Nombre=Pl, Cas=Acc",Acc-cri.N-Pl,4.0,Acc-,cri,.N,-Pl,NaN,NaN
1453,criNPlDat,cri,NOM,vovuge,davovugea,da-vovuge-a,"NOM, Genre=N, Nombre=Pl, Cas=Dat",Dat-cri.N-Pl,4.0,Dat-,cri,.N,-Pl,NaN,NaN
1454,criNPlObl,cri,NOM,vovuge,vovugena,vovuge-n-a,"NOM, Genre=N, Nombre=Pl, Cas=Obl",cri.N-Obl-Pl,4.0,cri,.N,-Obl,-Pl,NaN,NaN
1455,dragonNSgNom,dragon,NOM,ruzoz,noruzozi,no-ruzoz-i,"NOM, Genre=N, Nombre=Sg, Cas=Nom",Nom-dragon.N-Sg,4.0,Nom-,dragon,.N,-Sg,NaN,NaN
1456,dragonNSgAcc,dragon,NOM,ruzoz,karuzozi,ka-ruzoz-i,"NOM, Genre=N, Nombre=Sg, Cas=Acc",Acc-dragon.N-Sg,4.0,Acc-,dragon,.N,-Sg,NaN,NaN
1457,dragonNSgDat,dragon,NOM,ruzoz,daruzozi,da-ruzoz-i,"NOM, Genre=N, Nombre=Sg, Cas=Dat",Dat-dragon.N-Sg,4.0,Dat-,dragon,.N,-Sg,NaN,NaN
1458,dragonNSgObl,dragon,NOM,ruzoz,ruzozni,ruzoz-n-i,"NOM, Genre=N, Nombre=Sg, Cas=Obl",dragon.N-Obl-Sg,4.0,dragon,.N,-Obl,-Sg,NaN,NaN
1459,dragonNDuNom,dragon,NOM,ruzoz,noruzozo,no-ruzoz-o,"NOM, Genre=N, Nombre=Du, Cas=Nom",Nom-dragon.N-Du,4.0,Nom-,dragon,.N,-Du,NaN,NaN
1460,dragonNDuAcc,dragon,NOM,ruzoz,karuzozo,ka-ruzoz-o,"NOM, Genre=N, Nombre=Du, Cas=Acc",Acc-dragon.N-Du,4.0,Acc-,dragon,.N,-Du,NaN,NaN
1461,dragonNDuDat,dragon,NOM,ruzoz,daruzozo,da-ruzoz-o,"NOM, Genre=N, Nombre=Du, Cas=Dat",Dat-dragon.N-Du,4.0,Dat-,dragon,.N,-Du,NaN,NaN
1462,dragonNDuObl,dragon,NOM,ruzoz,ruzozno,ruzoz-n-o,"NOM, Genre=N, Nombre=Du, Cas=Obl",dragon.N-Obl-Du,4.0,dragon,.N,-Obl,-Du,NaN,NaN
1463,dragonNPlNom,dragon,NOM,ruzoz,noruzoza,no-ruzoz-a,"NOM, Genre=N, Nombre=Pl, Cas=Nom",Nom-dragon.N-Pl,4.0,Nom-,dragon,.N,-Pl,NaN,NaN
1464,dragonNPlAcc,dragon,NOM,ruzoz,karuzoza,ka-ruzoz-a,"NOM, Genre=N, Nombre=Pl, Cas=Acc",Acc-dragon.N-Pl,4.0,Acc-,dragon,.N,-Pl,NaN,NaN
1465,dragonNPlDat,dragon,NOM,ruzoz,daruzoza,da-ruzoz-a,"NOM, Genre=N, Nombre=Pl, Cas=Dat",Dat-dragon.N-Pl,4.0,Dat-,dragon,.N,-Pl,NaN,NaN
1466,dragonNPlObl,dragon,NOM,ruzoz,ruzozna,ruzoz-n-a,"NOM, Genre=N, Nombre=Pl, Cas=Obl",dragon.N-Obl-Pl,4.0,dragon,.N,-Obl,-Pl,NaN,NaN
1467,couteauNSgNom,couteau,NOM,pudoz,nopudozi,no-pudoz-i,"NOM, Genre=N, Nombre=Sg, Cas=Nom",Nom-couteau.N-Sg,4.0,Nom-,couteau,.N,-Sg,NaN,NaN
1468,couteauNSgAcc,couteau,NOM,pudoz,kapudozi,ka-pudoz-i,"NOM, Genre=N, Nombre=Sg, Cas=Acc",Acc-couteau.N-Sg,4.0,Acc-,couteau,.N,-Sg,NaN,NaN
1469,couteauNSgDat,couteau,NOM,pudoz,dapudozi,da-pudoz-i,"NOM, Genre=N, Nombre=Sg, Cas=Dat",Dat-couteau.N-Sg,4.0,Dat-,couteau,.N,-Sg,NaN,NaN
1470,couteauNSgObl,couteau,NOM,pudoz,pudozni,pudoz-n-i,"NOM, Genre=N, Nombre=Sg, Cas=Obl",couteau.N-Obl-Sg,4.0,couteau,.N,-Obl,-Sg,NaN,NaN
1471,couteauNDuNom,couteau,NOM,pudoz,nopudozo,no-pudoz-o,"NOM, Genre=N, Nombre=Du, Cas=Nom",Nom-couteau.N-Du,4.0,Nom-,couteau,.N,-Du,NaN,NaN
1472,couteauNDuAcc,couteau,NOM,pudoz,kapudozo,ka-pudoz-o,"NOM, Genre=N, Nombre=Du, Cas=Acc",Acc-couteau.N-Du,4.0,Acc-,couteau,.N,-Du,NaN,NaN
1473,couteauNDuDat,couteau,NOM,pudoz,dapudozo,da-pudoz-o,"NOM, Genre=N, Nombre=Du, Cas=Dat",Dat-couteau.N-Du,4.0,Dat-,couteau,.N,-Du,NaN,NaN
1474,couteauNDuObl,couteau,NOM,pudoz,pudozno,pudoz-n-o,"NOM, Genre=N, Nombre=Du, Cas=Obl",couteau.N-Obl-Du,4.0,couteau,.N,-Obl,-Du,NaN,NaN
1475,couteauNPlNom,couteau,NOM,pudoz,nopudoza,no-pudoz-a,"NOM, Genre=N, Nombre=Pl, Cas=Nom",Nom-couteau.N-Pl,4.0,Nom-,couteau,.N,-Pl,NaN,NaN
1476,couteauNPlAcc,couteau,NOM,pudoz,kapudoza,ka-pudoz-a,"NOM, Genre=N, Nombre=Pl, Cas=Acc",Acc-couteau.N-Pl,4.0,Acc-,couteau,.N,-Pl,NaN,NaN
1477,couteauNPlDat,couteau,NOM,pudoz,dapudoza,da-pudoz-a,"NOM, Genre=N, Nombre=Pl, Cas=Dat",Dat-couteau.N-Pl,4.0,Dat-,couteau,.N,-Pl,NaN,NaN
1478,couteauNPlObl,couteau,NOM,pudoz,pudozna,pudoz-n-a,"NOM, Genre=N, Nombre=Pl, Cas=Obl",couteau.N-Obl-Pl,4.0,couteau,.N,-Obl,-Pl,NaN,NaN

### Analyse de la case
on fait un dict à partir de la case pour éclater en colonne puis faire un pivot_table

In [32]:
def makeParadigme(row):
    result={}
    parts=row["Case"].split(", ")
    for part in parts[1:]:
        attr,val=part.split("=")
        result[attr.strip()]=val
    return result

# Tableaux pour une catégorie

In [33]:
def reindexNombre(tableau):
    result=tableau
    if "Du" in tableau.columns:
        result=tableau.reindex("Sg Du Pl".split(" "),axis=1)
    elif "Pau" in tableau.columns:
        result=tableau.reindex("Sg Pau Pl".split(" "),axis=1)
    elif "Sg" in tableau.columns:
        result=tableau.reindex("Sg Pl".split(" "),axis=1)
    return result

def reindexPers(tableau):
    result=tableau
    if "3Du" in tableau.columns:
        result=tableau.reindex("3Sg 3Du 3Pl".split(" "),axis=1)
    elif "3Pau" in tableau.columns:
        result=tableau.reindex("3Sg 3Pau 3Pl".split(" "),axis=1)
    elif "3Sg" in tableau.columns:
        result=tableau.reindex("3Sg 3Pl".split(" "),axis=1)
    return result

def reindexTableau(tableau):
    return reindexNombre(reindexPers(tableau))

In [34]:
def makeTableaux(cat):
    # sel sélectionne la catégorie cat dans flexion
    # les colonnes 1, 6 et 7 correspondent à la catégorie, la forme et la case
    sel=bFlex[cat]
    catTableaux={}
    catCF={}
    radCF={}
    cfLexemes={}

    # la colonnne 3 contient le radical
    lDF=flexion[sel][[1,6,7]]
    lDF=flexion[sel][[1,3,6,7]]
    lDF.columns=(u"%s Radical Forme Case"%cat).split(" ")
    # on ajoute une colonne avec un dict correspondant à attribut:valeur
    lDF["dCell"]=lDF.apply(makeParadigme,axis=1)
    if lDF.iloc[0]["dCell"]!={}:
        # on éclate le dict attribut:valeur en colonnes
        # on calcule les dimensions du tableau croisé pour pivot_table
        dfCat=pd.concat([lDF.drop(['Case',"dCell"], axis=1), lDF['dCell'].apply(pd.Series)], axis=1)
        setColonnes=set(dfCat.columns.tolist())
        if cat=="NOM" and not nomGenre:
            setColonnes-=set(["Genre"])
        if "Nombre" in setColonnes:
            colonnes="Nombre"
            lignes=setColonnes-set([cat,"Radical","Forme","CF","Nombre"])
        elif "Pers" in setColonnes:
            colonnes="Pers"
            lignes=list(setColonnes-set([cat,"Radical","Forme","CF","Pers"]))
        if debug: print colonnes, lignes
        # on fait la liste des lexèmes de la catégorie cat
        listCat=dfCat[cat].unique().tolist()
        if debug: display(dfCat.head())
        for l in listCat:
            print l
            catL=dfCat[dfCat[cat].str.encode("utf8")==l.encode("utf8")]
            radical=catL["Radical"].values[0]
            if "CF" in dfCat.columns:
                lCF=catL["CF"].values[0]
                if lCF not in cfLexemes:
                    cfLexemes[lCF]=[]
                cfLexemes[lCF].append(l)
                #
                # reindexNombre présente les colonnes concernant le nombre dans l'ordre traditionnel
                # SG < DU/PAU < PL
                #
                if lCF not in catCF:
                    catTableaux[lCF]=pd.pivot_table(catL,index=lignes,columns=colonnes,values="Forme", aggfunc='first')
                    catCF[lCF]=l
                    radCF[lCF]=radical
            elif cat=="NOM" and nomGenre:
                lCF=catL["Genre"].values[0]
                if lCF not in cfLexemes:
                    cfLexemes[lCF]=[]
                cfLexemes[lCF].append(l)
                if lCF not in catCF:
                    catTableaux[lCF]=pd.pivot_table(catL,index=lignes,columns=colonnes,values="Forme", aggfunc='first')
                    catCF[lCF]=l
                    radCF[lCF]=radical
            else:
                catCF[cat]=l
                radCF[cat]=radical
                catTableaux[cat]=pd.pivot_table(catL,index=lignes,columns=colonnes,values="Forme", aggfunc='first')
        for t in catTableaux:   
            if debug: display(HTML("<h1>%s, %s</h1>"%(t,catCF[t])),reindexTableau(catTableaux[t]))
#             print t,catCF[t],radCF[t]
#             print reindexTableau(catTableaux[t]).to_latex(multirow=True)
    return catTableaux,cfLexemes,catCF,radCF

In [35]:
tableaux={}
tableauxLatex=[]
lexemesCF={}
cfLexs={}
cfRads={}
tableauxLatex.append(ur"\subsection*{Tableaux de flexion}")
for cat in "DET PRO NOM ADJ VER".split(" "):
#    print ur"\section{%s}"%cat
    tableauxLatex.append(ur"\subsubsection*{%s}"%cat)
    tableaux[cat],lexemesCF[cat],cfLexs[cat],cfRads[cat]=makeTableaux(cat)
#     print tableaux[cat]
#     print lexemesCF[cat]
    for t in tableaux[cat]:
#        print t
        tableauxLatex.append(u"\\needspace{6\\baselineskip}")
        tableauxLatex.append(u"\\noindent\n%s %s => %s\\\\"%(t,cfLexs[cat][t],cfRads[cat][t]))
        tableauxLatex.append(reindexTableau(tableaux[cat][t]).to_latex(multirow=True)+u" \\\\ \\medskip")
        tableauxLatex.append("")
print "\n".join(tableauxLatex)

DEF
DEM
IND
PRO
fille
chef
infirmière
louve
peau
livre
lever-n
Clemencia
demande
villageoise
coussin
lumière
chasseuse
obscurité
Violette
table
feu
voleuse
sortilège
mère
lit
chatte
vengeance
serpent
Mahira
Nicole
colère
Elphaba
souffrance
autruche
Katisha
Freja
coyote
côté
bras
disparition
maison
soeur
légume
Agathos
femme
place
harmonie
dégât
hurlement
chat
souris
visage
Hoderi
oeil
homme
Kaleb
proximité
Nabil
robe
marais
combattant
corps
chasseur
poisson
croc
lune
excuse
viande
douleur
jour
tornade
démon
raison
gorge
garçon
loup
nuit
lueur
père
thé
jardin
balai
histoire
forêt
manoir
main
chemin
sorcier
lance
combat
mort
village
maître
dernier-n
milieu
œuf
enfant
bûcher
café
ombre
caillou
cuisine
créature
esprit
coup
plaine
matin
construction
parent
sort
crapaud
blessure
chambre
donjon
nouvelle-n
grimoire
légende
héros
vote
gargouille
fruit
villageois
arbre
cri
dragon
couteau
héroïque
sept
furieux
maigre
profond
différent
nouveau
trois
méchant
rouge
blessé
deux
six
terrible
blanc
quatre
noir
autre
effrayé
petit
gros
nombreux
suivant
cinq
courageux
disparu
jaune
troisième
vilain
grand
treize
dernier
bas
vert
être
acheter
aller
voler
voter
changer
noyer
pleurer-act
entrer
enfermer
mourir
interroger
transformer
tourner-mov
approcher
passer
enlever
nourrir
apporter
arriver
accueillir
survoler
voir
connaître
jardiner
transpercer
pendre
donner
prendre
voler-act
détester
parler
avoir
montrer
pleurer
planter
allumer
arrêter
remercier
chasser-act
brûler-med
boire
compter
inquiéter
hurler
recouvrir
envahir
lever
illustrer
disparaître
partir
présenter
dormir
protéger
retourner
manger
reconstruire
sortir-mov
demander
ressusciter
cacher
embrasser
rejoindre
reconnaître
excuser
fuir
courir
placer
tomber
pousser
chasser-mov
manquer-med
chercher
descendre
surplomber
jeter
échanger
porter
raconter
découvrir
offrir
lancer
brûler
posséder
sauter
dévorer
redevenir
préparer
revenir
nuire
supporter
attraper
faire
rêvasser
vivre
\subsection*{Tableaux de flexion}
\subsubsection*{DET}
\needspace{6\baselineskip}
\noindent
DET IND => la\\
\begin{tabular}{lllll}
\toprule
    & Nombre &        Sg &        Du &        Pl \\
Cas & Genre &           &           &           \\
\midrule
\multirow{3}{*}{Acc} & F &  la-ʃ-a-s &  la-ʃ-a-d &  la-ʃ-a-θ \\
    & M &  la-s-a-s &  la-s-a-d &  la-s-a-θ \\
    & N &  la-ʒ-a-s &  la-ʒ-a-d &  la-ʒ-a-θ \\
\cline{1-5}
\multirow{3}{*}{Dat} & F &  la-ʃ-e-s &  la-ʃ-e-d &  la-ʃ-e-θ \\
    & M &  la-s-e-s &  la-s-e-d &  la-s-e-θ \\
    & N &  la-ʒ-e-s &  la-ʒ-e-d &  la-ʒ-e-θ \\
\cline{1-5}
\multirow{3}{*}{Nom} & F &  la-ʃ-o-s &  la-ʃ-o-d &  la-ʃ-o-θ \\
    & M &  la-s-o-s &  la-s-o-d &  la-s-o-θ \\
    & N &  la-ʒ-o-s &  la-ʒ-o-d &  la-ʒ-o-θ \\
\cline{1-5}
\multirow{3}{*}{Obl} & F &  la-ʃ-i-s &  la-ʃ-i-d &  la-ʃ-i-θ \\
    & M &  la-s-i-s &  la-s-i-d &  la-s-i-θ \\
    & N &  la-ʒ-i-s &  la-ʒ-i-d &  la-ʒ-i-θ \\
\bottomrule
\end{tabular}
 \\ \medskip

\subsubsection*{PRO}
\needspace{6\baselineskip}
\noindent
PRO PRO => ta\\
\begin{tabular}{lllll}
\toprule
    & Nombre &      Sg &        Du &        Pl \\
Cas & Genre &         &           &           \\
\midrule
\multirow{3}{*}{Acc} & F &  ta-s-a &  ta-s-a-m &  ta-s-a-z \\
    & M &  ta-t-a &  ta-t-a-m &  ta-t-a-z \\
    & N &  ta-l-a &  ta-l-a-m &  ta-l-a-z \\
\cline{1-5}
\multirow{3}{*}{Dat} & F &  ta-s-i &  ta-s-i-m &  ta-s-i-z \\
    & M &  ta-t-i &  ta-t-i-m &  ta-t-i-z \\
    & N &  ta-l-i &  ta-l-i-m &  ta-l-i-z \\
\cline{1-5}
\multirow{3}{*}{Nom} & F &  ta-s-u &  ta-s-u-m &  ta-s-u-z \\
    & M &  ta-t-u &  ta-t-u-m &  ta-t-u-z \\
    & N &  ta-l-u &  ta-l-u-m &  ta-l-u-z \\
\cline{1-5}
\multirow{3}{*}{Obl} & F &  ta-s-o &  ta-s-o-m &  ta-s-o-z \\
    & M &  ta-t-o &  ta-t-o-m &  ta-t-o-z \\
    & N &  ta-l-o &  ta-l-o-m &  ta-l-o-z \\
\bottomrule
\end{tabular}
 \\ \medskip

\subsubsection*{NOM}
\needspace{6\baselineskip}
\noindent
NOM couteau => pudoz\\
\begin{tabular}{llll}
\toprule
Nombre &          Sg &          Du &          Pl \\
Cas &             &             &             \\
\midrule
Acc &  ka-pudoz-i &  ka-pudoz-o &  ka-pudoz-a \\
Dat &  da-pudoz-i &  da-pudoz-o &  da-pudoz-a \\
Nom &  no-pudoz-i &  no-pudoz-o &  no-pudoz-a \\
Obl &   pudoz-n-i &   pudoz-n-o &   pudoz-n-a \\
\bottomrule
\end{tabular}
 \\ \medskip

\subsubsection*{ADJ}
\needspace{6\baselineskip}
\noindent
ADJ vert => bogok\\
\begin{tabular}{llll}
\toprule
Nombre &       Sg &         Du &         Pl \\
Genre &          &            &            \\
\midrule
F     &  bogok-a &  bogok-a-s &  bogok-a-b \\
M     &  bogok-o &    bogok-i &    bogok-i \\
N     &  bogok-u &  bogok-u-l &  bogok-u-s \\
\bottomrule
\end{tabular}
 \\ \medskip

\subsubsection*{VER}
\needspace{6\baselineskip}
\noindent
V1 être => nugut\\
\begin{tabular}{lllll}
\toprule
    & Pers &          3Sg &          3Du &          3Pl \\
Temps & Genre &              &              &              \\
\midrule
\multirow{3}{*}{PRS} & F &    nugut-a-p &  nugut-a-p-o &  nugut-a-p-i \\
    & M &    nugut-i-p &  nugut-i-p-o &  nugut-i-p-i \\
    & N &    nugut-u-p &  nugut-u-p-o &  nugut-u-p-i \\
\cline{1-5}
\multirow{3}{*}{PST} & F &  nugut-a-b-o &  nugut-a-b-u &  nugut-a-b-e \\
    & M &  nugut-i-b-o &  nugut-i-b-u &  nugut-i-b-e \\
    & N &  nugut-u-b-o &  nugut-u-b-u &  nugut-u-b-e \\
\bottomrule
\end{tabular}
 \\ \medskip

\needspace{6\baselineskip}
\noindent
V2 illustrer => putuk\\
\begin{tabular}{lllll}
\toprule
    & Pers &          3Sg &          3Du &          3Pl \\
Temps & Genre &              &              &              \\
\midrule
\multirow{3}{*}{PRS} & F &  putuk-a-p-a &  putuk-a-p-e &  putuk-a-p-u \\
    & M &  putuk-o-p-a &  putuk-o-p-e &  putuk-o-p-u \\
    & N &  putuk-u-p-a &  putuk-u-p-e &  putuk-u-p-u \\
\cline{1-5}
\multirow{3}{*}{PST} & F &    putuk-a-r &  putuk-a-r-u &  putuk-a-r-i \\
    & M &    putuk-o-r &  putuk-o-r-u &  putuk-o-r-i \\
    & N &    putuk-u-r &  putuk-u-r-u &  putuk-u-r-i \\
\bottomrule
\end{tabular}
 \\ \medskip

# Liste des lexèmes par CF

=> à intégrer aux tableaux...

In [36]:
cfLatex=[]
cfLatex.append(ur"\subsection*{Classes flexionnelles}")
for cat in "NOM ADJ VER DET".split(" "):
    classeCat=lexemesCF[cat]
    if classeCat:
        if debug: print cat+" : "
        cfLatex.append(cat+" : ")
        if debug: print ur"\begin{description}"
        cfLatex.append(ur"\begin{description}")
        for c in classeCat:
            if debug: print ur"\item[- %s] %s"%(c,", ".join(sorted(classeCat[c])))
            cfLatex.append(ur"\item[- %s] %s"%(c,", ".join(sorted(classeCat[c]))))
        if debug: print ur"\end{description}"
        cfLatex.append(ur"\end{description}")
if len(cfLatex)<2:
    cfLatex=[]
print "\n".join(cfLatex)

\subsection*{Classes flexionnelles}
VER :
\begin{description}
\item[- V1] accueillir, acheter, aller, allumer, apporter, approcher, arriver, arrêter, avoir, boire, brûler-med, changer, chasser-act, compter, connaître, donner, détester, enfermer, enlever, entrer, envahir, hurler, inquiéter, interroger, jardiner, lever, montrer, mourir, nourrir, noyer, parler, passer, pendre, planter, pleurer, pleurer-act, prendre, recouvrir, remercier, survoler, tourner-mov, transformer, transpercer, voir, voler, voler-act, voter, être
\item[- V2] attraper, brûler, cacher, chasser-mov, chercher, courir, demander, descendre, disparaître, dormir, découvrir, dévorer, embrasser, excuser, faire, fuir, illustrer, jeter, lancer, manger, manquer-med, nuire, offrir, partir, placer, porter, posséder, pousser, protéger, préparer, présenter, raconter, reconnaître, reconstruire, redevenir, rejoindre, ressusciter, retourner, revenir, rêvasser, sauter, sortir-mov, supporter, surplomber, tomber, vivre, échanger
\end{description}

# Liste des noms par genre

- on ajoute une colonne genre en coupant dans la matrice de traits
- on fait la liste des genres
- on fait la liste des noms par genre
- on fabrique la structure LaTeX

In [37]:
genresLatex=[]

genresLatex.append(ur"\subsection*{Genre des noms}")

# Ajout de la colonne genre
flexion["genre"]=flexion[bFlex["NOM"]][7].str.extract("Genre=(.+?),")

# Liste des genres
genres=sorted([g for g in flexion["genre"].unique().tolist() if isinstance(g,unicode)])
genreNoms={}

# Liste des noms par genre
for g in genres:
    genreNoms[g]=flexion[flexion.genre==g][1].unique().tolist()

# LaTeX
if debug: print ur"\begin{description}"
genresLatex.append(ur"\begin{description}")
for g in genres:
    if debug: print ur"\item[- %s]"%g, ", ".join(sorted(genreNoms[g]))
    genresLatex.append(ur"\item[- %s] %s"%(g, ", ".join(sorted(genreNoms[g]))))
if debug: print ur"\end{description}"
genresLatex.append(ur"\end{description}")

print "\n".join(genresLatex)

\subsection*{Genre des noms}
\begin{description}
\item[- F] Agathos, Clemencia, Elphaba, Freja, Katisha, Mahira, Nicole, Violette, autruche, bras, chasseuse, chatte, chef, colère, coussin, coyote, côté, demande, disparition, femme, feu, fille, infirmière, lever-n, lit, livre, louve, lumière, légume, maison, mère, obscurité, peau, place, serpent, soeur, sortilège, souffrance, table, vengeance, villageoise, voleuse
\item[- M] Hoderi, Kaleb, Nabil, balai, chasseur, chat, combattant, corps, croc, douleur, dégât, démon, excuse, forêt, garçon, gorge, harmonie, histoire, homme, hurlement, jardin, jour, loup, lueur, lune, marais, nuit, oeil, poisson, proximité, père, raison, robe, souris, thé, tornade, viande, visage
\item[- N] arbre, blessure, bûcher, café, caillou, chambre, chemin, combat, construction, coup, couteau, crapaud, cri, créature, cuisine, dernier-n, donjon, dragon, enfant, esprit, fruit, gargouille, grimoire, héros, lance, loup, légende, main, manoir, matin, maître, milieu, mort, nouvelle-n, ombre, parent, plaine, sorcier, sort, village, villageois, vote, œuf
\end{description}

# Calcul des remplissages de paradigmes
- filledCells contient les informations exportées par Phrases2
- sortLevel permet de mettre les noms des traits dans l'ordre logique
- filledTable fait le tableau du remplissage pour une catégorie avec un pivot_table
    - on lui passe 
        - le filledCells de la catégorie
        - la colonne du lexème
        - les colonnes qu'on veut mettre en ligne dans le tableau du paradigme
        - les colonnes qu'on veut mettre en colonnes dans le tableau du paradigme

In [38]:
with open(serie+"FilledCells.yaml", 'r') as stream:
    filledCells=yaml.safe_load(stream)
filledCells["VER"]=[v.replace(".Trois",".3") for v in filledCells["VER"]]
filledCells

{'ADJ': [u'diff\xe9rent.M.SG',
  'noir.M.SG',
  'maigre.F.PL',
  'autre.F.PL',
  'terrible.M.PL',
  'petit.N.PL',
  'gros.M.SG',
  'furieux.N.PL',
  'quatre.M.PL',
  'profond.M.SG',
  'jaune.N.DU',
  'courageux.F.PL',
  'maigre.M.PL',
  'noir.M.PL',
  'jaune.M.DU',
  u'bless\xe9.M.SG',
  'jaune.F.DU',
  'petit.N.SG',
  u'diff\xe9rent.N.SG',
  'gros.F.DU',
  'courageux.M.PL',
  'trois.M.PL',
  'blanc.N.DU',
  'blanc.F.DU',
  'gros.F.SG',
  'maigre.M.SG',
  'noir.F.SG',
  'profond.F.SG',
  'courageux.F.SG',
  'grand.N.SG',
  'petit.F.SG',
  'suivant.N.SG',
  u'effray\xe9.F.DU',
  u'diff\xe9rent.F.DU',
  'terrible.F.DU',
  'courageux.N.DU',
  'vert.F.SG',
  'grand.M.SG',
  'terrible.N.PL',
  'profond.N.SG',
  'blanc.M.PL',
  'grand.M.DU',
  'terrible.N.SG',
  'noir.N.DU',
  'maigre.F.DU',
  'rouge.N.PL',
  'gros.M.DU',
  'grand.N.DU',
  'grand.F.SG',
  'petit.M.PL',
  'petit.F.DU',
  'nombreux.F.PL',
  'autre.N.PL',
  'petit.F.PL',
  'furieux.M.SG',
  u'bless\xe9.N.PL',
  u'effray\xe9.F.SG',
  'noir.N.SG',
  'blanc.N.PL',
  'rouge.N.SG',
  'courageux.M.DU',
  'jaune.F.SG',
  'jaune.M.PL',
  'terrible.M.DU',
  'gros.F.PL',
  'vert.M.SG',
  'blanc.F.PL',
  'petit.M.SG',
  'rouge.F.PL',
  u'effray\xe9.M.PL',
  'terrible.M.SG',
  'suivant.M.SG',
  'rouge.M.SG',
  'bas.F.SG',
  'noir.M.DU',
  'furieux.N.SG',
  'suivant.N.PL',
  'quatre.N.PL',
  'maigre.M.DU',
  'jaune.M.SG',
  'rouge.M.DU',
  'profond.N.PL',
  'disparu.N.SG',
  'noir.N.PL',
  'quatre.F.PL',
  'rouge.N.DU',
  'rouge.F.SG',
  u'diff\xe9rent.N.PL',
  u'effray\xe9.N.PL',
  'blanc.F.SG',
  u'effray\xe9.F.PL',
  'rouge.M.PL',
  'suivant.M.DU',
  u'bless\xe9.F.SG',
  u'bless\xe9.M.DU',
  'grand.F.PL',
  u'effray\xe9.M.DU',
  u'effray\xe9.N.SG',
  'petit.N.DU',
  'gros.M.PL',
  'grand.N.PL',
  'jaune.N.PL',
  'noir.F.PL',
  'petit.M.DU',
  'blanc.M.DU',
  'trois.F.PL',
  'vert.N.PL',
  'blanc.M.SG',
  'courageux.M.SG',
  'grand.M.PL'],
 'DET': ['DEF.N.SG.Nom',
  'DEM.M.DU.obl',
  'DEF.F.SG.Acc',
  'DEF.N.SG.Dat',
  'DEM.N.DU.obl',
  'DEF.N.DU.Dat',
  'DEM.M.SG.Nom',
  'DEF.N.PL.obl',
  'DEM.N.DU.Acc',
  'DEF.N.SG.Acc',
  'DEM.F.DU.Nom',
  'DEM.M.SG.Acc',
  'DEF.M.SG.Dat',
  'DEM.F.SG.obl',
  'DEM.N.DU.Dat',
  'IND.F.PL.obl',
  'DEF.M.DU.obl',
  'IND.F.DU.Acc',
  'DEM.F.DU.Acc',
  'DEM.N.DU.Nom',
  'DEF.F.PL.obl',
  'DEM.M.PL.Nom',
  'IND.M.DU.Acc',
  'DEM.N.SG.Acc',
  'DEF.M.SG.obl',
  'IND.N.PL.Nom',
  'DEM.M.DU.Acc',
  'IND.N.SG.obl',
  'DEF.M.DU.Nom',
  'DEM.F.PL.Dat',
  'DEF.F.DU.Nom',
  'DEF.M.SG.Nom',
  'DEF.M.SG.Acc',
  'IND.N.DU.obl',
  'DEF.N.PL.Acc',
  'DEF.F.PL.Nom',
  'DEM.F.PL.Nom',
  'DEF.M.PL.Dat',
  'DEM.N.SG.Nom',
  'DEF.F.DU.Dat',
  'DEM.F.SG.Acc',
  'IND.M.SG.Dat',
  'IND.N.DU.Nom',
  'DEF.N.SG.obl',
  'DEF.F.SG.Nom',
  'DEM.N.SG.obl',
  'IND.M.PL.Acc',
  'DEM.F.DU.obl',
  'IND.M.DU.obl',
  'DEM.N.PL.Acc',
  'IND.N.SG.Nom',
  'IND.F.SG.obl',
  'DEM.M.PL.Acc',
  'IND.N.SG.Acc',
  'DEF.N.DU.Acc',
  'DEF.F.SG.Dat',
  'DEM.F.PL.obl',
  'DEM.N.PL.Nom',
  'DEM.F.DU.Dat',
  'DEF.M.DU.Acc',
  'IND.N.DU.Acc',
  'DEM.M.SG.obl',
  'DEF.F.DU.obl',
  'IND.F.SG.Nom',
  'DEF.N.PL.Dat',
  'DEM.F.SG.Nom',
  'IND.M.SG.Acc',
  'DEF.M.PL.Acc',
  'DEF.M.PL.obl',
  'DEF.F.SG.obl',
  'DEM.M.PL.Dat',
  'DEF.N.DU.Nom',
  'DEF.N.PL.Nom',
  'IND.F.DU.Nom',
  'IND.M.SG.Nom',
  'DEM.M.SG.Dat',
  'IND.M.PL.Nom',
  'DEF.N.DU.obl',
  'IND.F.DU.Dat',
  'DEF.M.DU.Dat',
  'DEF.F.PL.Acc',
  'IND.F.DU.obl',
  'DEM.N.PL.obl',
  'IND.M.PL.Dat',
  'IND.N.PL.obl',
  'IND.N.PL.Acc',
  'IND.M.SG.obl',
  'IND.F.PL.Acc',
  'DEF.M.PL.Nom',
  'IND.F.PL.Nom',
  'IND.N.PL.Dat',
  'DEF.F.PL.Dat',
  'IND.F.SG.Dat',
  'IND.M.DU.Nom',
  'DEF.F.DU.Acc',
  'IND.M.PL.obl',
  'DEM.M.DU.Nom',
  'IND.F.SG.Acc'],
 'NOM': ['balai.M.Pl.Nom',
  'lit.F.Sg.Obl',
  'blessure.N.Sg.Acc',
  'chat.M.Pl.Acc',
  'louve.F.Sg.Nom',
  'lit.F.Pl.Nom',
  'Violette.F.Sg.Acc',
  'milieu.N.Pl.Obl',
  'Mahira.F.Sg.Dat',
  'enfant.N.Pl.Nom',
  'blessure.N.Sg.Dat',
  'fruit.N.Du.Nom',
  'table.F.Sg.Obl',
  'gorge.M.Sg.Nom',
  u'l\xe9gume.F.Pl.Acc',
  'chat.M.Sg.Obl',
  'souris.M.Sg.Dat',
  u'infirmi\xe8re.F.Pl.Obl',
  'coussin.F.Sg.Nom',
  'fille.F.Du.Nom',
  'villageois.N.Pl.Nom',
  u'infirmi\xe8re.F.Du.Obl',
  u'th\xe9.M.Sg.Nom',
  'Katisha.F.Sg.Obl',
  'nuit.M.Sg.Obl',
  'Agathos.F.Pl.Obl',
  'lance.N.Sg.Nom',
  'serpent.F.Sg.Nom',
  'chambre.N.Pl.Obl',
  'chasseur.M.Du.Dat',
  'arbre.N.Du.Obl',
  'dragon.N.Sg.Obl',
  'sort.N.Du.Nom',
  'coyote.F.Sg.Acc',
  'lueur.M.Pl.Obl',
  'viande.M.Du.Acc',
  'Agathos.F.Sg.Obl',
  'fille.F.Sg.Acc',
  'souris.M.Du.Acc',
  'lueur.M.Sg.Acc',
  'Katisha.F.Sg.Dat',
  'Mahira.F.Sg.Nom',
  'chasseur.M.Du.Obl',
  'chasseur.M.Du.Acc',
  'arbre.N.Sg.Obl',
  'autruche.F.Sg.Acc',
  'enfant.N.Pl.Dat',
  'combattant.M.Du.Obl',
  'coyote.F.Du.Nom',
  'souris.M.Du.Nom',
  'main.N.Pl.Obl',
  'combattant.M.Pl.Dat',
  'enfant.N.Pl.Obl',
  'fruit.N.Pl.Acc',
  'visage.M.Pl.Acc',
  'autruche.F.Sg.Nom',
  'villageoise.F.Pl.Nom',
  'ombre.N.Du.Dat',
  'visage.M.Sg.Acc',
  'combat.N.Pl.Nom',
  'chef.F.Sg.Obl',
  'gorge.M.Pl.Obl',
  'plaine.N.Sg.Obl',
  'cri.N.Pl.Nom',
  'maison.F.Sg.Acc',
  'village.N.Sg.Nom',
  'chasseur.M.Pl.Nom',
  'loup.M.Sg.Dat',
  'corps.M.Sg.Obl',
  'villageois.N.Pl.Obl',
  'fille.F.Du.Obl',
  u'infirmi\xe8re.F.Du.Nom',
  'loup.M.Sg.Nom',
  u'caf\xe9.N.Du.Nom',
  'souffrance.F.Sg.Nom',
  'village.N.Sg.Acc',
  'milieu.N.Sg.Obl',
  u'gar\xe7on.M.Sg.Dat',
  'villageois.N.Sg.Obl',
  'enfant.N.Sg.Obl',
  'crapaud.N.Pl.Acc',
  'sorcier.N.Pl.Acc',
  'chambre.N.Pl.Nom',
  u'for\xeat.M.Sg.Acc',
  'chat.M.Du.Nom',
  'chasseur.M.Sg.Nom',
  'maison.F.Pl.Obl',
  'souris.M.Pl.Acc',
  'couteau.N.Sg.Acc',
  u'gar\xe7on.M.Pl.Nom',
  'blessure.N.Pl.Nom',
  u'\u0153uf.N.Du.Acc',
  'coyote.F.Sg.Nom',
  u'th\xe9.M.Pl.Acc',
  'chasseur.M.Du.Nom',
  'enfant.N.Du.Dat',
  'autruche.F.Du.Acc',
  'coyote.F.Sg.Dat',
  'loup.hyper.N.Pl.Obl',
  'poisson.M.Sg.Nom',
  'coup.N.Du.Nom',
  'marais.M.Pl.Obl',
  u'lumi\xe8re.F.Sg.Obl',
  'feu.F.Sg.Obl',
  'excuse.M.Pl.Acc',
  'autruche.F.Pl.Acc',
  'croc.M.Sg.Acc',
  'chat.M.Pl.Dat',
  'combattant.M.Du.Nom',
  u'col\xe8re.F.Sg.Nom',
  'cri.N.Pl.Obl',
  'chef.F.Sg.Nom',
  'Kaleb.M.Pl.Acc',
  'chasseur.M.Pl.Obl',
  'fille.F.Pl.Obl',
  'loup.M.Pl.Nom',
  'arbre.N.Pl.Nom',
  'enfant.N.Du.Obl',
  'tornade.M.Sg.Obl',
  u'\u0153uf.N.Sg.Acc',
  'chasseur.M.Sg.Obl',
  'Violette.F.Sg.Nom',
  'serpent.F.Du.Nom',
  u'\u0153uf.N.Du.Obl',
  'Kaleb.M.Sg.Nom',
  u'th\xe9.M.Pl.Nom',
  'fille.F.Pl.Acc',
  'villageois.N.Du.Dat',
  'loup.M.Pl.Obl',
  'cri.N.Sg.Obl',
  u'd\xe9mon.M.Sg.Nom',
  'lueur.M.Pl.Nom',
  'arbre.N.Pl.Obl',
  'fille.F.Du.Dat',
  'souris.M.Sg.Nom',
  'villageois.N.Pl.Dat',
  u'\u0153uf.N.Pl.Acc',
  'combattant.M.Sg.Nom',
  'coup.N.Pl.Nom',
  'maison.F.Sg.Obl',
  'ombre.N.Sg.Obl',
  'chat.M.Pl.Nom',
  'coyote.F.Du.Acc',
  'combattant.M.Sg.Acc',
  'histoire.M.Sg.Obl',
  'coussin.F.Du.Acc',
  'lueur.M.Sg.Nom',
  'balai.M.Pl.Acc',
  u'col\xe8re.F.Sg.Acc',
  'serpent.F.Pl.Nom',
  'mort.N.Sg.Dat',
  'poisson.M.Sg.Obl',
  'chambre.N.Du.Obl',
  'croc.M.Pl.Acc',
  'chef.F.Sg.Dat',
  'coyote.F.Pl.Acc',
  u'gar\xe7on.M.Du.Obl',
  'main.N.Du.Obl',
  'plaine.N.Pl.Obl',
  'lance.N.Du.Acc',
  u'sortil\xe8ge.F.Sg.Nom',
  'villageoise.F.Pl.Obl',
  'Nabil.M.Sg.Nom',
  'mort.N.Sg.Obl',
  'mort.N.Sg.Acc',
  'sorcier.N.Pl.Nom',
  'soeur.F.Sg.Acc',
  'soeur.F.Sg.Obl',
  'sorcier.N.Pl.Dat',
  'croc.M.Du.Nom',
  'village.N.Sg.Dat',
  u'c\xf4t\xe9.F.Sg.Obl',
  'main.N.Sg.Acc',
  'lit.F.Pl.Acc',
  'souffrance.F.Pl.Nom',
  'arbre.N.Sg.Nom',
  'coussin.F.Sg.Obl',
  'sort.N.Pl.Nom',
  'arbre.N.Sg.Acc',
  'village.N.Sg.Obl',
  u'th\xe9.M.Sg.Acc',
  'mort.N.Pl.Dat',
  'Nicole.F.Sg.Nom',
  'corps.M.Du.Acc',
  'chat.M.Sg.Acc',
  'poisson.M.Du.Acc',
  'loup.M.Du.Acc',
  u'd\xe9mon.M.Pl.Acc',
  'lueur.M.Du.Nom',
  'voleuse.F.Pl.Acc',
  u'col\xe8re.F.Du.Nom',
  'cuisine.N.Sg.Obl',
  'lance.N.Du.Obl',
  'Katisha.F.Sg.Nom',
  'lance.N.Du.Nom',
  'lune.M.Du.Acc',
  'lance.N.Sg.Acc',
  'croc.M.Du.Obl',
  'ombre.N.Sg.Acc',
  u'caf\xe9.N.Sg.Acc',
  'sort.N.Sg.Obl',
  'corps.M.Sg.Nom',
  'chatte.F.Du.Obl',
  u'gar\xe7on.M.Sg.Nom',
  'loup.M.Sg.Obl',
  'fille.F.Pl.Dat',
  'coup.N.Sg.Acc',
  'fruit.N.Pl.Nom',
  'mort.N.Sg.Nom',
  'livre.F.Sg.Acc',
  'soeur.F.Sg.Nom',
  'cri.N.Sg.Acc',
  'vengeance.F.Sg.Obl',
  'homme.M.Sg.Obl',
  'loup.M.Pl.Acc',
  'couteau.N.Du.Dat',
  u'cr\xe9ature.N.Pl.Obl',
  u'd\xe9mon.M.Pl.Nom',
  'enfant.N.Du.Nom',
  'table.F.Sg.Acc',
  'souffrance.F.Sg.Acc',
  'chasseur.M.Pl.Dat',
  'villageois.N.Sg.Nom',
  'corps.M.Sg.Acc',
  'crapaud.N.Pl.Nom',
  'coussin.F.Pl.Obl',
  u'infirmi\xe8re.F.Pl.Nom',
  'souris.M.Pl.Nom',
  'Mahira.F.Sg.Acc',
  'enfant.N.Pl.Acc',
  'chatte.F.Sg.Obl',
  'nuit.M.Sg.Nom',
  'souffrance.F.Du.Obl',
  u'\u0153uf.N.Pl.Nom',
  'main.N.Sg.Obl',
  'viande.M.Pl.Acc',
  'ombre.N.Sg.Nom',
  'autruche.F.Pl.Obl',
  'arbre.N.Du.Nom',
  'loup.hyper.N.Pl.Dat',
  'coussin.F.Pl.Nom',
  'mort.N.Pl.Acc',
  'lance.N.Sg.Dat',
  'visage.M.Du.Obl',
  'nuit.M.Du.Acc',
  'serpent.F.Pl.Obl',
  'lune.M.Sg.Acc',
  'villageoise.F.Du.Nom',
  'maison.F.Du.Obl',
  'chatte.F.Du.Dat',
  u'l\xe9gume.F.Pl.Obl',
  'nuit.M.Pl.Nom',
  'autruche.F.Sg.Dat',
  'Kaleb.M.Pl.Nom',
  'loup.hyper.N.Pl.Nom',
  u'\u0153uf.N.Sg.Nom',
  'combat.N.Sg.Obl',
  'voleuse.F.Pl.Dat',
  'fille.F.Sg.Obl',
  'lance.N.Sg.Obl',
  'combattant.M.Pl.Nom',
  'homme.M.Pl.Obl',
  u'sortil\xe8ge.F.Sg.Acc',
  'peau.F.Sg.Acc',
  'chat.M.Du.Acc',
  u'gar\xe7on.M.Sg.Acc',
  'cri.N.Du.Nom',
  'loup.hyper.N.Pl.Acc',
  'louve.F.Sg.Acc',
  'villageois.N.Sg.Dat',
  'village.N.Du.Nom',
  'table.F.Du.Obl',
  'gorge.M.Sg.Acc',
  'croc.M.Pl.Nom',
  u'd\xe9mon.M.Sg.Acc',
  u'd\xe9mon.M.Sg.Obl',
  'chat.M.Du.Obl',
  u'd\xe9mon.M.Du.Obl',
  u'\u0153uf.N.Du.Nom',
  'sorcier.N.Sg.Acc',
  'cri.N.Pl.Acc',
  u'for\xeat.M.Sg.Nom',
  'couteau.N.Sg.Nom',
  'homme.M.Pl.Nom',
  'lit.F.Sg.Nom',
  'serpent.F.Sg.Dat',
  'village.N.Pl.Dat',
  'chambre.N.Sg.Obl',
  'Nicole.F.Sg.Dat',
  'villageoise.F.Sg.Nom',
  'manoir.N.Sg.Obl',
  'autruche.F.Du.Nom',
  'combat.N.Sg.Nom',
  'souris.M.Pl.Obl',
  'histoire.M.Pl.Obl',
  'combattant.M.Sg.Obl',
  'table.F.Du.Nom',
  'chef.F.Pl.Dat',
  'villageoise.F.Sg.Acc',
  'villageoise.F.Du.Acc',
  'gorge.M.Sg.Obl',
  u'for\xeat.M.Sg.Obl',
  'viande.M.Pl.Obl',
  'lueur.M.Sg.Obl',
  'lune.M.Sg.Nom',
  'arbre.N.Pl.Acc',
  'Nicole.F.Sg.Obl',
  'couteau.N.Sg.Obl',
  'Mahira.F.Sg.Obl',
  'Nabil.M.Sg.Dat',
  'couteau.N.Du.Nom',
  'balai.M.Pl.Obl',
  'balai.M.Sg.Acc',
  'coussin.F.Pl.Acc',
  'cri.N.Sg.Nom',
  'villageois.N.Du.Nom',
  'Violette.F.Sg.Obl',
  u'd\xe9mon.M.Sg.Dat',
  'Kaleb.M.Pl.Obl',
  'serpent.F.Sg.Acc',
  u'infirmi\xe8re.F.Sg.Acc',
  'souris.M.Sg.Acc',
  'autruche.F.Sg.Obl',
  'louve.F.Du.Nom',
  'combattant.M.Pl.Obl',
  'main.N.Pl.Acc',
  'Agathos.F.Sg.Acc',
  'grimoire.N.Sg.Obl',
  'voleuse.F.Pl.Nom',
  'soeur.F.Pl.Acc',
  'souris.M.Sg.Obl',
  'sort.N.Sg.Nom',
  'nuit.M.Du.Nom',
  'Kaleb.M.Sg.Obl',
  u'caf\xe9.N.Du.Acc',
  'louve.F.Sg.Dat',
  u'd\xe9mon.M.Pl.Obl',
  'lune.M.Sg.Obl',
  'grimoire.N.Sg.Acc',
  'combat.N.Pl.Acc',
  'ombre.N.Pl.Acc',
  'blessure.N.Sg.Nom',
  u'gar\xe7on.M.Du.Nom',
  'poisson.M.Sg.Acc',
  'Nabil.M.Sg.Obl',
  'Kaleb.M.Sg.Dat',
  'table.F.Sg.Nom',
  'chatte.F.Sg.Nom',
  u'col\xe8re.F.Pl.Obl',
  'lune.M.Pl.Obl',
  'coyote.F.Pl.Nom',
  u'infirmi\xe8re.F.Sg.Obl',
  'main.N.Du.Nom',
  'poisson.M.Pl.Nom',
  'coyote.F.Pl.Dat',
  'croc.M.Pl.Obl',
  u'gar\xe7on.M.Pl.Obl',
  'Violette.F.Du.Obl',
  'loup.M.Du.Nom',
  'sorcier.N.Sg.Obl',
  'sort.N.Sg.Acc',
  'main.N.Pl.Nom',
  'villageois.N.Sg.Acc',
  'fille.F.Sg.Dat',
  u'infirmi\xe8re.F.Pl.Dat',
  'Mahira.F.Du.Nom',
  u'infirmi\xe8re.F.Sg.Dat',
  'cuisine.N.Sg.Acc',
  'loup.M.Sg.Acc',
  u'caf\xe9.N.Pl.Acc',
  'esprit.N.Pl.Obl',
  'corps.M.Du.Nom',
  'chat.M.Sg.Nom',
  'lance.N.Pl.Acc',
  'lit.F.Sg.Acc',
  'chat.M.Sg.Dat',
  'homme.M.Sg.Nom',
  'chef.F.Sg.Acc',
  'sort.N.Pl.Acc',
  'viande.M.Sg.Nom',
  u'for\xeat.M.Pl.Nom',
  'louve.F.Sg.Obl',
  'viande.M.Sg.Acc',
  'chatte.F.Pl.Nom',
  'corps.M.Sg.Dat',
  'poisson.M.Pl.Acc',
  'loup.M.Du.Dat',
  'coyote.F.Pl.Obl',
  'villageois.N.Pl.Acc',
  'croc.M.Sg.Nom',
  'livre.F.Pl.Nom',
  'autruche.F.Pl.Nom',
  'fille.F.Sg.Nom',
  'table.F.Pl.Obl',
  'fille.F.Pl.Nom',
  'autruche.F.Pl.Dat',
  'couteau.N.Pl.Obl',
  'fille.F.Du.Acc'],
 'PRO': ['PRO.M.Pl.Nom',
  'PRO.N.Pl.Nom',
  'PRO.F.Sg.Nom',
  'PRO.F.Pl.Nom',
  'PRO.M.Sg.Nom',
  'PRO.N.Du.Nom'],
 'VER': ['lancer.V2.Pst.3Sg.M',
  'sortir-Mov.V2.Pst.3Pl.N',
  'prendre.V1.Pst.3Pl.N',
  'dormir.V2.Pst.3Du.M',
  'voir.V1.Pst.3Sg.F',
  'montrer.V1.Prs.3Sg.F',
  'rejoindre.V2.Prs.3Pl.M',
  'apporter.V1.Pst.3Pl.N',
  'apporter.V1.Pst.3Pl.M',
  'arriver.V1.Prs.3Du.F',
  'dormir.V2.Prs.3Pl.M',
  'courir.V2.Pst.3Du.N',
  'arriver.V1.Prs.3Du.M',
  'parler.V1.Pst.3Sg.F',
  'arriver.V1.Prs.3Du.N',
  'entrer.V1.Prs.3Sg.F',
  'dormir.V2.Prs.3Sg.F',
  u'pr\xe9senter.V2.Pst.3Sg.N',
  u'dispara\xeetre.V2.Prs.3Pl.N',
  'transformer.V1.Pst.3Sg.F',
  'prendre.V1.Prs.3Sg.N',
  'prendre.V1.Prs.3Sg.M',
  'apporter.V1.Prs.3Sg.F',
  'transformer.V1.Pst.3Sg.N',
  'prendre.V1.Prs.3Sg.F',
  'entrer.V1.Prs.3Sg.M',
  'apporter.V1.Pst.3Sg.M',
  'offrir.V2.Prs.3Du.M',
  'dormir.V2.Prs.3Pl.F',
  'lancer.V2.Pst.3Sg.F',
  'tomber.V2.Prs.3Pl.N',
  'tomber.V2.Pst.3Sg.N',
  'tomber.V2.Prs.3Pl.M',
  'parler.V1.Prs.3Pl.N',
  u'dispara\xeetre.V2.Prs.3Du.M',
  'arriver.V1.Pst.3Pl.F',
  'jeter.V2.Prs.3Pl.M',
  'tomber.V2.Prs.3Pl.F',
  'supporter.V2.Pst.3Sg.F',
  'tomber.V2.Prs.3Sg.M',
  'tomber.V2.Prs.3Sg.N',
  'acheter.V1.Prs.3Sg.M',
  'boire.V1.Prs.3Sg.F',
  u'dispara\xeetre.V2.Pst.3Sg.F',
  'tomber.V2.Prs.3Sg.F',
  'recouvrir.V1.Prs.3Sg.M',
  u'dispara\xeetre.V2.Prs.3Sg.N',
  u'dispara\xeetre.V2.Prs.3Sg.M',
  u'\xeatre.V1.Prs.3Sg.F',
  'dormir.V2.Pst.3Pl.F',
  'passer.V1.Pst.3Du.M',
  'lancer.V2.Prs.3Sg.M',
  'parler.V1.Prs.3Sg.M',
  'tomber.V2.Pst.3Sg.F',
  'supporter.V2.Pst.3Du.M',
  'tomber.V2.Pst.3Sg.M',
  'parler.V1.Prs.3Sg.F',
  'acheter.V1.Pst.3Pl.F',
  'boire.V1.Prs.3Du.F',
  'boire.V1.Pst.3Pl.M',
  'arriver.V1.Pst.3Sg.F',
  'tomber.V2.Prs.3Du.N',
  'chasser-Act.V1.Prs.3Sg.M',
  'lancer.V2.Prs.3Sg.F',
  'boire.V1.Prs.3Du.M',
  'donner.V1.Pst.3Sg.M',
  'envahir.V1.Pst.3Sg.M',
  'arriver.V1.Prs.3Pl.N',
  'parler.V1.Pst.3Du.F',
  'planter.V1.Pst.3Du.F',
  u'd\xe9vorer.V2.Prs.3Pl.N',
  'boire.V1.Prs.3Sg.M',
  'chercher.V2.Prs.3Sg.N',
  'boire.V1.Pst.3Pl.F',
  'accueillir.V1.Pst.3Sg.F',
  u'd\xe9vorer.V2.Prs.3Sg.F',
  u'\xeatre.V1.Pst.3Sg.N',
  'chasser-Act.V1.Pst.3Sg.F',
  'chasser-Act.V1.Pst.3Sg.N',
  'chasser-Act.V1.Pst.3Sg.M',
  'fuir.V2.Prs.3Pl.M',
  'boire.V1.Pst.3Du.M',
  'chercher.V2.Pst.3Pl.F',
  'arriver.V1.Prs.3Sg.F',
  u'prot\xe9ger.V2.Prs.3Pl.F',
  'voir.V1.Pst.3Du.F',
  'manger.V2.Pst.3Du.F',
  'tomber.V2.Pst.3Du.N',
  'donner.V1.Prs.3Pl.M',
  'arriver.V1.Prs.3Sg.M',
  'acheter.V1.Prs.3Pl.M',
  'supporter.V2.Prs.3Du.N',
  'chasser-Act.V1.Pst.3Du.F',
  'avoir.V1.Pst.3Pl.F',
  'recouvrir.V1.Prs.3Pl.M',
  'acheter.V1.Prs.3Pl.F',
  'chasser-Act.V1.Prs.3Du.F',
  'aller.V1.Prs.3Pl.M',
  'chasser-Act.V1.Pst.3Pl.F',
  'aller.V1.Prs.3Pl.N',
  'fuir.V2.Pst.3Sg.M',
  'transpercer.V1.Prs.3Sg.M',
  'transpercer.V1.Prs.3Sg.N',
  'fuir.V2.Pst.3Sg.F',
  'montrer.V1.Prs.3Du.M',
  'sauter.V2.Prs.3Sg.F',
  'montrer.V1.Prs.3Pl.F',
  u'\xeatre.V1.Prs.3Pl.N',
  'supporter.V2.Prs.3Du.F',
  'offrir.V2.Prs.3Pl.F',
  'voir.V1.Pst.3Du.N',
  u'br\xfbler-Med.V1.Pst.3Sg.M',
  'sauter.V2.Prs.3Sg.M',
  'attraper.V2.Pst.3Du.N',
  'arriver.V1.Prs.3Pl.F',
  'supporter.V2.Prs.3Du.M',
  u'd\xe9vorer.V2.Pst.3Pl.N',
  'courir.V2.Prs.3Sg.F',
  'entrer.V1.Prs.3Du.N',
  u'dispara\xeetre.V2.Pst.3Du.N',
  'jeter.V2.Prs.3Sg.F',
  'transpercer.V1.Prs.3Pl.M',
  'approcher.V1.Pst.3Du.M',
  'courir.V2.Prs.3Sg.M',
  u'd\xe9couvrir.V2.Pst.3Pl.F',
  'jeter.V2.Prs.3Sg.M',
  'jeter.V2.Prs.3Sg.N',
  'passer.V1.Prs.3Pl.M',
  'pousser.V2.Prs.3Sg.F',
  'arriver.V1.Pst.3Du.F',
  u'\xe9changer.V2.Pst.3Pl.N',
  'approcher.V1.Prs.3Sg.N',
  'approcher.V1.Prs.3Sg.M',
  'arriver.V1.Prs.3Pl.M',
  'cacher.V2.Pst.3Pl.F',
  'enlever.V1.Pst.3Sg.F',
  'supporter.V2.Pst.3Pl.M',
  'donner.V1.Prs.3Sg.M',
  'donner.V1.Prs.3Sg.N',
  'transpercer.V1.Prs.3Du.N',
  'donner.V1.Pst.3Pl.M',
  'approcher.V1.Prs.3Sg.F',
  'parler.V1.Pst.3Sg.M',
  'donner.V1.Prs.3Sg.F',
  'chercher.V2.Prs.3Sg.F',
  'offrir.V2.Pst.3Du.F',
  'fuir.V2.Prs.3Sg.F',
  'recouvrir.V1.Pst.3Sg.N',
  'envahir.V1.Prs.3Du.M',
  u'prot\xe9ger.V2.Prs.3Sg.F',
  'sauter.V2.Prs.3Du.F',
  'fuir.V2.Prs.3Sg.N',
  'acheter.V1.Pst.3Du.M',
  u'prot\xe9ger.V2.Prs.3Sg.N',
  u'prot\xe9ger.V2.Pst.3Sg.M',
  'pousser.V2.Pst.3Pl.N',
  'fuir.V2.Pst.3Pl.N',
  'donner.V1.Prs.3Du.M',
  'courir.V2.Prs.3Du.F',
  'sortir-Mov.V2.Pst.3Sg.F',
  'fuir.V2.Pst.3Pl.F',
  'changer.V1.Pst.3Pl.M',
  'planter.V1.Prs.3Sg.N',
  'planter.V1.Prs.3Sg.M',
  'boire.V1.Pst.3Sg.M',
  'aller.V1.Pst.3Sg.F',
  u'r\xeavasser.V2.Prs.3Pl.M',
  'planter.V1.Prs.3Sg.F',
  'envahir.V1.Pst.3Pl.M',
  'fuir.V2.Pst.3Du.N',
  'pousser.V2.Prs.3Pl.N',
  'lancer.V2.Prs.3Du.M',
  'approcher.V1.Pst.3Sg.M',
  'montrer.V1.Pst.3Du.M',
  'sortir-Mov.V2.Prs.3Sg.F',
  u'd\xe9vorer.V2.Pst.3Du.N',
  'envahir.V1.Prs.3Sg.F',
  'chercher.V2.Pst.3Du.F',
  'redevenir.V2.Pst.3Pl.N',
  'donner.V1.Prs.3Du.F',
  'chasser-Act.V1.Prs.3Du.M',
  'rejoindre.V2.Pst.3Pl.N',
  'fuir.V2.Prs.3Du.F',
  'pousser.V2.Prs.3Sg.M',
  'donner.V1.Pst.3Du.M',
  'jeter.V2.Pst.3Pl.N',
  'lancer.V2.Pst.3Du.M',
  'prendre.V1.Prs.3Du.N',
  'rejoindre.V2.Prs.3Sg.F',
  'offrir.V2.Pst.3Sg.M',
  u'prot\xe9ger.V2.Pst.3Sg.F',
  'lancer.V2.Prs.3Pl.F',
  u'dispara\xeetre.V2.Pst.3Sg.M',
  'rejoindre.V2.Prs.3Sg.M',
  'tomber.V2.Pst.3Pl.N',
  u'd\xe9vorer.V2.Pst.3Sg.M',
  'manger.V2.Prs.3Pl.F',
  'montrer.V1.Pst.3Pl.M',
  'manger.V2.Prs.3Pl.M',
  'acheter.V1.Prs.3Du.F',
  'montrer.V1.Pst.3Du.F',
  'prendre.V1.Prs.3Pl.M',
  'manger.V2.Prs.3Sg.F',
  'aller.V1.Prs.3Sg.M',
  'voir.V1.Pst.3Pl.M',
  'transformer.V1.Prs.3Sg.N',
  'transformer.V1.Prs.3Sg.M',
  'donner.V1.Pst.3Pl.F',
  'aller.V1.Prs.3Sg.F',
  'manger.V2.Prs.3Sg.M',
  'chasser-Act.V1.Prs.3Pl.N',
  'apporter.V1.Prs.3Pl.N',
  'apporter.V1.Prs.3Pl.M',
  'supporter.V2.Prs.3Sg.F',
  'entrer.V1.Pst.3Pl.N',
  'lancer.V2.Pst.3Pl.N',
  'entrer.V1.Pst.3Pl.F',
  'dormir.V2.Prs.3Du.M',
  u'poss\xe9der.V2.Pst.3Pl.M',
  'passer.V1.Pst.3Pl.M',
  'donner.V1.Prs.3Pl.N',
  'rejoindre.V2.Prs.3Du.N',
  'apporter.V1.Pst.3Du.F',
  'dormir.V2.Prs.3Du.F',
  'donner.V1.Prs.3Pl.F',
  'lancer.V2.Pst.3Pl.F',
  'voir.V1.Prs.3Sg.F',
  'chasser-Act.V1.Prs.3Pl.F',
  'supporter.V2.Prs.3Pl.F',
  u'\xeatre.V1.Pst.3Sg.F',
  'pousser.V2.Prs.3Sg.N',
  'voir.V1.Prs.3Sg.M',
  'arriver.V1.Pst.3Du.N',
  'supporter.V2.Prs.3Pl.N',
  'chercher.V2.Pst.3Sg.F',
  u'\xeatre.V1.Pst.3Sg.M',
  'supporter.V2.Prs.3Pl.M',
  'montrer.V1.Pst.3Sg.M',
  'offrir.V2.Prs.3Sg.M',
  'manger.V2.Pst.3Pl.M',
  'envahir.V1.Prs.3Pl.N',
  'manger.V2.Prs.3Du.M',
  'dormir.V2.Pst.3Sg.M',
  'offrir.V2.Pst.3Pl.M',
  'sauter.V2.Pst.3Sg.M',
  'offrir.V2.Pst.3Pl.N',
  'aller.V1.Pst.3Pl.M',
  'acheter.V1.Pst.3Sg.M',
  'offrir.V2.Pst.3Pl.F']}

In [39]:
def sortLevel(level):
    sortedLevel=level
    name="???"
    if "Erg" in level:
        sortedLevel=[f for f in "Erg Abs Dat Obl".split(" ") if f in level]
        name="Cas"
    elif "Acc" in level or "Nom" in level:
        sortedLevel=[f for f in "Nom Acc Dat Obl".split(" ") if f in level]
        name="Cas"
    elif "3Sg" in level:
        sortedLevel=[f for f in u"3Sg 3Du 3Pau 3Pl".split(" ") if f in level]
        name="Pers"
    elif "Sg" in level or "Pl" in level:
        sortedLevel=[f for f in u"Sg Du Pau Pl".split(" ") if f in level]
        name="Nombre"
    elif "Hum" in level or "Ani" in level:
        sortedLevel=[f for f in "Hum Ani Anim Ina Inan".split(" ") if f in level]
        name="Genre"
    elif "H" in level:
        sortedLevel=[f for f in "H A I".split(" ") if f in level]
        name="Genre"
    elif "M" in level or "F" in level or "N" in level:
        sortedLevel=[f for f in "M F N".split(" ") if f in level]
        name="Genre"
    elif "A" in level and "B" in level:
        sortedLevel=[f for f in "A B C D".split(" ") if f in level]
        name="Genre"
    elif "Def" in level:
        sortedLevel=[f for f in "Def Indef Ind Dem".split(" ") if f in level]
        name="DET"

    elif "Prs" in level:
        print level
        sortedLevel=[f for f in "Prs PRS Pst PST Fut FUT".split(" ") if f in level]
        name="Temps"
    elif "V1" in level or "N1" in level or "A1" in level:
        name="CF"
    elif "Vt" in level:
        name="Trans"
    return sortedLevel, name
        
def filledTable(fc,lexeme,rows,cols):
    filled=[f.split(".") for f in fc]
    filled=[f if "hyper" not in f else [c for c in f if c!="hyper"] for f in filled]
    print [f for f in filled if f and len(f)>5]
    for iF,f in enumerate(filled):
        filled[iF]=[c.capitalize() if c[0] not in "123" else c for c in f]
    dfFilled=pd.DataFrame(filled)
    dfFilled.columns=["C"+str(n) for n in dfFilled.columns.tolist()]
    if lexeme!=0:
        dfFilled["lexeme"]=dfFilled["C0"]
        lLexeme="lexeme"
    else:
        lLexeme="C"+str(lexeme)
    lRows=["C"+str(n) for n in rows]
    lCols=["C"+str(n) for n in cols]
#     display(dfFilled)

    
    result=pd.pivot_table(dfFilled,index=lRows,columns=lCols,values=lLexeme,aggfunc="count",dropna = False,fill_value=0)
#     display(result)
    if isinstance(result.index, pd.MultiIndex):
        levels=result.index.levels
        for iL,level in enumerate(levels):
            print iL, level
            sort,name=sortLevel(level)
            result=result.reindex(sort,level=iL)
            result.index=result.index.set_names(name, level=iL)
    else:
        sort,name=sortLevel(result.index)
        result=result.reindex(sort)
        result.index=result.index.set_names(name)

    if isinstance(result.columns, pd.MultiIndex):
        levels=result.columns.levels
        for iL,level in enumerate(levels):
            sort,name=sortLevel(level)
            result=result.reindex(sort,level=iL,axis=1)
            result.columns=result.columns.set_names(name, level=iL)
#             result=result.reindex(sortLevel(level),level=-iL,axis=1)
    else:
        sort,name=sortLevel(result.columns)
        result=result.reindex(sort,axis=1)
        result.columns=result.columns.set_names(name)

#         result=result.reindex(sortLevel(result.columns),axis=1)


    
    return result

In [40]:
tableauxRemplissage={}

# Paramétrage des remplissages

In [41]:
fc=filledCells["NOM"]
print fc[0]
tableauxRemplissage["NOM"]=filledTable(fc,0,[1],[2])
# tableauxRemplissage["NOM"]=filledTable(fc,0,[1],[3])
tableauxRemplissage["NOM"]=filledTable(fc,0,[2],[3])
# tableauxRemplissage["NOM"]=filledTable(fc,0,[1],[2,3])
# tableauxRemplissage["NOM"]=filledTable(fc,0,[1],[3,4])
# tableauxRemplissage["NOM"]=filledTable(fc,0,[2,1],[3,4])
# tableauxRemplissage["NOM"]=filledTable(fc,0,[2],[3,4])

balai.M.Pl.Nom
[]
[]

In [42]:
fc=filledCells["VER"]
print fc[0]
tableauxRemplissage["VER"]=filledTable(fc,0,[1],[2,3])
tableauxRemplissage["VER"]=filledTable(fc,0,[1,2],[3,4])
# tableauxRemplissage["VER"]=filledTable(fc,0,[2,3],[4,5])

lancer.V2.Pst.3Sg.M
[]
Index([u'Prs', u'Pst'], dtype='object', name=u'C2')
[]
0 Index([u'V1', u'V2'], dtype='object', name=u'C1')
1 Index([u'Prs', u'Pst'], dtype='object', name=u'C2')
Index([u'Prs', u'Pst'], dtype='object', name=u'C2')

In [43]:
fc=filledCells["ADJ"]
print fc[0]
tableauxRemplissage["ADJ"]=filledTable(fc,0,[1],[2])
# tableauxRemplissage["ADJ"]=filledTable(fc,0,[1],[2,3])
# tableauxRemplissage["ADJ"]=filledTable(fc,0,[1,2],[3,4])

différent.M.SG
[]

In [44]:
fc=filledCells["DET"]
print fc[0]
tableauxRemplissage["DET"]=filledTable(fc,0,[1],[2])
tableauxRemplissage["DET"]=filledTable(fc,0,[1],[2,3])
# tableauxRemplissage["DET"]=filledTable(fc,0,[1,2],[3,4])

DEF.N.SG.Nom
[]
[]

In [45]:
fc=filledCells["PRO"]
print fc[0]
if fc[0]:
    tableauxRemplissage["PRO"]=filledTable(fc,0,[1],[2])
    tableauxRemplissage["PRO"]=filledTable(fc,0,[1],[2,3])

PRO.M.Pl.Nom
[]
[]

# Tableaux remplis

In [46]:
tableauxLatexRemplissage=[]
tableauxLatexRemplissage.append(ur"\subsection*{Tableaux de remplissage}")
for cat in "DET PRO NOM ADJ VER".split(" "):
#    print ur"\section{%s}"%cat
    if cat in tableauxRemplissage:
        tableauxLatexRemplissage.append(u"%%\\columnbreak\n\\subsubsection*{%s}"%cat)
        tableauxLatexRemplissage.append(tableauxRemplissage[cat].to_latex(multirow=True)+u" \\\\ \\medskip")
        tableauxLatexRemplissage.append("")
print "\n".join(tableauxLatexRemplissage)

\subsection*{Tableaux de remplissage}
%\columnbreak
\subsubsection*{DET}
\begin{tabular}{lrrrrrrrrrrrr}
\toprule
Nombre & \multicolumn{4}{l}{Sg} & \multicolumn{4}{l}{Du} & \multicolumn{4}{l}{Pl} \\
Cas & Nom & Acc & Dat & Obl & Nom & Acc & Dat & Obl & Nom & Acc & Dat & Obl \\
Genre &     &     &     &     &     &     &     &     &     &     &     &     \\
\midrule
M     &   3 &   3 &   3 &   3 &   3 &   3 &   1 &   3 &   3 &   3 &   3 &   2 \\
F     &   3 &   3 &   2 &   3 &   3 &   3 &   3 &   3 &   3 &   2 &   2 &   3 \\
N     &   3 &   3 &   1 &   3 &   3 &   3 &   2 &   3 &   3 &   3 &   2 &   3 \\
\bottomrule
\end{tabular}
 \\ \medskip

%\columnbreak
\subsubsection*{PRO}
\begin{tabular}{lrrr}
\toprule
Nombre &  Sg &  Du &  Pl \\
Cas & Nom & Nom & Nom \\
Genre &     &     &     \\
\midrule
M     &   1 &   0 &   1 \\
F     &   1 &   0 &   1 \\
N     &   0 &   1 &   1 \\
\bottomrule
\end{tabular}
 \\ \medskip

%\columnbreak
\subsubsection*{NOM}
\begin{tabular}{lrrrr}
\toprule
Cas &  Nom &  Acc &  Dat &  Obl \\
Nombre &      &      &      &      \\
\midrule
Sg     &   51 &   54 &   23 &   58 \\
Du     &   33 &   17 &    8 &   20 \\
Pl     &   43 &   36 &   15 &   40 \\
\bottomrule
\end{tabular}
 \\ \medskip

%\columnbreak
\subsubsection*{ADJ}
\begin{tabular}{lrrr}
\toprule
Nombre &  Sg &  Du &  Pl \\
Genre &     &     &     \\
\midrule
M     &  16 &  13 &  13 \\
F     &  13 &   8 &  13 \\
N     &  11 &   7 &  16 \\
\bottomrule
\end{tabular}
 \\ \medskip

%\columnbreak
\subsubsection*{VER}
\begin{tabular}{llrrrrrrrrr}
\toprule
   & Pers & \multicolumn{3}{l}{3Sg} & \multicolumn{3}{l}{3Du} & \multicolumn{3}{l}{3Pl} \\
   & Genre &   M &   F &  N &   M &  F &  N &   M &  F &   N \\
CF & Temps &     &     &    &     &    &    &     &    &     \\
\midrule
\multirow{2}{*}{V1} & Prs &  15 &  14 &  6 &   6 &  5 &  4 &   9 &  5 &   8 \\
   & Pst &  11 &   9 &  4 &   6 &  7 &  2 &   9 &  7 &   3 \\
\cline{1-11}
\multirow{2}{*}{V2} & Prs &  10 &  15 &  7 &   6 &  5 &  3 &   8 &  7 &   5 \\
   & Pst &   9 &   8 &  2 &   3 &  3 &  6 &   4 &  7 &  11 \\
\bottomrule
\end{tabular}
 \\ \medskip

In [47]:
with codecs.open(serie+"Flexions.tex","w",encoding="utf8") as outFile:
    print "\n".join(tableauxLatex+cfLatex+genresLatex+tableauxLatexRemplissage)
    outFile.write("\n".join(tableauxLatex+cfLatex+genresLatex+tableauxLatexRemplissage))

\subsection*{Tableaux de flexion}
\subsubsection*{DET}
\needspace{6\baselineskip}
\noindent
DET IND => la\\
\begin{tabular}{lllll}
\toprule
    & Nombre &        Sg &        Du &        Pl \\
Cas & Genre &           &           &           \\
\midrule
\multirow{3}{*}{Acc} & F &  la-ʃ-a-s &  la-ʃ-a-d &  la-ʃ-a-θ \\
    & M &  la-s-a-s &  la-s-a-d &  la-s-a-θ \\
    & N &  la-ʒ-a-s &  la-ʒ-a-d &  la-ʒ-a-θ \\
\cline{1-5}
\multirow{3}{*}{Dat} & F &  la-ʃ-e-s &  la-ʃ-e-d &  la-ʃ-e-θ \\
    & M &  la-s-e-s &  la-s-e-d &  la-s-e-θ \\
    & N &  la-ʒ-e-s &  la-ʒ-e-d &  la-ʒ-e-θ \\
\cline{1-5}
\multirow{3}{*}{Nom} & F &  la-ʃ-o-s &  la-ʃ-o-d &  la-ʃ-o-θ \\
    & M &  la-s-o-s &  la-s-o-d &  la-s-o-θ \\
    & N &  la-ʒ-o-s &  la-ʒ-o-d &  la-ʒ-o-θ \\
\cline{1-5}
\multirow{3}{*}{Obl} & F &  la-ʃ-i-s &  la-ʃ-i-d &  la-ʃ-i-θ \\
    & M &  la-s-i-s &  la-s-i-d &  la-s-i-θ \\
    & N &  la-ʒ-i-s &  la-ʒ-i-d &  la-ʒ-i-θ \\
\bottomrule
\end{tabular}
 \\ \medskip

\subsubsection*{PRO}
\needspace{6\baselineskip}
\noindent
PRO PRO => ta\\
\begin{tabular}{lllll}
\toprule
    & Nombre &      Sg &        Du &        Pl \\
Cas & Genre &         &           &           \\
\midrule
\multirow{3}{*}{Acc} & F &  ta-s-a &  ta-s-a-m &  ta-s-a-z \\
    & M &  ta-t-a &  ta-t-a-m &  ta-t-a-z \\
    & N &  ta-l-a &  ta-l-a-m &  ta-l-a-z \\
\cline{1-5}
\multirow{3}{*}{Dat} & F &  ta-s-i &  ta-s-i-m &  ta-s-i-z \\
    & M &  ta-t-i &  ta-t-i-m &  ta-t-i-z \\
    & N &  ta-l-i &  ta-l-i-m &  ta-l-i-z \\
\cline{1-5}
\multirow{3}{*}{Nom} & F &  ta-s-u &  ta-s-u-m &  ta-s-u-z \\
    & M &  ta-t-u &  ta-t-u-m &  ta-t-u-z \\
    & N &  ta-l-u &  ta-l-u-m &  ta-l-u-z \\
\cline{1-5}
\multirow{3}{*}{Obl} & F &  ta-s-o &  ta-s-o-m &  ta-s-o-z \\
    & M &  ta-t-o &  ta-t-o-m &  ta-t-o-z \\
    & N &  ta-l-o &  ta-l-o-m &  ta-l-o-z \\
\bottomrule
\end{tabular}
 \\ \medskip

\subsubsection*{NOM}
\needspace{6\baselineskip}
\noindent
NOM couteau => pudoz\\
\begin{tabular}{llll}
\toprule
Nombre &          Sg &          Du &          Pl \\
Cas &             &             &             \\
\midrule
Acc &  ka-pudoz-i &  ka-pudoz-o &  ka-pudoz-a \\
Dat &  da-pudoz-i &  da-pudoz-o &  da-pudoz-a \\
Nom &  no-pudoz-i &  no-pudoz-o &  no-pudoz-a \\
Obl &   pudoz-n-i &   pudoz-n-o &   pudoz-n-a \\
\bottomrule
\end{tabular}
 \\ \medskip

\subsubsection*{ADJ}
\needspace{6\baselineskip}
\noindent
ADJ vert => bogok\\
\begin{tabular}{llll}
\toprule
Nombre &       Sg &         Du &         Pl \\
Genre &          &            &            \\
\midrule
F     &  bogok-a &  bogok-a-s &  bogok-a-b \\
M     &  bogok-o &    bogok-i &    bogok-i \\
N     &  bogok-u &  bogok-u-l &  bogok-u-s \\
\bottomrule
\end{tabular}
 \\ \medskip

\subsubsection*{VER}
\needspace{6\baselineskip}
\noindent
V1 être => nugut\\
\begin{tabular}{lllll}
\toprule
    & Pers &          3Sg &          3Du &          3Pl \\
Temps & Genre &              &              &              \\
\midrule
\multirow{3}{*}{PRS} & F &    nugut-a-p &  nugut-a-p-o &  nugut-a-p-i \\
    & M &    nugut-i-p &  nugut-i-p-o &  nugut-i-p-i \\
    & N &    nugut-u-p &  nugut-u-p-o &  nugut-u-p-i \\
\cline{1-5}
\multirow{3}{*}{PST} & F &  nugut-a-b-o &  nugut-a-b-u &  nugut-a-b-e \\
    & M &  nugut-i-b-o &  nugut-i-b-u &  nugut-i-b-e \\
    & N &  nugut-u-b-o &  nugut-u-b-u &  nugut-u-b-e \\
\bottomrule
\end{tabular}
 \\ \medskip

\needspace{6\baselineskip}
\noindent
V2 illustrer => putuk\\
\begin{tabular}{lllll}
\toprule
    & Pers &          3Sg &          3Du &          3Pl \\
Temps & Genre &              &              &              \\
\midrule
\multirow{3}{*}{PRS} & F &  putuk-a-p-a &  putuk-a-p-e &  putuk-a-p-u \\
    & M &  putuk-o-p-a &  putuk-o-p-e &  putuk-o-p-u \\
    & N &  putuk-u-p-a &  putuk-u-p-e &  putuk-u-p-u \\
\cline{1-5}
\multirow{3}{*}{PST} & F &    putuk-a-r &  putuk-a-r-u &  putuk-a-r-i \\
    & M &    putuk-o-r &  putuk-o-r-u &  putuk-o-r-i \\
    & N &    putuk-u-r &  putuk-u-r-u &  putuk-u-r-i \\
\bottomrule
\end{tabular}
 \\ \medskip

\subsection*{Classes flexionnelles}
VER :
\begin{description}
\item[- V1] accueillir, acheter, aller, allumer, apporter, approcher, arriver, arrêter, avoir, boire, brûler-med, changer, chasser-act, compter, connaître, donner, détester, enfermer, enlever, entrer, envahir, hurler, inquiéter, interroger, jardiner, lever, montrer, mourir, nourrir, noyer, parler, passer, pendre, planter, pleurer, pleurer-act, prendre, recouvrir, remercier, survoler, tourner-mov, transformer, transpercer, voir, voler, voler-act, voter, être
\item[- V2] attraper, brûler, cacher, chasser-mov, chercher, courir, demander, descendre, disparaître, dormir, découvrir, dévorer, embrasser, excuser, faire, fuir, illustrer, jeter, lancer, manger, manquer-med, nuire, offrir, partir, placer, porter, posséder, pousser, protéger, préparer, présenter, raconter, reconnaître, reconstruire, redevenir, rejoindre, ressusciter, retourner, revenir, rêvasser, sauter, sortir-mov, supporter, surplomber, tomber, vivre, échanger
\end{description}
\subsection*{Genre des noms}
\begin{description}
\item[- F] Agathos, Clemencia, Elphaba, Freja, Katisha, Mahira, Nicole, Violette, autruche, bras, chasseuse, chatte, chef, colère, coussin, coyote, côté, demande, disparition, femme, feu, fille, infirmière, lever-n, lit, livre, louve, lumière, légume, maison, mère, obscurité, peau, place, serpent, soeur, sortilège, souffrance, table, vengeance, villageoise, voleuse
\item[- M] Hoderi, Kaleb, Nabil, balai, chasseur, chat, combattant, corps, croc, douleur, dégât, démon, excuse, forêt, garçon, gorge, harmonie, histoire, homme, hurlement, jardin, jour, loup, lueur, lune, marais, nuit, oeil, poisson, proximité, père, raison, robe, souris, thé, tornade, viande, visage
\item[- N] arbre, blessure, bûcher, café, caillou, chambre, chemin, combat, construction, coup, couteau, crapaud, cri, créature, cuisine, dernier-n, donjon, dragon, enfant, esprit, fruit, gargouille, grimoire, héros, lance, loup, légende, main, manoir, matin, maître, milieu, mort, nouvelle-n, ombre, parent, plaine, sorcier, sort, village, villageois, vote, œuf
\end{description}
\subsection*{Tableaux de remplissage}
%\columnbreak
\subsubsection*{DET}
\begin{tabular}{lrrrrrrrrrrrr}
\toprule
Nombre & \multicolumn{4}{l}{Sg} & \multicolumn{4}{l}{Du} & \multicolumn{4}{l}{Pl} \\
Cas & Nom & Acc & Dat & Obl & Nom & Acc & Dat & Obl & Nom & Acc & Dat & Obl \\
Genre &     &     &     &     &     &     &     &     &     &     &     &     \\
\midrule
M     &   3 &   3 &   3 &   3 &   3 &   3 &   1 &   3 &   3 &   3 &   3 &   2 \\
F     &   3 &   3 &   2 &   3 &   3 &   3 &   3 &   3 &   3 &   2 &   2 &   3 \\
N     &   3 &   3 &   1 &   3 &   3 &   3 &   2 &   3 &   3 &   3 &   2 &   3 \\
\bottomrule
\end{tabular}
 \\ \medskip

%\columnbreak
\subsubsection*{PRO}
\begin{tabular}{lrrr}
\toprule
Nombre &  Sg &  Du &  Pl \\
Cas & Nom & Nom & Nom \\
Genre &     &     &     \\
\midrule
M     &   1 &   0 &   1 \\
F     &   1 &   0 &   1 \\
N     &   0 &   1 &   1 \\
\bottomrule
\end{tabular}
 \\ \medskip

%\columnbreak
\subsubsection*{NOM}
\begin{tabular}{lrrrr}
\toprule
Cas &  Nom &  Acc &  Dat &  Obl \\
Nombre &      &      &      &      \\
\midrule
Sg     &   51 &   54 &   23 &   58 \\
Du     &   33 &   17 &    8 &   20 \\
Pl     &   43 &   36 &   15 &   40 \\
\bottomrule
\end{tabular}
 \\ \medskip

%\columnbreak
\subsubsection*{ADJ}
\begin{tabular}{lrrr}
\toprule
Nombre &  Sg &  Du &  Pl \\
Genre &     &     &     \\
\midrule
M     &  16 &  13 &  13 \\
F     &  13 &   8 &  13 \\
N     &  11 &   7 &  16 \\
\bottomrule
\end{tabular}
 \\ \medskip

%\columnbreak
\subsubsection*{VER}
\begin{tabular}{llrrrrrrrrr}
\toprule
   & Pers & \multicolumn{3}{l}{3Sg} & \multicolumn{3}{l}{3Du} & \multicolumn{3}{l}{3Pl} \\
   & Genre &   M &   F &  N &   M &  F &  N &   M &  F &   N \\
CF & Temps &     &     &    &     &    &    &     &    &     \\
\midrule
\multirow{2}{*}{V1} & Prs &  15 &  14 &  6 &   6 &  5 &  4 &   9 &  5 &   8 \\
   & Pst &  11 &   9 &  4 &   6 &  7 &  2 &   9 &  7 &   3 \\
\cline{1-11}
\multirow{2}{*}{V2} & Prs &  10 &  15 &  7 &   6 &  5 &  3 &   8 &  7 &   5 \\
   & Pst &   9 &   8 &  2 &   3 &  3 &  6 &   4 &  7 &  11 \\
\bottomrule
\end{tabular}
 \\ \medskip

In [48]:
ding()